import { apiClient, getApiErrorMessage } from "@shared/services/api.client"; import type { PaginatedData, ResponseApi } from "@shared/types/api.response.types"; import { REPRESENTATIVE_ENDPOINTS } from "./representative.constants"; import type { RepresentativeCreateDataT, RepresentativeDeleteParamsT, RepresentativeGetParamsT, RepresentativeListParamsT, RepresentativeServiceT, RepresentativeT, RepresentativeUpdateParamsT } from "./representative.types";
class RepresentativeService implements RepresentativeServiceT {
  async list(p?: RepresentativeListParamsT): Promise<RepresentativeT[]> { try { const pg = p?.page ?? 1; const ps = p?.pageSize ?? 100; const sq = p?.search ? `&search=${encodeURIComponent(p.search)}` : ""; const oq = p?.ordering ? `&ordering=${encodeURIComponent(p.ordering)}` : ""; const { data } = await apiClient.get<ResponseApi<PaginatedData<RepresentativeT>>>(`${REPRESENTATIVE_ENDPOINTS.LIST}?page=${pg}&page_size=${ps}${sq}${oq}`); return data.data.results; } catch (error) { throw new Error(getApiErrorMessage(error), { cause: error }); } }
  async get(id: RepresentativeGetParamsT): Promise<RepresentativeT> { try { const { data } = await apiClient.get<ResponseApi<RepresentativeT>>(REPRESENTATIVE_ENDPOINTS.DETAIL(id)); return data.data; } catch (error) { throw new Error(getApiErrorMessage(error), { cause: error }); } }
  async create(d: RepresentativeCreateDataT): Promise<RepresentativeT> { try { const { data } = await apiClient.post<ResponseApi<RepresentativeT>>(REPRESENTATIVE_ENDPOINTS.LIST, d); return data.data; } catch (error) { throw new Error(getApiErrorMessage(error), { cause: error }); } }
  async update(p: RepresentativeUpdateParamsT): Promise<RepresentativeT> { try { const { data } = await apiClient.patch<ResponseApi<RepresentativeT>>(REPRESENTATIVE_ENDPOINTS.DETAIL(p.id), p.data); return data.data; } catch (error) { throw new Error(getApiErrorMessage(error), { cause: error }); } }
  async softDelete(id: RepresentativeDeleteParamsT): Promise<{ id: number }> { try { const { data } = await apiClient.post<ResponseApi<{ id: number }>>(REPRESENTATIVE_ENDPOINTS.SOFT_DELETE(id)); return data.data; } catch (error) { throw new Error(getApiErrorMessage(error), { cause: error }); } }
}
export const representativeService = new RepresentativeService();
