import { useAppDispatch, useAppSelector } from "@shared/redux/hooks"; import { useCallback, useState } from "react"; import { representativeService } from "./representative.service"; import { loadPending, loadSuccess, loadError, entityCreated, entityUpdated, entityDeleted, mutationError, selectRepresentatives, selectRepresentativesStatus, selectRepresentativesError } from "./representative.slice"; import type { RepresentativeCreateParamsT, RepresentativeDeleteParamsT, RepresentativeFormValues, RepresentativeListParamsT, RepresentativeT, RepresentativeUpdateParamsT } from "./representative.types";
export type CreateRejectValue = { msg: string; data: Record<string, string> | null; }; export type ValidationErrors = Record<string, string>; export interface SubmitErrorState { general: string[]; validation: ValidationErrors; }
const toRejectValue = (e: unknown): CreateRejectValue => { const msg = e instanceof Error ? e.message : "Error desconocido"; const cause = e instanceof Error ? (e as { cause?: unknown }).cause : undefined; const d = (cause as { response?: { data?: { data?: unknown } } })?.response?.data; return { msg, data: (d?.data as Record<string, string> | null) ?? null }; };
export const useRepresentativesController = () => {
  const dispatch = useAppDispatch(); const items = useAppSelector(selectRepresentatives); const status = useAppSelector(selectRepresentativesStatus); const error = useAppSelector(selectRepresentativesError);
  const load = useCallback(async (p?: RepresentativeListParamsT) => { dispatch(loadPending()); try { const items = await representativeService.list(p ?? { page: 1, pageSize: 100 }); dispatch(loadSuccess(items)); } catch (err) { dispatch(loadError(err instanceof Error ? err.message : "Error")); } }, [dispatch]);
  const create = useCallback(async (d: RepresentativeCreateParamsT): Promise<RepresentativeT> => { try { const c = await representativeService.create(d); dispatch(entityCreated(c)); return c; } catch (err) { const rv = toRejectValue(err); dispatch(mutationError(rv.msg)); throw rv; } }, [dispatch]);
  const update = useCallback(async (p: RepresentativeUpdateParamsT): Promise<RepresentativeT> => { try { const u = await representativeService.update(p); dispatch(entityUpdated(u)); return u; } catch (err) { const rv = toRejectValue(err); dispatch(mutationError(rv.msg)); throw rv; } }, [dispatch]);
  const remove = useCallback(async (id: RepresentativeDeleteParamsT): Promise<void> => { try { const { id: did } = await representativeService.softDelete(id); dispatch(entityDeleted(did)); } catch (err) { dispatch(mutationError(err instanceof Error ? err.message : "Error")); } }, [dispatch]);
  return { representatives: items, isLoading: status === "loading", error, loadRepresentatives: load, createRepresentative: create, updateRepresentative: update, deleteRepresentative: remove };
};
export type RepControllerT = ReturnType<typeof useRepresentativesController>;
const extractError = (e: unknown) => { if (e && typeof e === "object" && "msg" in e && typeof (e as { msg?: unknown }).msg === "string") { const obj = e as CreateRejectValue; const fes: ValidationErrors = {}; const gen: string[] = []; if (obj.data && typeof obj.data === "object") { for (const [k, v] of Object.entries(obj.data)) { if (typeof v === "string") fes[k] = v; else gen.push(`${k}: ${v}`); } } if (gen.length === 0 && Object.keys(fes).length === 0) gen.push(obj.msg); return { msg: obj.msg, general: gen, validation: fes }; } const msg = e instanceof Error ? e.message : "Error desconocido"; return { msg, general: [msg], validation: {} }; };
const uwCreate = async (d: RepresentativeCreateParamsT, create: RepControllerT["createRepresentative"]) => { try { return { ok: true as const, result: await create(d), errors: { general: [], validation: {} } as SubmitErrorState }; } catch (e) { const p = extractError(e); return { ok: false as const, result: null, errors: { general: p.general, validation: p.validation } as SubmitErrorState }; } };
const uwUpdate = async (p: RepresentativeUpdateParamsT, update: RepControllerT["updateRepresentative"]) => { try { return { ok: true as const, result: await update(p), errors: { general: [], validation: {} } as SubmitErrorState }; } catch (e) { const p2 = extractError(e); return { ok: false as const, result: null, errors: { general: p2.general, validation: p2.validation } as SubmitErrorState }; } };
interface UseFormArgs { create: RepControllerT["createRepresentative"]; update: RepControllerT["updateRepresentative"]; }
export const useRepresentativesForm = ({ create, update }: UseFormArgs) => {
  const [isOpen, setIsOpen] = useState(false); const [editing, setEditing] = useState<RepresentativeT | null>(null); const [submitErrors, setSubmitErrors] = useState<SubmitErrorState>({ general: [], validation: {} }); const isEdit = !!editing;
  const openModal = useCallback((r?: RepresentativeT) => { setEditing(r ?? null); setSubmitErrors({ general: [], validation: {} }); setIsOpen(true); }, []);
  const closeModal = useCallback(() => { setIsOpen(false); setEditing(null); setSubmitErrors({ general: [], validation: {} }); }, []);
  const handleSubmit = useCallback(async (values: RepresentativeFormValues) => { setSubmitErrors({ general: [], validation: {} }); if (editing) { const { dni, names, last_names, email, phone, address, city, document_type, is_active } = values; const r = await uwUpdate({ id: editing.id, data: { dni, names, last_names, email, phone, address, city, document_type, is_active } }, update); if (r.ok) { closeModal(); return; } setSubmitErrors(r.errors); } else { const { dni, names, last_names, email, phone, address, city, document_type } = values; const r = await uwCreate({ dni, names, last_names, email, phone, address, city, document_type }, create); if (r.ok) { closeModal(); return; } setSubmitErrors(r.errors); } }, [editing, create, update, closeModal]);
  return { isOpen, isEdit, editingRepresentative: editing, submitErrors, openModal, closeModal, handleSubmit };
};
