import { Plus } from "lucide-react"; import { useCallback, useState } from "react"; import { useRepresentativesController, useRepresentativesForm } from "./representative.controller"; import { RepresentativeDeleteModal } from "./components/RepresentativeDeleteModal"; import { RepresentativeFormModal } from "./components/RepresentativeFormModal"; import { RepresentativeTable } from "./components/RepresentativeTable"; import { RepresentativeViewModal } from "./components/RepresentativeViewModal"; import type { RepresentativeT } from "./representative.types";
export default function RepresentativesPage() {
  const { representatives, isLoading, loadRepresentatives, createRepresentative, updateRepresentative, deleteRepresentative } = useRepresentativesController();
  const { isOpen, isEdit, editingRepresentative, submitErrors, openModal, closeModal, handleSubmit } = useRepresentativesForm({ create: createRepresentative, update: updateRepresentative });
  const [viewing, setViewing] = useState<RepresentativeT | null>(null); const [isViewOpen, setIsViewOpen] = useState(false);
  const [deleting, setDeleting] = useState<RepresentativeT | null>(null); const [isDeleteOpen, setIsDeleteOpen] = useState(false);
  const openV = useCallback((r: RepresentativeT) => { setViewing(r); setIsViewOpen(true); }, []); const closeV = useCallback(() => { setViewing(null); setIsViewOpen(false); }, []);
  const openD = useCallback((r: RepresentativeT) => { setDeleting(r); setIsDeleteOpen(true); }, []); const closeD = useCallback(() => { setDeleting(null); setIsDeleteOpen(false); }, []);
  const handleDel = useCallback(async (id: number) => { await deleteRepresentative(id); }, [deleteRepresentative]);
  return (<div className="space-y-4"><div className="flex flex-col items-start justify-between gap-4 sm:flex-row sm:items-center"><div><h1 className="text-2xl font-extrabold text-slate-800">Representantes</h1><p className="mt-1 text-sm text-slate-500">Gestiona los representantes de estudiantes</p></div><button type="button" onClick={() => openModal()} className="inline-flex items-center gap-2 rounded-lg bg-primary px-4 py-2.5 text-sm font-bold text-white hover:bg-primary-hover"><Plus className="size-4" />Nuevo Representante</button></div><RepresentativeTable representatives={representatives} isLoading={isLoading} loadRepresentatives={loadRepresentatives} onEdit={openModal} onView={openV} onDelete={openD} /><RepresentativeFormModal isOpen={isOpen} onClose={closeModal} isEdit={isEdit} editingRepresentative={editingRepresentative} onSubmit={handleSubmit} submitErrors={submitErrors} /><RepresentativeViewModal isOpen={isViewOpen} representativeId={viewing?.id ?? null} onClose={closeV} /><RepresentativeDeleteModal isOpen={isDeleteOpen} representative={deleting} onClose={closeD} onConfirm={handleDel} /></div>);
}
