export interface EnrollmentInfo { id: number; student: number; section: number; section_name: string; school_year: number; enrollment_date: string; status: string; is_active: boolean; }
export interface AttendanceRecord { id: number; enrollment: number; enrollment_name: string; attendance_status: number; attendance_status_name: string; absence_type: number | null; absence_type_name: string; attendance_date: string; }
export interface AttendanceSummary { present: number; absent: number; late: number; total: number; }
export interface GradeActivity { evaluative_activity_id: number; evaluative_activity_title: string; activity_type_name: string; max_score: number; score: number | null; qualitative_scale_name: string | null; due_date: string; }
export interface SubjectGrades { subject: string; subject_offering: number; activities: GradeActivity[]; }
export interface StudentNoteRaw { id: number; enrollment: number; evaluative_activity: number; enrollment_name: string; evaluative_activity_title: string; numeric_score: number | null; subject_offering: number | null; subject_offering_name: string | null; activity_type: number | null; activity_type_name: string | null; max_score: string | null; academic_period: number | null; academic_period_name: string | null; }
export interface PeriodGradeSummaryRaw { id: number; enrollment_name: string; subject_offering_name: string; formative_avg: number; summative_avg: number; final_avg_truncated: number; qualitative_scale_name: string; is_failing: boolean; }
export interface BehaviorEvaluationRaw { id: number; enrollment_name: string; academic_period_name: string; final_scale: number | null; calculated_scale: number; final_scale_name: string | null; calculated_scale_name: string; general_observation: string; evaluation_date: string; }
export interface ConductIncidentRaw { id: number; enrollment_name: string; incident_type_name: string; severity_name: string; incident_date: string; description: string; }
