import { apiClient, getApiErrorMessage } from "@shared/services/api.client"; import type { PaginatedData, ResponseApi } from "@shared/types/api.response.types"; import { EVALUATIVE_ACTIVITY_ENDPOINTS } from "./evaluative-activities.constants"; import type { EvaluativeActivityCreateDataT, EvaluativeActivityDeleteParamsT, EvaluativeActivityGetParamsT, EvaluativeActivityListParamsT, EvaluativeActivityServiceT, EvaluativeActivityT, EvaluativeActivityUpdateParamsT } from "./evaluative-activities.types";
class EvaluativeActivityService implements EvaluativeActivityServiceT {
  async list(p?: EvaluativeActivityListParamsT): Promise<EvaluativeActivityT[]> { try { const page = p?.page ?? 1; const pageSize = p?.pageSize ?? 100; const sq = p?.search ? `&search=${encodeURIComponent(p.search)}` : ""; const oq = p?.ordering ? `&ordering=${encodeURIComponent(p.ordering)}` : ""; const filters = p?.filters ?? {}; const fq = Object.entries(filters).filter(([, v]) => v !== undefined && v !== null).map(([k, v]) => `&${k}=${encodeURIComponent(String(v))}`).join(""); const { data } = await apiClient.get<ResponseApi<PaginatedData<EvaluativeActivityT>>>(`${EVALUATIVE_ACTIVITY_ENDPOINTS.LIST}?page=${page}&page_size=${pageSize}${sq}${oq}${fq}`); return data.data.results; } catch (error) { throw new Error(getApiErrorMessage(error), { cause: error }); } }
  async get(id: EvaluativeActivityGetParamsT): Promise<EvaluativeActivityT> { try { const { data } = await apiClient.get<ResponseApi<EvaluativeActivityT>>(EVALUATIVE_ACTIVITY_ENDPOINTS.DETAIL(id)); return data.data; } catch (error) { throw new Error(getApiErrorMessage(error), { cause: error }); } }
  async create(d: EvaluativeActivityCreateDataT): Promise<EvaluativeActivityT> { try { const { data } = await apiClient.post<ResponseApi<EvaluativeActivityT>>(EVALUATIVE_ACTIVITY_ENDPOINTS.LIST, d); return data.data; } catch (error) { throw new Error(getApiErrorMessage(error), { cause: error }); } }
  async update(p: EvaluativeActivityUpdateParamsT): Promise<EvaluativeActivityT> { try { const { data } = await apiClient.patch<ResponseApi<EvaluativeActivityT>>(EVALUATIVE_ACTIVITY_ENDPOINTS.DETAIL(p.id), p.data); return data.data; } catch (error) { throw new Error(getApiErrorMessage(error), { cause: error }); } }
  async softDelete(id: EvaluativeActivityDeleteParamsT): Promise<{ id: number }> { try { const { data } = await apiClient.post<ResponseApi<{ id: number }>>(EVALUATIVE_ACTIVITY_ENDPOINTS.SOFT_DELETE(id)); return data.data; } catch (error) { throw new Error(getApiErrorMessage(error), { cause: error }); } }
}
export const evaluativeActivityService = new EvaluativeActivityService();
