import { useAppDispatch, useAppSelector } from "@shared/redux/hooks"; import { useCallback, useState } from "react"; import { evaluativeActivityService } from "./evaluative-activities.service"; import { loadPending, loadSuccess, loadError, entityCreated, entityUpdated, entityDeleted, mutationError, selectEvaluativeActivities, selectEvaluativeActivitiesStatus, selectEvaluativeActivityError } from "./evaluative-activities.slice"; import type { EvaluativeActivityCreateDataT, EvaluativeActivityCreateParamsT, EvaluativeActivityDeleteParamsT, EvaluativeActivityFormValues, EvaluativeActivityListParamsT, EvaluativeActivityT, EvaluativeActivityUpdateParamsT } from "./evaluative-activities.types";
export type CreateRejectValue = { msg: string; data: Record<string, string> | null; }; export type ValidationErrors = Record<string, string>; export interface SubmitErrorState { general: string[]; validation: ValidationErrors; }
const toRejectValue = (e: unknown): CreateRejectValue => { const msg = e instanceof Error ? e.message : "Error desconocido"; const cause = e instanceof Error ? (e as { cause?: unknown }).cause : undefined; const d = (cause as { response?: { data?: { data?: unknown } } })?.response?.data; return { msg, data: (d?.data as Record<string, string> | null) ?? null }; };
export const useEvaluativeActivityController = () => {
  const dispatch = useAppDispatch(); const evaluativeActivities = useAppSelector(selectEvaluativeActivities); const status = useAppSelector(selectEvaluativeActivitiesStatus); const error = useAppSelector(selectEvaluativeActivityError);
  const loadEvaluativeActivities = useCallback(async (p?: EvaluativeActivityListParamsT) => { dispatch(loadPending()); try { const items = await evaluativeActivityService.list(p ?? { page: 1, pageSize: 100 }); dispatch(loadSuccess(items)); } catch (err) { dispatch(loadError(err instanceof Error ? err.message : "Error")); } }, [dispatch]);
  const create = useCallback(async (d: EvaluativeActivityCreateParamsT): Promise<EvaluativeActivityT> => { try { const c = await evaluativeActivityService.create(d); dispatch(entityCreated(c)); return c; } catch (err) { const rv = toRejectValue(err); dispatch(mutationError(rv.msg)); throw rv; } }, [dispatch]);
  const update = useCallback(async (p: EvaluativeActivityUpdateParamsT): Promise<EvaluativeActivityT> => { try { const u = await evaluativeActivityService.update(p); dispatch(entityUpdated(u)); return u; } catch (err) { const rv = toRejectValue(err); dispatch(mutationError(rv.msg)); throw rv; } }, [dispatch]);
  const remove = useCallback(async (id: EvaluativeActivityDeleteParamsT): Promise<void> => { try { const { id: did } = await evaluativeActivityService.softDelete(id); dispatch(entityDeleted(did)); } catch (err) { dispatch(mutationError(err instanceof Error ? err.message : "Error")); } }, [dispatch]);
  return { evaluativeActivities, isLoading: status === "loading", error, loadEvaluativeActivities, createEvaluativeActivity: create, updateEvaluativeActivity: update, deleteEvaluativeActivity: remove };
};
export type EAControllerT = ReturnType<typeof useEvaluativeActivityController>;
const extractError = (e: unknown) => { if (e && typeof e === "object" && "msg" in e && typeof (e as { msg?: unknown }).msg === "string") { const obj = e as CreateRejectValue; const fes: ValidationErrors = {}; const gen: string[] = []; if (obj.data && typeof obj.data === "object") { for (const [k, v] of Object.entries(obj.data)) { if (typeof v === "string") fes[k] = v; else gen.push(`${k}: ${v}`); } } if (gen.length === 0 && Object.keys(fes).length === 0) gen.push(obj.msg); return { msg: obj.msg, general: gen, validation: fes }; } const msg = e instanceof Error ? e.message : "Error desconocido"; return { msg, general: [msg], validation: {} }; };
const uwCreate = async (d: EvaluativeActivityCreateDataT, create: EAControllerT["createEvaluativeActivity"]) => { try { return { ok: true as const, result: await create(d), errors: { general: [], validation: {} } as SubmitErrorState }; } catch (e) { const p = extractError(e); return { ok: false as const, result: null, errors: { general: p.general, validation: p.validation } as SubmitErrorState }; } };
const uwUpdate = async (p: EvaluativeActivityUpdateParamsT, update: EAControllerT["updateEvaluativeActivity"]) => { try { return { ok: true as const, result: await update(p), errors: { general: [], validation: {} } as SubmitErrorState }; } catch (e) { const p2 = extractError(e); return { ok: false as const, result: null, errors: { general: p2.general, validation: p2.validation } as SubmitErrorState }; } };
interface UseFormArgs { create: EAControllerT["createEvaluativeActivity"]; update: EAControllerT["updateEvaluativeActivity"]; }
export const useEvaluativeActivityForm = ({ create, update }: UseFormArgs) => {
  const [isOpen, setIsOpen] = useState(false); const [editing, setEditing] = useState<EvaluativeActivityT | null>(null); const [submitErrors, setSubmitErrors] = useState<SubmitErrorState>({ general: [], validation: {} }); const isEdit = !!editing;
  const openModal = useCallback((a?: EvaluativeActivityT) => { setEditing(a ?? null); setSubmitErrors({ general: [], validation: {} }); setIsOpen(true); }, []);
  const closeModal = useCallback(() => { setIsOpen(false); setEditing(null); setSubmitErrors({ general: [], validation: {} }); }, []);
  const handleSubmit = useCallback(async (values: EvaluativeActivityFormValues) => { setSubmitErrors({ general: [], validation: {} }); if (editing) { const { title, teacher_subject_section, activity_type, max_score, due_date, is_active } = values; const r = await uwUpdate({ id: editing.id, data: { title, teacher_subject_section, activity_type, max_score, due_date, is_active } }, update); if (r.ok) { closeModal(); return; } setSubmitErrors(r.errors); } else { const { title, teacher_subject_section, activity_type, max_score, due_date } = values; const r = await uwCreate({ title, teacher_subject_section, activity_type, max_score, due_date, block_component: values.block_component, internal_weight: values.internal_weight }, create); if (r.ok) { closeModal(); return; } setSubmitErrors(r.errors); } }, [editing, create, update, closeModal]);
  return { isOpen, isEdit, editingEvaluativeActivity: editing, submitErrors, openModal, closeModal, handleSubmit };
};
