import { apiClient, getApiErrorMessage } from "@shared/services/api.client"; import type { PaginatedData, ResponseApi } from "@shared/types/api.response.types"; import { SECTION_ENDPOINTS } from "./section.constants"; import type { SectionCreateDataT, SectionDeleteParamsT, SectionGetParamsT, SectionListParamsT, SectionServiceT, SectionT, SectionUpdateParamsT } from "./section.types";
class SectionService implements SectionServiceT {
  async list(p?: SectionListParamsT): Promise<SectionT[]> { try { const pg = p?.page ?? 1; const ps = p?.pageSize ?? 100; const sq = p?.search ? `&search=${encodeURIComponent(p.search)}` : ""; const oq = p?.ordering ? `&ordering=${encodeURIComponent(p.ordering)}` : ""; const { data } = await apiClient.get<ResponseApi<PaginatedData<SectionT>>>(`${SECTION_ENDPOINTS.LIST}?page=${pg}&page_size=${ps}${sq}${oq}`); return data.data.results; } catch (error) { throw new Error(getApiErrorMessage(error), { cause: error }); } }
  async get(id: SectionGetParamsT): Promise<SectionT> { try { const { data } = await apiClient.get<ResponseApi<SectionT>>(SECTION_ENDPOINTS.DETAIL(id)); return data.data; } catch (error) { throw new Error(getApiErrorMessage(error), { cause: error }); } }
  async create(d: SectionCreateDataT): Promise<SectionT> { try { const { data } = await apiClient.post<ResponseApi<SectionT>>(SECTION_ENDPOINTS.LIST, d); return data.data; } catch (error) { throw new Error(getApiErrorMessage(error), { cause: error }); } }
  async update(p: SectionUpdateParamsT): Promise<SectionT> { try { const { data } = await apiClient.patch<ResponseApi<SectionT>>(SECTION_ENDPOINTS.DETAIL(p.id), p.data); return data.data; } catch (error) { throw new Error(getApiErrorMessage(error), { cause: error }); } }
  async softDelete(id: SectionDeleteParamsT): Promise<{ id: number }> { try { const { data } = await apiClient.post<ResponseApi<{ id: number }>>(SECTION_ENDPOINTS.SOFT_DELETE(id)); return data.data; } catch (error) { throw new Error(getApiErrorMessage(error), { cause: error }); } }
}
export const sectionService = new SectionService();
