import { Plus } from "lucide-react"; import { useCallback, useState } from "react"; import { useSectionController, useSectionForm } from "./section.controller"; import { useAcademicGradeOptions, useSchoolYearOptions } from "./section.options"; import { SectionDeleteModal } from "./components/SectionDeleteModal"; import { SectionFormModal } from "./components/SectionFormModal"; import { SectionTable } from "./components/SectionTable"; import { SectionViewModal } from "./components/SectionViewModal"; import type { SectionT } from "./section.types";
export default function SectionsPage() {
  const { sections, isLoading, loadSections, createSection, updateSection, deleteSection } = useSectionController();
  const { isOpen, isEdit, editingSection, submitErrors, openModal, closeModal, handleSubmit } = useSectionForm({ create: createSection, update: updateSection });
  const { academicGradeOptions } = useAcademicGradeOptions();
  const { schoolYearOptions } = useSchoolYearOptions();
  const [viewing, setViewing] = useState<SectionT | null>(null); const [isViewOpen, setIsViewOpen] = useState(false);
  const [deleting, setDeleting] = useState<SectionT | null>(null); const [isDeleteOpen, setIsDeleteOpen] = useState(false);
  const openV = useCallback((s: SectionT) => { setViewing(s); setIsViewOpen(true); }, []); const closeV = useCallback(() => { setViewing(null); setIsViewOpen(false); }, []);
  const openD = useCallback((s: SectionT) => { setDeleting(s); setIsDeleteOpen(true); }, []); const closeD = useCallback(() => { setDeleting(null); setIsDeleteOpen(false); }, []);
  const handleDel = useCallback(async (id: number) => { await deleteSection(id); }, [deleteSection]);
  return (<div className="space-y-4"><div className="flex flex-col items-start justify-between gap-4 sm:flex-row sm:items-center"><div><h1 className="text-2xl font-extrabold text-slate-800">Secciones</h1><p className="mt-1 text-sm text-slate-500">Gestiona las secciones/paralelos</p></div><button type="button" onClick={() => openModal()} className="inline-flex items-center gap-2 rounded-lg bg-primary px-4 py-2.5 text-sm font-bold text-white hover:bg-primary-hover"><Plus className="size-4" />Nueva Sección</button></div><SectionTable sections={sections} isLoading={isLoading} loadSections={loadSections} onEdit={openModal} onView={openV} onDelete={openD} /><SectionFormModal isOpen={isOpen} onClose={closeModal} isEdit={isEdit} editingSection={editingSection} onSubmit={handleSubmit} submitErrors={submitErrors} academicGradeOptions={academicGradeOptions} schoolYearOptions={schoolYearOptions} /><SectionViewModal isOpen={isViewOpen} sectionId={viewing?.id ?? null} onClose={closeV} /><SectionDeleteModal isOpen={isDeleteOpen} section={deleting} onClose={closeD} onConfirm={handleDel} /></div>);
}
