import { useAppDispatch, useAppSelector } from "@shared/redux/hooks"; import { useCallback, useState } from "react"; import { studentNoteService } from "./student-notes.service"; import { loadPending, loadSuccess, loadError, entityCreated, entityUpdated, entityDeleted, mutationError, selectStudentNotes, selectStudentNotesStatus, selectStudentNotesError } from "./student-notes.slice"; import type { StudentNoteCreateDataT, StudentNoteCreateParamsT, StudentNoteDeleteParamsT, StudentNoteFormValues, StudentNoteListParamsT, StudentNoteT, StudentNoteUpdateParamsT } from "./student-notes.types";
export type CreateRejectValue = { msg: string; data: Record<string, string> | null; }; export type ValidationErrors = Record<string, string>; export interface SubmitErrorState { general: string[]; validation: ValidationErrors; }
const toRejectValue = (e: unknown): CreateRejectValue => { const msg = e instanceof Error ? e.message : "Error desconocido"; const cause = e instanceof Error ? (e as { cause?: unknown }).cause : undefined; const d = (cause as { response?: { data?: { data?: unknown } } })?.response?.data; return { msg, data: (d?.data as Record<string, string> | null) ?? null }; };
export const useStudentNotesController = () => {
  const dispatch = useAppDispatch(); const items = useAppSelector(selectStudentNotes); const status = useAppSelector(selectStudentNotesStatus); const error = useAppSelector(selectStudentNotesError);
  const load = useCallback(async (p?: StudentNoteListParamsT) => { dispatch(loadPending()); try { const items = await studentNoteService.list(p ?? { page: 1, pageSize: 100 }); dispatch(loadSuccess(items)); } catch (err) { dispatch(loadError(err instanceof Error ? err.message : "Error")); } }, [dispatch]);
  const create = useCallback(async (d: StudentNoteCreateParamsT): Promise<StudentNoteT> => { try { const c = await studentNoteService.create(d); dispatch(entityCreated(c)); return c; } catch (err) { const rv = toRejectValue(err); dispatch(mutationError(rv.msg)); throw rv; } }, [dispatch]);
  const update = useCallback(async (p: StudentNoteUpdateParamsT): Promise<StudentNoteT> => { try { const u = await studentNoteService.update(p); dispatch(entityUpdated(u)); return u; } catch (err) { const rv = toRejectValue(err); dispatch(mutationError(rv.msg)); throw rv; } }, [dispatch]);
  const remove = useCallback(async (id: StudentNoteDeleteParamsT): Promise<void> => { try { const { id: did } = await studentNoteService.softDelete(id); dispatch(entityDeleted(did)); } catch (err) { dispatch(mutationError(err instanceof Error ? err.message : "Error")); } }, [dispatch]);
  return { studentNotes: items, isLoading: status === "loading", error, loadStudentNotes: load, createStudentNote: create, updateStudentNote: update, deleteStudentNote: remove };
};
export type SNControllerT = ReturnType<typeof useStudentNotesController>;
const extractError = (e: unknown) => { if (e && typeof e === "object" && "msg" in e && typeof (e as { msg?: unknown }).msg === "string") { const obj = e as CreateRejectValue; const fes: ValidationErrors = {}; const gen: string[] = []; if (obj.data && typeof obj.data === "object") { for (const [k, v] of Object.entries(obj.data)) { if (typeof v === "string") fes[k] = v; else gen.push(`${k}: ${v}`); } } if (gen.length === 0 && Object.keys(fes).length === 0) gen.push(obj.msg); return { msg: obj.msg, general: gen, validation: fes }; } const msg = e instanceof Error ? e.message : "Error desconocido"; return { msg, general: [msg], validation: {} }; };
const uwCreate = async (d: StudentNoteCreateDataT, create: SNControllerT["createStudentNote"]) => { try { return { ok: true as const, result: await create(d), errors: { general: [], validation: {} } as SubmitErrorState }; } catch (e) { const p = extractError(e); return { ok: false as const, result: null, errors: { general: p.general, validation: p.validation } as SubmitErrorState }; } };
const uwUpdate = async (p: StudentNoteUpdateParamsT, update: SNControllerT["updateStudentNote"]) => { try { return { ok: true as const, result: await update(p), errors: { general: [], validation: {} } as SubmitErrorState }; } catch (e) { const p2 = extractError(e); return { ok: false as const, result: null, errors: { general: p2.general, validation: p2.validation } as SubmitErrorState }; } };
interface UseFormArgs { create: SNControllerT["createStudentNote"]; update: SNControllerT["updateStudentNote"]; }
export const useStudentNotesForm = ({ create, update }: UseFormArgs) => {
  const [isOpen, setIsOpen] = useState(false); const [editing, setEditing] = useState<StudentNoteT | null>(null); const [submitErrors, setSubmitErrors] = useState<SubmitErrorState>({ general: [], validation: {} }); const isEdit = !!editing;
  const openModal = useCallback((s?: StudentNoteT) => { setEditing(s ?? null); setSubmitErrors({ general: [], validation: {} }); setIsOpen(true); }, []);
  const closeModal = useCallback(() => { setIsOpen(false); setEditing(null); setSubmitErrors({ general: [], validation: {} }); }, []);
  const handleSubmit = useCallback(async (values: StudentNoteFormValues) => { setSubmitErrors({ general: [], validation: {} }); if (editing) { const r = await uwUpdate({ id: editing.id, data: { enrollment: values.enrollment === "" ? undefined : values.enrollment, evaluative_activity: values.evaluative_activity === "" ? undefined : values.evaluative_activity, grading_mode: values.grading_mode, numeric_score: values.numeric_score, qualitative_scale: values.qualitative_scale === "" ? null : values.qualitative_scale, teacher_observation: values.teacher_observation } }, update); if (r.ok) { closeModal(); return; } setSubmitErrors(r.errors); } else { const { enrollment, evaluative_activity, grading_mode, numeric_score, qualitative_scale, teacher_observation } = values; const r = await uwCreate({ enrollment: enrollment as number, evaluative_activity: evaluative_activity as number, grading_mode, numeric_score, qualitative_scale: qualitative_scale === "" ? null : qualitative_scale, teacher_observation, created_by: null, modified_by: null }, create); if (r.ok) { closeModal(); return; } setSubmitErrors(r.errors); } }, [editing, create, update, closeModal]);
  return { isOpen, isEdit, editingStudentNote: editing, submitErrors, openModal, closeModal, handleSubmit };
};
