import { Plus } from "lucide-react"; import { useCallback, useState } from "react"; import { useStudentNotesController, useStudentNotesForm } from "./student-notes.controller"; import { useStudentNoteOptions } from "./student-notes.options"; import { StudentNoteDeleteModal } from "./components/StudentNoteDeleteModal"; import { StudentNotesFormModal } from "./components/StudentNotesFormModal"; import { StudentNotesTable } from "./components/StudentNotesTable"; import { StudentNoteViewModal } from "./components/StudentNoteViewModal"; import type { StudentNoteT } from "./student-notes.types";
export default function StudentNotesPage() {
  const { studentNotes, isLoading, loadStudentNotes, createStudentNote, updateStudentNote, deleteStudentNote } = useStudentNotesController();
  const { isOpen, isEdit, editingStudentNote, submitErrors, openModal, closeModal, handleSubmit } = useStudentNotesForm({ create: createStudentNote, update: updateStudentNote });
  const { enrollmentOptions, evaluativeActivityOptions, gradeTypeOptions, qualitativeScaleOptions } = useStudentNoteOptions();
  const [viewing, setViewing] = useState<StudentNoteT | null>(null); const [isViewOpen, setIsViewOpen] = useState(false);
  const [deleting, setDeleting] = useState<StudentNoteT | null>(null); const [isDeleteOpen, setIsDeleteOpen] = useState(false);
  const openV = useCallback((n: StudentNoteT) => { setViewing(n); setIsViewOpen(true); }, []); const closeV = useCallback(() => { setViewing(null); setIsViewOpen(false); }, []);
  const openD = useCallback((n: StudentNoteT) => { setDeleting(n); setIsDeleteOpen(true); }, []); const closeD = useCallback(() => { setDeleting(null); setIsDeleteOpen(false); }, []);
  const handleDel = useCallback(async (id: number) => { await deleteStudentNote(id); }, [deleteStudentNote]);
  return (<div className="space-y-4"><div className="flex flex-col items-start justify-between gap-4 sm:flex-row sm:items-center"><div><h1 className="text-2xl font-extrabold text-slate-800">Notas de Estudiantes</h1><p className="mt-1 text-sm text-slate-500">Gestiona las notas académicas de los estudiantes</p></div><button type="button" onClick={() => openModal()} className="inline-flex items-center gap-2 rounded-lg bg-primary px-4 py-2.5 text-sm font-bold text-white hover:bg-primary-hover"><Plus className="size-4" />Nueva Nota</button></div><StudentNotesTable studentNotes={studentNotes} isLoading={isLoading} loadStudentNotes={loadStudentNotes} onEdit={openModal} onView={openV} onDelete={openD} /><StudentNotesFormModal isOpen={isOpen} onClose={closeModal} isEdit={isEdit} editingStudentNote={editingStudentNote} onSubmit={handleSubmit} submitErrors={submitErrors} enrollmentOptions={enrollmentOptions} evaluativeActivityOptions={evaluativeActivityOptions} gradeTypeOptions={gradeTypeOptions} qualitativeScaleOptions={qualitativeScaleOptions} /><StudentNoteViewModal isOpen={isViewOpen} studentNoteId={viewing?.id ?? null} onClose={closeV} /><StudentNoteDeleteModal isOpen={isDeleteOpen} studentNote={deleting} onClose={closeD} onConfirm={handleDel} /></div>);
}
