import { enrollmentService } from "@features/students/enrollments/enrollments.service"; import { evaluativeActivityService } from "@features/grading/evaluative-activities/evaluative-activities.service"; import { qualitativeScaleService } from "@features/grading/qualitative-scales/qualitative-scales.service"; import { useEffect, useReducer } from "react";
interface O { label: string; value: string; }
interface S { enrollmentOptions: O[]; evaluativeActivityOptions: O[]; qualitativeScaleOptions: O[]; loading: boolean; }
type A = { type: "loading" } | { type: "success"; enrollments: O[]; evaluativeActivities: O[]; qualitativeScales: O[] } | { type: "error" };
function r(s: S, a: A): S { switch (a.type) { case "loading": return { ...s, loading: true }; case "success": return { ...s, loading: false, enrollmentOptions: a.enrollments, evaluativeActivityOptions: a.evaluativeActivities, qualitativeScaleOptions: a.qualitativeScales }; case "error": return { ...s, loading: false }; } }
const GRADING_MODES: O[] = [{ label: "Numérica", value: "NUMERIC" }, { label: "Cualitativa", value: "QUALITATIVE" }, { label: "Mixta", value: "MIXED" }];
export const useStudentNoteOptions = () => {
  const [state, dispatch] = useReducer(r, { enrollmentOptions: [], evaluativeActivityOptions: [], qualitativeScaleOptions: [], loading: true });
  useEffect(() => { let c = false; dispatch({ type: "loading" }); Promise.all([enrollmentService.list({ page: 1, pageSize: 100 }), evaluativeActivityService.list({ page: 1, pageSize: 100 }), qualitativeScaleService.list({ page: 1, pageSize: 100 })]).then(([enrollments, eas, qs]) => { if (c) return; dispatch({ type: "success", enrollments: enrollments.map((i) => ({ label: i.student_name, value: String(i.id) })), evaluativeActivities: eas.map((i) => ({ label: i.title, value: String(i.id) })), qualitativeScales: qs.filter((i) => i.is_active).map((i) => ({ label: i.name, value: String(i.id) })) }); }).catch(() => { if (!c) dispatch({ type: "error" }); }); return () => { c = true; }; }, []);
  return { enrollmentOptions: state.enrollmentOptions, evaluativeActivityOptions: state.evaluativeActivityOptions, qualitativeScaleOptions: state.qualitativeScaleOptions, gradeTypeOptions: GRADING_MODES, loading: state.loading };
};
