import { useAppDispatch, useAppSelector } from "@shared/redux/hooks"; import { useCallback, useState } from "react"; import { enrollmentService } from "./enrollments.service"; import { loadPending, loadSuccess, loadError, entityCreated, entityUpdated, entityDeleted, mutationError, selectEnrollments, selectEnrollmentsStatus, selectEnrollmentsError } from "./enrollments.slice"; import type { EnrollmentCreateParamsT, EnrollmentDeleteParamsT, EnrollmentListParamsT, EnrollmentT, EnrollmentUpdateParamsT } from "./enrollments.types";
export type CreateRejectValue = { msg: string; data: Record<string, string> | null; }; export type ValidationErrors = Record<string, string>; export interface SubmitErrorState { general: string[]; validation: ValidationErrors; }
const toRejectValue = (e: unknown): CreateRejectValue => { const msg = e instanceof Error ? e.message : "Error desconocido"; const cause = e instanceof Error ? (e as { cause?: unknown }).cause : undefined; const d = (cause as { response?: { data?: { data?: unknown } } })?.response?.data; return { msg, data: (d?.data as Record<string, string> | null) ?? null }; };
export const useEnrollmentsController = () => {
  const dispatch = useAppDispatch(); const items = useAppSelector(selectEnrollments); const status = useAppSelector(selectEnrollmentsStatus); const error = useAppSelector(selectEnrollmentsError);
  const load = useCallback(async (p?: EnrollmentListParamsT) => { dispatch(loadPending()); try { const items = await enrollmentService.list(p ?? { page: 1, pageSize: 100 }); dispatch(loadSuccess(items)); } catch (err) { dispatch(loadError(err instanceof Error ? err.message : "Error")); } }, [dispatch]);
  const create = useCallback(async (d: EnrollmentCreateParamsT): Promise<EnrollmentT> => { try { const c = await enrollmentService.create(d); dispatch(entityCreated(c)); return c; } catch (err) { const rv = toRejectValue(err); dispatch(mutationError(rv.msg)); throw rv; } }, [dispatch]);
  const update = useCallback(async (p: EnrollmentUpdateParamsT): Promise<EnrollmentT> => { try { const u = await enrollmentService.update(p); dispatch(entityUpdated(u)); return u; } catch (err) { const rv = toRejectValue(err); dispatch(mutationError(rv.msg)); throw rv; } }, [dispatch]);
  const remove = useCallback(async (id: EnrollmentDeleteParamsT): Promise<void> => { try { const { id: did } = await enrollmentService.softDelete(id); dispatch(entityDeleted(did)); } catch (err) { dispatch(mutationError(err instanceof Error ? err.message : "Error")); } }, [dispatch]);
  return { enrollments: items, isLoading: status === "loading", error, loadEnrollments: load, createEnrollment: create, updateEnrollment: update, deleteEnrollment: remove };
};
export type EnrControllerT = ReturnType<typeof useEnrollmentsController>;
const extractError = (e: unknown) => { if (e && typeof e === "object" && "msg" in e && typeof (e as { msg?: unknown }).msg === "string") { const obj = e as CreateRejectValue; const fes: ValidationErrors = {}; const gen: string[] = []; if (obj.data && typeof obj.data === "object") { for (const [k, v] of Object.entries(obj.data)) { if (typeof v === "string") fes[k] = v; else gen.push(`${k}: ${v}`); } } if (gen.length === 0 && Object.keys(fes).length === 0) gen.push(obj.msg); return { msg: obj.msg, general: gen, validation: fes }; } const msg = e instanceof Error ? e.message : "Error desconocido"; return { msg, general: [msg], validation: {} }; };
const uwUpdate = async (p: EnrollmentUpdateParamsT, update: EnrControllerT["updateEnrollment"]) => { try { return { ok: true as const, result: await update(p), errors: { general: [], validation: {} } as SubmitErrorState }; } catch (e) { const p2 = extractError(e); return { ok: false as const, result: null, errors: { general: p2.general, validation: p2.validation } as SubmitErrorState }; } };
interface UseFormArgs { update: EnrControllerT["updateEnrollment"]; }
export const useEnrollmentForm = ({ update }: UseFormArgs) => {
  const [isOpen, setIsOpen] = useState(false); const [editing, setEditing] = useState<EnrollmentT | null>(null); const [submitErrors, setSubmitErrors] = useState<SubmitErrorState>({ general: [], validation: {} }); const isEdit = !!editing;
  const openModal = useCallback((e?: EnrollmentT) => { setEditing(e ?? null); setSubmitErrors({ general: [], validation: {} }); setIsOpen(true); }, []);
  const closeModal = useCallback(() => { setIsOpen(false); setEditing(null); setSubmitErrors({ general: [], validation: {} }); }, []);
  const handleSubmit = useCallback(async (values: { section: number; enrollment_status: string; is_repeat: boolean }) => { setSubmitErrors({ general: [], validation: {} }); if (!editing) return; const r = await uwUpdate({ id: editing.id, data: { section: values.section, enrollment_status: values.enrollment_status, is_repeat: values.is_repeat } }, update); if (r.ok) { closeModal(); return; } setSubmitErrors(r.errors); }, [editing, update, closeModal]);
  return { isOpen, isEdit, editingEnrollment: editing, submitErrors, openModal, closeModal, handleSubmit };
};
