import { apiClient, getApiErrorMessage } from "@shared/services/api.client"; import type { PaginatedData, ResponseApi } from "@shared/types/api.response.types"; import { ENROLLMENT_ENDPOINTS } from "./enrollments.constants"; import type { EnrollmentCreateDataT, EnrollmentDeleteParamsT, EnrollmentGetParamsT, EnrollmentListBySectionParamsT, EnrollmentListParamsT, EnrollmentServiceT, EnrollmentT, EnrollmentUpdateParamsT } from "./enrollments.types";
class EnrollmentService implements EnrollmentServiceT {
  async list(p?: EnrollmentListParamsT): Promise<EnrollmentT[]> { try { const pg = p?.page ?? 1; const ps = p?.pageSize ?? 100; const sq = p?.search ? `&search=${encodeURIComponent(p.search)}` : ""; const oq = p?.ordering ? `&ordering=${encodeURIComponent(p.ordering)}` : ""; const filters = p?.filters ?? {}; const fq = Object.entries(filters).filter(([, v]) => v !== undefined && v !== null).map(([k, v]) => `&${k}=${encodeURIComponent(String(v))}`).join(""); const { data } = await apiClient.get<ResponseApi<PaginatedData<EnrollmentT>>>(`${ENROLLMENT_ENDPOINTS.LIST}?page=${pg}&page_size=${ps}${sq}${oq}${fq}`); return data.data.results; } catch (error) { throw new Error(getApiErrorMessage(error), { cause: error }); } }
  async listBySection(p: EnrollmentListBySectionParamsT): Promise<EnrollmentT[]> { try { const { data } = await apiClient.get<ResponseApi<PaginatedData<EnrollmentT>>>(`${ENROLLMENT_ENDPOINTS.BY_SECTION}?section_id=${p.section_id}&status=${p.status ?? "ACT"}`); return data.data.results; } catch (error) { throw new Error(getApiErrorMessage(error), { cause: error }); } }
  async get(id: EnrollmentGetParamsT): Promise<EnrollmentT> { try { const { data } = await apiClient.get<ResponseApi<EnrollmentT>>(ENROLLMENT_ENDPOINTS.DETAIL(id)); return data.data; } catch (error) { throw new Error(getApiErrorMessage(error), { cause: error }); } }
  async create(d: EnrollmentCreateDataT): Promise<EnrollmentT> { try { const { data } = await apiClient.post<ResponseApi<EnrollmentT>>(ENROLLMENT_ENDPOINTS.LIST, d); return data.data; } catch (error) { throw new Error(getApiErrorMessage(error), { cause: error }); } }
  async update(p: EnrollmentUpdateParamsT): Promise<EnrollmentT> { try { const { data } = await apiClient.patch<ResponseApi<EnrollmentT>>(ENROLLMENT_ENDPOINTS.DETAIL(p.id), p.data); return data.data; } catch (error) { throw new Error(getApiErrorMessage(error), { cause: error }); } }
  async softDelete(id: EnrollmentDeleteParamsT): Promise<{ id: number }> { try { const { data } = await apiClient.post<ResponseApi<{ id: number }>>(ENROLLMENT_ENDPOINTS.SOFT_DELETE(id)); return data.data; } catch (error) { throw new Error(getApiErrorMessage(error), { cause: error }); } }
}
export const enrollmentService = new EnrollmentService();
