import { useAppDispatch, useAppSelector } from "@shared/redux/hooks"; import { useCallback, useState } from "react"; import { qualitativeScaleService } from "./qualitative-scales.service"; import { loadPending, loadSuccess, loadError, entityCreated, entityUpdated, entityDeleted, mutationError, selectQualitativeScales, selectQualitativeScalesStatus, selectQualitativeScalesError } from "./qualitative-scales.slice"; import type { QualitativeScaleCreateDataT, QualitativeScaleCreateParamsT, QualitativeScaleDeleteParamsT, QualitativeScaleFormValues, QualitativeScaleListParamsT, QualitativeScaleT, QualitativeScaleUpdateParamsT } from "./qualitative-scales.types";
export type CreateRejectValue = { msg: string; data: Record<string, string> | null; }; export type ValidationErrors = Record<string, string>; export interface SubmitErrorState { general: string[]; validation: ValidationErrors; }
const toRejectValue = (e: unknown): CreateRejectValue => { const msg = e instanceof Error ? e.message : "Error desconocido"; const cause = e instanceof Error ? (e as { cause?: unknown }).cause : undefined; const d = (cause as { response?: { data?: { data?: unknown } } })?.response?.data; return { msg, data: (d?.data as Record<string, string> | null) ?? null }; };
export const useQualitativeScalesController = () => {
  const dispatch = useAppDispatch(); const items = useAppSelector(selectQualitativeScales); const status = useAppSelector(selectQualitativeScalesStatus); const error = useAppSelector(selectQualitativeScalesError);
  const load = useCallback(async (p?: QualitativeScaleListParamsT) => { dispatch(loadPending()); try { const items = await qualitativeScaleService.list(p ?? { page: 1, pageSize: 100 }); dispatch(loadSuccess(items)); } catch (err) { dispatch(loadError(err instanceof Error ? err.message : "Error")); } }, [dispatch]);
  const create = useCallback(async (d: QualitativeScaleCreateParamsT): Promise<QualitativeScaleT> => { try { const c = await qualitativeScaleService.create(d); dispatch(entityCreated(c)); return c; } catch (err) { const rv = toRejectValue(err); dispatch(mutationError(rv.msg)); throw rv; } }, [dispatch]);
  const update = useCallback(async (p: QualitativeScaleUpdateParamsT): Promise<QualitativeScaleT> => { try { const u = await qualitativeScaleService.update(p); dispatch(entityUpdated(u)); return u; } catch (err) { const rv = toRejectValue(err); dispatch(mutationError(rv.msg)); throw rv; } }, [dispatch]);
  const remove = useCallback(async (id: QualitativeScaleDeleteParamsT): Promise<void> => { try { const { id: did } = await qualitativeScaleService.softDelete(id); dispatch(entityDeleted(did)); } catch (err) { dispatch(mutationError(err instanceof Error ? err.message : "Error")); } }, [dispatch]);
  return { qualitativeScales: items, isLoading: status === "loading", error, loadQualitativeScales: load, createQualitativeScale: create, updateQualitativeScale: update, deleteQualitativeScale: remove };
};
export type QSTControllerT = ReturnType<typeof useQualitativeScalesController>;
const extractError = (e: unknown) => { if (e && typeof e === "object" && "msg" in e && typeof (e as { msg?: unknown }).msg === "string") { const obj = e as CreateRejectValue; const fes: ValidationErrors = {}; const gen: string[] = []; if (obj.data && typeof obj.data === "object") { for (const [k, v] of Object.entries(obj.data)) { if (typeof v === "string") fes[k] = v; else gen.push(`${k}: ${v}`); } } if (gen.length === 0 && Object.keys(fes).length === 0) gen.push(obj.msg); return { msg: obj.msg, general: gen, validation: fes }; } const msg = e instanceof Error ? e.message : "Error desconocido"; return { msg, general: [msg], validation: {} }; };
const uwCreate = async (d: QualitativeScaleCreateDataT, create: QSTControllerT["createQualitativeScale"]) => { try { return { ok: true as const, result: await create(d), errors: { general: [], validation: {} } as SubmitErrorState }; } catch (e) { const p = extractError(e); return { ok: false as const, result: null, errors: { general: p.general, validation: p.validation } as SubmitErrorState }; } };
const uwUpdate = async (p: QualitativeScaleUpdateParamsT, update: QSTControllerT["updateQualitativeScale"]) => { try { return { ok: true as const, result: await update(p), errors: { general: [], validation: {} } as SubmitErrorState }; } catch (e) { const p2 = extractError(e); return { ok: false as const, result: null, errors: { general: p2.general, validation: p2.validation } as SubmitErrorState }; } };
interface UseFormArgs { create: QSTControllerT["createQualitativeScale"]; update: QSTControllerT["updateQualitativeScale"]; }
export const useQualitativeScalesForm = ({ create, update }: UseFormArgs) => {
  const [isOpen, setIsOpen] = useState(false); const [editing, setEditing] = useState<QualitativeScaleT | null>(null); const [submitErrors, setSubmitErrors] = useState<SubmitErrorState>({ general: [], validation: {} }); const isEdit = !!editing;
  const openModal = useCallback((s?: QualitativeScaleT) => { setEditing(s ?? null); setSubmitErrors({ general: [], validation: {} }); setIsOpen(true); }, []);
  const closeModal = useCallback(() => { setIsOpen(false); setEditing(null); setSubmitErrors({ general: [], validation: {} }); }, []);
  const handleSubmit = useCallback(async (values: QualitativeScaleFormValues) => { setSubmitErrors({ general: [], validation: {} }); if (editing) { const { code, name, description, numeric_equivalence, is_active } = values; const r = await uwUpdate({ id: editing.id, data: { code, name, description, numeric_equivalence, is_active } }, update); if (r.ok) { closeModal(); return; } setSubmitErrors(r.errors); } else { const { code, name, description, numeric_equivalence } = values; const r = await uwCreate({ code, name, description, numeric_equivalence }, create); if (r.ok) { closeModal(); return; } setSubmitErrors(r.errors); } }, [editing, create, update, closeModal]);
  return { isOpen, isEdit, editingQualitativeScale: editing, submitErrors, openModal, closeModal, handleSubmit };
};
