import { apiClient, getApiErrorMessage } from "@shared/services/api.client"; import type { PaginatedData, ResponseApi } from "@shared/types/api.response.types"; import { QUALITATIVE_SCALES_ENDPOINTS } from "./qualitative-scales.constants"; import type { QualitativeScaleCreateDataT, QualitativeScaleDeleteParamsT, QualitativeScaleGetParamsT, QualitativeScaleListParamsT, QualitativeScaleServiceT, QualitativeScaleT, QualitativeScaleUpdateParamsT } from "./qualitative-scales.types";
class QualitativeScaleService implements QualitativeScaleServiceT {
  async list(p?: QualitativeScaleListParamsT): Promise<QualitativeScaleT[]> { try { const pg = p?.page ?? 1; const ps = p?.pageSize ?? 100; const sq = p?.search ? `&search=${encodeURIComponent(p.search)}` : ""; const oq = p?.ordering ? `&ordering=${encodeURIComponent(p.ordering)}` : ""; const { data } = await apiClient.get<ResponseApi<PaginatedData<QualitativeScaleT>>>(`${QUALITATIVE_SCALES_ENDPOINTS.LIST}?page=${pg}&page_size=${ps}${sq}${oq}`); return data.data.results; } catch (error) { throw new Error(getApiErrorMessage(error), { cause: error }); } }
  async get(id: QualitativeScaleGetParamsT): Promise<QualitativeScaleT> { try { const { data } = await apiClient.get<ResponseApi<QualitativeScaleT>>(QUALITATIVE_SCALES_ENDPOINTS.DETAIL(id)); return data.data; } catch (error) { throw new Error(getApiErrorMessage(error), { cause: error }); } }
  async create(d: QualitativeScaleCreateDataT): Promise<QualitativeScaleT> { try { const { data } = await apiClient.post<ResponseApi<QualitativeScaleT>>(QUALITATIVE_SCALES_ENDPOINTS.LIST, d); return data.data; } catch (error) { throw new Error(getApiErrorMessage(error), { cause: error }); } }
  async update(p: QualitativeScaleUpdateParamsT): Promise<QualitativeScaleT> { try { const { data } = await apiClient.patch<ResponseApi<QualitativeScaleT>>(QUALITATIVE_SCALES_ENDPOINTS.DETAIL(p.id), p.data); return data.data; } catch (error) { throw new Error(getApiErrorMessage(error), { cause: error }); } }
  async softDelete(id: QualitativeScaleDeleteParamsT): Promise<{ id: number }> { try { const { data } = await apiClient.post<ResponseApi<{ id: number }>>(QUALITATIVE_SCALES_ENDPOINTS.SOFT_DELETE(id)); return data.data; } catch (error) { throw new Error(getApiErrorMessage(error), { cause: error }); } }
}
export const qualitativeScaleService = new QualitativeScaleService();
