import { Plus } from "lucide-react"; import { useCallback, useState } from "react"; import { useQualitativeScalesController, useQualitativeScalesForm } from "./qualitative-scales.controller"; import { QualitativeScaleDeleteModal } from "./components/QualitativeScaleDeleteModal"; import { QualitativeScalesFormModal } from "./components/QualitativeScalesFormModal"; import { QualitativeScalesTable } from "./components/QualitativeScalesTable"; import { QualitativeScaleViewModal } from "./components/QualitativeScaleViewModal"; import type { QualitativeScaleT } from "./qualitative-scales.types";
export default function QualitativeScalesPage() {
  const { qualitativeScales, isLoading, loadQualitativeScales, createQualitativeScale, updateQualitativeScale, deleteQualitativeScale } = useQualitativeScalesController();
  const { isOpen, isEdit, editingQualitativeScale, submitErrors, openModal, closeModal, handleSubmit } = useQualitativeScalesForm({ create: createQualitativeScale, update: updateQualitativeScale });
  const [viewing, setViewing] = useState<QualitativeScaleT | null>(null); const [isViewOpen, setIsViewOpen] = useState(false);
  const [deleting, setDeleting] = useState<QualitativeScaleT | null>(null); const [isDeleteOpen, setIsDeleteOpen] = useState(false);
  const openV = useCallback((s: QualitativeScaleT) => { setViewing(s); setIsViewOpen(true); }, []); const closeV = useCallback(() => { setViewing(null); setIsViewOpen(false); }, []);
  const openD = useCallback((s: QualitativeScaleT) => { setDeleting(s); setIsDeleteOpen(true); }, []); const closeD = useCallback(() => { setDeleting(null); setIsDeleteOpen(false); }, []);
  const handleDel = useCallback(async (id: number) => { await deleteQualitativeScale(id); }, [deleteQualitativeScale]);
  return (<div className="space-y-4"><div className="flex flex-col items-start justify-between gap-4 sm:flex-row sm:items-center"><div><h1 className="text-2xl font-extrabold text-slate-800">Escalas Cualitativas</h1><p className="mt-1 text-sm text-slate-500">Gestiona las escalas de calificación cualitativa</p></div><button type="button" onClick={() => openModal()} className="inline-flex items-center gap-2 rounded-lg bg-primary px-4 py-2.5 text-sm font-bold text-white hover:bg-primary-hover"><Plus className="size-4" />Nueva Escala</button></div><QualitativeScalesTable qualitativeScales={qualitativeScales} isLoading={isLoading} loadQualitativeScales={loadQualitativeScales} onEdit={openModal} onView={openV} onDelete={openD} /><QualitativeScalesFormModal isOpen={isOpen} onClose={closeModal} isEdit={isEdit} editingQualitativeScale={editingQualitativeScale} onSubmit={handleSubmit} submitErrors={submitErrors} /><QualitativeScaleViewModal isOpen={isViewOpen} qualitativeScaleId={viewing?.id ?? null} onClose={closeV} /><QualitativeScaleDeleteModal isOpen={isDeleteOpen} qualitativeScale={deleting} onClose={closeD} onConfirm={handleDel} /></div>);
}
