import { Plus } from "lucide-react"; import { useCallback, useState } from "react"; import { useBlockComponentsController, useBlockComponentsForm } from "./block-components.controller"; import { BlockComponentDeleteModal } from "./components/BlockComponentDeleteModal"; import { BlockComponentsFormModal } from "./components/BlockComponentsFormModal"; import { BlockComponentsTable } from "./components/BlockComponentsTable"; import { BlockComponentViewModal } from "./components/BlockComponentViewModal"; import type { BlockComponentT } from "./block-components.types";
export default function BlockComponentsPage() {
  const { blockComponents, isLoading, loadBlockComponents, createBlockComponent, updateBlockComponent, deleteBlockComponent } = useBlockComponentsController();
  const { isOpen, isEdit, editingBlockComponent, submitErrors, openModal, closeModal, handleSubmit } = useBlockComponentsForm({ create: createBlockComponent, update: updateBlockComponent });
  const [viewing, setViewing] = useState<BlockComponentT | null>(null); const [isViewOpen, setIsViewOpen] = useState(false);
  const [deleting, setDeleting] = useState<BlockComponentT | null>(null); const [isDeleteOpen, setIsDeleteOpen] = useState(false);
  const openView = useCallback((bc: BlockComponentT) => { setViewing(bc); setIsViewOpen(true); }, []); const closeView = useCallback(() => { setViewing(null); setIsViewOpen(false); }, []);
  const openDel = useCallback((bc: BlockComponentT) => { setDeleting(bc); setIsDeleteOpen(true); }, []); const closeDel = useCallback(() => { setDeleting(null); setIsDeleteOpen(false); }, []);
  const handleDel = useCallback(async (id: number) => { await deleteBlockComponent(id); }, [deleteBlockComponent]);
  return (<div className="space-y-4"><div className="flex flex-col items-start justify-between gap-4 sm:flex-row sm:items-center"><div><h1 className="text-2xl font-extrabold text-slate-800">Componentes de Bloque</h1><p className="mt-1 text-sm text-slate-500">Gestiona los componentes de bloque de evaluación</p></div><button type="button" onClick={() => openModal()} className="inline-flex items-center justify-center gap-2 rounded-lg bg-primary px-4 py-2.5 text-sm font-bold text-white shadow-sm transition hover:bg-primary-hover disabled:cursor-not-allowed disabled:opacity-60"><Plus className="size-4" />Nuevo Componente</button></div><BlockComponentsTable blockComponents={blockComponents} isLoading={isLoading} loadBlockComponents={loadBlockComponents} onEdit={openModal} onView={openView} onDelete={openDel} /><BlockComponentsFormModal isOpen={isOpen} onClose={closeModal} isEdit={isEdit} editingBlockComponent={editingBlockComponent} onSubmit={handleSubmit} submitErrors={submitErrors} /><BlockComponentViewModal isOpen={isViewOpen} blockComponentId={viewing?.id ?? null} onClose={closeView} /><BlockComponentDeleteModal isOpen={isDeleteOpen} blockComponent={deleting} onClose={closeDel} onConfirm={handleDel} /></div>);
}
