import { createSlice, type PayloadAction } from "@reduxjs/toolkit"; import type { RootState } from "@shared/redux/store"; import type { RequestStatusT } from "@shared/types/request.types"; import type { BlockComponentT } from "./block-components.types";
export interface BlockComponentsStateT { blockComponents: BlockComponentT[]; status: RequestStatusT; error: string | null; }
const initialState: BlockComponentsStateT = { blockComponents: [], status: "idle", error: null };
const slice = createSlice({ name: "blockComponents", initialState, reducers: { loadPending(s) { s.status = "loading"; s.error = null; }, loadSuccess(s, a: PayloadAction<BlockComponentT[]>) { s.blockComponents = a.payload; s.status = "succeeded"; }, loadError(s, a: PayloadAction<string>) { s.status = "failed"; s.error = a.payload; }, entityCreated(s, a: PayloadAction<BlockComponentT>) { s.blockComponents.unshift(a.payload); s.status = "succeeded"; }, entityUpdated(s, a: PayloadAction<BlockComponentT>) { const idx = s.blockComponents.findIndex((p) => p.id === a.payload.id); if (idx !== -1) s.blockComponents[idx] = a.payload; s.status = "succeeded"; }, entityDeleted(s, a: PayloadAction<number>) { s.blockComponents = s.blockComponents.filter((p) => p.id !== a.payload); s.status = "succeeded"; }, mutationError(s, a: PayloadAction<string>) { s.status = "failed"; s.error = a.payload; }, clearError(s) { s.error = null; } } });
export const { loadPending, loadSuccess, loadError, entityCreated, entityUpdated, entityDeleted, mutationError, clearError } = slice.actions;
export const selectBlockComponents = (s: RootState): BlockComponentT[] => s.grading.blockComponents.blockComponents;
export const selectBlockComponentsStatus = (s: RootState): RequestStatusT => s.grading.blockComponents.status;
export const selectBlockComponentsError = (s: RootState): string | null => s.grading.blockComponents.error;
export const blockComponentsReducer = slice.reducer; export default slice.reducer;
