import { useAppDispatch, useAppSelector } from "@shared/redux/hooks"; import { useCallback, useState } from "react"; import { blockComponentService } from "./block-components.service"; import { loadPending, loadSuccess, loadError, entityCreated, entityUpdated, entityDeleted, mutationError, selectBlockComponents, selectBlockComponentsStatus, selectBlockComponentsError } from "./block-components.slice"; import type { BlockComponentCreateDataT, BlockComponentCreateParamsT, BlockComponentDeleteParamsT, BlockComponentFormValues, BlockComponentListParamsT, BlockComponentT, BlockComponentUpdateParamsT } from "./block-components.types";
export type CreateRejectValue = { msg: string; data: Record<string, string> | null; }; export type ValidationErrors = Record<string, string>; export interface SubmitErrorState { general: string[]; validation: ValidationErrors; }
const toRejectValue = (e: unknown): CreateRejectValue => { const msg = e instanceof Error ? e.message : "Error desconocido"; const cause = e instanceof Error ? (e as { cause?: unknown }).cause : undefined; const d = (cause as { response?: { data?: { data?: unknown } } })?.response?.data; return { msg, data: (d?.data as Record<string, string> | null) ?? null }; };
export const useBlockComponentsController = () => {
  const dispatch = useAppDispatch(); const blockComponents = useAppSelector(selectBlockComponents); const status = useAppSelector(selectBlockComponentsStatus); const error = useAppSelector(selectBlockComponentsError);
  const loadBlockComponents = useCallback(async (p?: BlockComponentListParamsT) => { dispatch(loadPending()); try { const items = await blockComponentService.list(p ?? { page: 1, pageSize: 100 }); dispatch(loadSuccess(items)); } catch (err) { dispatch(loadError(err instanceof Error ? err.message : "Error al cargar")); } }, [dispatch]);
  const create = useCallback(async (d: BlockComponentCreateParamsT): Promise<BlockComponentT> => { try { const c = await blockComponentService.create(d); dispatch(entityCreated(c)); return c; } catch (err) { const rv = toRejectValue(err); dispatch(mutationError(rv.msg)); throw rv; } }, [dispatch]);
  const update = useCallback(async (p: BlockComponentUpdateParamsT): Promise<BlockComponentT> => { try { const u = await blockComponentService.update(p); dispatch(entityUpdated(u)); return u; } catch (err) { const rv = toRejectValue(err); dispatch(mutationError(rv.msg)); throw rv; } }, [dispatch]);
  const remove = useCallback(async (id: BlockComponentDeleteParamsT): Promise<void> => { try { const { id: deletedId } = await blockComponentService.softDelete(id); dispatch(entityDeleted(deletedId)); } catch (err) { dispatch(mutationError(err instanceof Error ? err.message : "Error al eliminar")); } }, [dispatch]);
  return { blockComponents, isLoading: status === "loading", error, loadBlockComponents, createBlockComponent: create, updateBlockComponent: update, deleteBlockComponent: remove };
};
export type BlockComponentsControllerT = ReturnType<typeof useBlockComponentsController>;
const extractError = (e: unknown) => { if (e && typeof e === "object" && "msg" in e && typeof (e as { msg?: unknown }).msg === "string") { const obj = e as CreateRejectValue; const fieldErrors: ValidationErrors = {}; const general: string[] = []; if (obj.data && typeof obj.data === "object") { for (const [key, value] of Object.entries(obj.data)) { if (typeof value === "string") fieldErrors[key] = value; else general.push(`${key}: ${value}`); } } if (general.length === 0 && Object.keys(fieldErrors).length === 0) general.push(obj.msg); return { msg: obj.msg, general, validation: fieldErrors }; } const msg = e instanceof Error ? e.message : "Error desconocido"; return { msg, general: [msg], validation: {} }; };
const unwrapCreate = async (d: BlockComponentCreateDataT, create: BlockComponentsControllerT["createBlockComponent"]) => { try { return { ok: true as const, result: await create(d), errors: { general: [], validation: {} } as SubmitErrorState }; } catch (e) { const p = extractError(e); return { ok: false as const, result: null, errors: { general: p.general, validation: p.validation } as SubmitErrorState }; } };
const unwrapUpdate = async (p: BlockComponentUpdateParamsT, update: BlockComponentsControllerT["updateBlockComponent"]) => { try { return { ok: true as const, result: await update(p), errors: { general: [], validation: {} } as SubmitErrorState }; } catch (e) { const parsed = extractError(e); return { ok: false as const, result: null, errors: { general: parsed.general, validation: parsed.validation } as SubmitErrorState }; } };
interface UseFormArgs { create: BlockComponentsControllerT["createBlockComponent"]; update: BlockComponentsControllerT["updateBlockComponent"]; }
export const useBlockComponentsForm = ({ create, update }: UseFormArgs) => {
  const [isOpen, setIsOpen] = useState(false); const [editingBlockComponent, setEditingBlockComponent] = useState<BlockComponentT | null>(null); const [submitErrors, setSubmitErrors] = useState<SubmitErrorState>({ general: [], validation: {} }); const isEdit = !!editingBlockComponent;
  const openModal = useCallback((bc?: BlockComponentT) => { setEditingBlockComponent(bc ?? null); setSubmitErrors({ general: [], validation: {} }); setIsOpen(true); }, []);
  const closeModal = useCallback(() => { setIsOpen(false); setEditingBlockComponent(null); setSubmitErrors({ general: [], validation: {} }); }, []);
  const handleSubmit = useCallback(async (values: BlockComponentFormValues) => { setSubmitErrors({ general: [], validation: {} }); if (editingBlockComponent) { const { code, name, internal_weight, evaluation_block, is_active } = values; const result = await unwrapUpdate({ id: editingBlockComponent.id, data: { code, name, internal_weight, evaluation_block, is_active } }, update); if (result.ok) { closeModal(); return; } setSubmitErrors(result.errors); } else { const { code, name, internal_weight, evaluation_block } = values; const result = await unwrapCreate({ code, name, internal_weight, evaluation_block }, create); if (result.ok) { closeModal(); return; } setSubmitErrors(result.errors); } }, [editingBlockComponent, create, update, closeModal]);
  return { isOpen, isEdit, editingBlockComponent, submitErrors, openModal, closeModal, handleSubmit };
};
