import { apiClient, getApiErrorMessage } from "@shared/services/api.client"; import type { PaginatedData, ResponseApi } from "@shared/types/api.response.types"; import { STUDENT_ENDPOINTS } from "./student.constants"; import type { AssignRepresentativeParamsT, StudentCreateDataT, StudentDeleteParamsT, StudentGetParamsT, StudentListParamsT, StudentServiceT, StudentT, StudentUpdateParamsT } from "./student.types";
class StudentService implements StudentServiceT {
  async list(p?: StudentListParamsT): Promise<StudentT[]> { try { const qs = new URLSearchParams(); if (p?.page) qs.set("page", String(p.page)); if (p?.pageSize) qs.set("page_size", String(p.pageSize)); if (p?.search) qs.set("search", p.search); if (p?.ordering) qs.set("ordering", p.ordering); if (p?.names) qs.set("names", p.names); if (p?.last_names) qs.set("last_names", p.last_names); if (p?.document_number) qs.set("document_number", p.document_number); if (p?.student_code) qs.set("student_code", p.student_code); if (p?.is_active !== undefined) qs.set("is_active", String(p.is_active)); const { data } = await apiClient.get<ResponseApi<PaginatedData<StudentT>>>(`${STUDENT_ENDPOINTS.LIST}?${qs.toString()}`); return data.data.results; } catch (error) { throw new Error(getApiErrorMessage(error), { cause: error }); } }
  async get(id: StudentGetParamsT): Promise<StudentT> { try { const { data } = await apiClient.get<ResponseApi<StudentT>>(STUDENT_ENDPOINTS.DETAIL(id)); return data.data; } catch (error) { throw new Error(getApiErrorMessage(error), { cause: error }); } }
  async create(d: StudentCreateDataT): Promise<StudentT> { try { const { data } = await apiClient.post<ResponseApi<StudentT>>(STUDENT_ENDPOINTS.LIST, d); return data.data; } catch (error) { throw new Error(getApiErrorMessage(error), { cause: error }); } }
  async update(p: StudentUpdateParamsT): Promise<StudentT> { try { const { data } = await apiClient.patch<ResponseApi<StudentT>>(STUDENT_ENDPOINTS.DETAIL(p.id), p.data); return data.data; } catch (error) { throw new Error(getApiErrorMessage(error), { cause: error }); } }
  async softDelete(id: StudentDeleteParamsT): Promise<{ id: number }> { try { const { data } = await apiClient.post<ResponseApi<{ id: number }>>(STUDENT_ENDPOINTS.SOFT_DELETE(id)); return data.data; } catch (error) { throw new Error(getApiErrorMessage(error), { cause: error }); } }
  async assignRepresentative(studentId: number, d: AssignRepresentativeParamsT): Promise<unknown> { try { const { data } = await apiClient.post(STUDENT_ENDPOINTS.ASSIGN_REPRESENTATIVE(studentId), d); return data.data; } catch (error) { throw new Error(getApiErrorMessage(error), { cause: error }); } }
}
export const studentService = new StudentService();
