import { useAppDispatch, useAppSelector } from "@shared/redux/hooks"; import { useCallback, useState } from "react"; import { studentService } from "./student.service"; import { loadPending, loadSuccess, loadError, entityCreated, entityUpdated, entityDeleted, mutationError, selectStudents, selectStudentsStatus, selectStudentsError } from "./student.slice"; import type { StudentCreateParamsT, StudentDeleteParamsT, StudentFormValues, StudentListParamsT, StudentT, StudentUpdateParamsT } from "./student.types";
export type CreateRejectValue = { msg: string; data: Record<string, string> | null; }; export type ValidationErrors = Record<string, string>; export interface SubmitErrorState { general: string[]; validation: ValidationErrors; }
const toRejectValue = (e: unknown): CreateRejectValue => { const msg = e instanceof Error ? e.message : "Error desconocido"; const cause = e instanceof Error ? (e as { cause?: unknown }).cause : undefined; const d = (cause as { response?: { data?: { data?: unknown } } })?.response?.data; return { msg, data: (d?.data as Record<string, string> | null) ?? null }; };
export const useStudentController = () => {
  const dispatch = useAppDispatch(); const items = useAppSelector(selectStudents); const status = useAppSelector(selectStudentsStatus); const error = useAppSelector(selectStudentsError);
  const load = useCallback(async (p?: StudentListParamsT) => { dispatch(loadPending()); try { const items = await studentService.list(p ?? { page: 1, pageSize: 100 }); dispatch(loadSuccess(items)); } catch (err) { dispatch(loadError(err instanceof Error ? err.message : "Error")); } }, [dispatch]);
  const create = useCallback(async (d: StudentCreateParamsT): Promise<StudentT> => { try { const c = await studentService.create(d); dispatch(entityCreated(c)); return c; } catch (err) { const rv = toRejectValue(err); dispatch(mutationError(rv.msg)); throw rv; } }, [dispatch]);
  const update = useCallback(async (p: StudentUpdateParamsT): Promise<StudentT> => { try { const u = await studentService.update(p); dispatch(entityUpdated(u)); return u; } catch (err) { const rv = toRejectValue(err); dispatch(mutationError(rv.msg)); throw rv; } }, [dispatch]);
  const remove = useCallback(async (id: StudentDeleteParamsT): Promise<void> => { try { const { id: did } = await studentService.softDelete(id); dispatch(entityDeleted(did)); } catch (err) { dispatch(mutationError(err instanceof Error ? err.message : "Error")); } }, [dispatch]);
  return { students: items, isLoading: status === "loading", error, loadStudents: load, createStudent: create, updateStudent: update, deleteStudent: remove };
};
export type StdControllerT = ReturnType<typeof useStudentController>;
const extractError = (e: unknown) => { if (e && typeof e === "object" && "msg" in e && typeof (e as { msg?: unknown }).msg === "string") { const obj = e as CreateRejectValue; const fes: ValidationErrors = {}; const gen: string[] = []; if (obj.data && typeof obj.data === "object") { for (const [k, v] of Object.entries(obj.data)) { if (typeof v === "string") fes[k] = v; else gen.push(`${k}: ${v}`); } } if (gen.length === 0 && Object.keys(fes).length === 0) gen.push(obj.msg); return { msg: obj.msg, general: gen, validation: fes }; } const msg = e instanceof Error ? e.message : "Error desconocido"; return { msg, general: [msg], validation: {} }; };
const uwUpdate = async (p: StudentUpdateParamsT, update: StdControllerT["updateStudent"]) => { try { return { ok: true as const, result: await update(p), errors: { general: [], validation: {} } as SubmitErrorState }; } catch (e) { const p2 = extractError(e); return { ok: false as const, result: null, errors: { general: p2.general, validation: p2.validation } as SubmitErrorState }; } };
interface UseFormArgs { update: StdControllerT["updateStudent"]; }
export const useStudentForm = ({ update }: UseFormArgs) => {
  const [isOpen, setIsOpen] = useState(false); const [editing, setEditing] = useState<StudentT | null>(null); const [submitErrors, setSubmitErrors] = useState<SubmitErrorState>({ general: [], validation: {} }); const isEdit = !!editing;
  const openModal = useCallback((s?: StudentT) => { setEditing(s ?? null); setSubmitErrors({ general: [], validation: {} }); setIsOpen(true); }, []);
  const closeModal = useCallback(() => { setIsOpen(false); setEditing(null); setSubmitErrors({ general: [], validation: {} }); }, []);
  const handleSubmit = useCallback(async (values: StudentFormValues) => { setSubmitErrors({ general: [], validation: {} }); if (editing) { const r = await uwUpdate({ id: editing.id, data: values }, update); if (r.ok) { closeModal(); return; } setSubmitErrors(r.errors); } }, [editing, update, closeModal]);
  return { isOpen, isEdit, editingStudent: editing, submitErrors, openModal, closeModal, handleSubmit };
};
