import { Plus } from "lucide-react"; import { useCallback, useState } from "react"; import { useStudentController, useStudentForm } from "./student.controller"; import { StudentDeleteModal } from "./components/StudentDeleteModal"; import { StudentFormModal } from "./components/StudentFormModal"; import { StudentTable } from "./components/StudentTable"; import { StudentViewModal } from "./components/StudentViewModal"; import type { StudentT } from "./student.types";
export default function StudentsPage() {
  const { students, isLoading, loadStudents, updateStudent, deleteStudent } = useStudentController();
  const { isOpen, isEdit, editingStudent, submitErrors, openModal, closeModal, handleSubmit } = useStudentForm({ update: updateStudent });
  const [viewing, setViewing] = useState<StudentT | null>(null); const [isViewOpen, setIsViewOpen] = useState(false);
  const [deleting, setDeleting] = useState<StudentT | null>(null); const [isDeleteOpen, setIsDeleteOpen] = useState(false);
  const openV = useCallback((s: StudentT) => { setViewing(s); setIsViewOpen(true); }, []); const closeV = useCallback(() => { setViewing(null); setIsViewOpen(false); }, []);
  const openD = useCallback((s: StudentT) => { setDeleting(s); setIsDeleteOpen(true); }, []); const closeD = useCallback(() => { setDeleting(null); setIsDeleteOpen(false); }, []);
  const handleDel = useCallback(async (id: number) => { await deleteStudent(id); }, [deleteStudent]);
  return (<div className="space-y-4"><div className="flex flex-col items-start justify-between gap-4 sm:flex-row sm:items-center"><div><h1 className="text-2xl font-extrabold text-slate-800">Estudiantes</h1><p className="mt-1 text-sm text-slate-500">Gestiona los estudiantes</p></div><button type="button" onClick={() => openModal()} className="inline-flex items-center gap-2 rounded-lg bg-primary px-4 py-2.5 text-sm font-bold text-white hover:bg-primary-hover"><Plus className="size-4" />Nuevo Estudiante</button></div><StudentTable students={students} isLoading={isLoading} loadStudents={loadStudents} onEdit={openModal} onView={openV} onDelete={openD} /><StudentFormModal isOpen={isOpen} onClose={closeModal} isEdit={isEdit} editingStudent={editingStudent} onSubmit={handleSubmit} submitErrors={submitErrors} /><StudentViewModal isOpen={isViewOpen} studentId={viewing?.id ?? null} onClose={closeV} /><StudentDeleteModal isOpen={isDeleteOpen} student={deleting} onClose={closeD} onConfirm={handleDel} /></div>);
}
