export const GRADING_ROUTES = {
  DASHBOARD: "/dashboard",
  SCHOOL_YEARS: "/school-years",
  ACADEMIC_GRADES: "/academic-grades",
  ACADEMIC_LEVELS: "/academic-levels",
  SECTIONS: "/sections",

  SUBJECTS: "/subjects",
  ACADEMIC_PERIODS: "/academic-periods",
  SUBJECT_ACADEMIC_CONFIGS: "/subject-academic-configs",
  TEACHER_SUBJECT_SECTIONS: "/teacher-subject-sections",
  SUBJECT_OFFERINGS: "/subject-offerings",
  PERIOD_TYPES: "/period-types",

  QUALITATIVE_SCALES: "/qualitative-scales",
  ACTIVITY_TYPES: "/activity-types",
  EVALUATION_BLOCKS: "/evaluation-blocks",
  BLOCK_COMPONENTS: "/block-components",
  STUDENT_NOTES: "/student-notes",
  GRADE_HISTORY: "/grade-history",
  PERIOD_GRADE_SUMMARIES: "/period-grade-summaries",
  EVALUATIVE_ACTIVITIES: "/evaluative-activities",
  GRADEBOOK: "/gradebook",
  QUALITATIVE_SCALE_SUBLEVELS: "/qualitative-scale-sublevels",
  ACADEMIC_SUBLEVELS: "/academic-subnivels",
};
