export * from "./grade-types";
export { gradeTypesReducer, GradeTypesPage } from "./grade-types";
export * from "./qualitative-scales";
export { qualitativeScalesReducer, QualitativeScalesPage } from "./qualitative-scales";
export * from "./evaluation-blocks";
export { evaluationBlocksReducer, EvaluationBlocksPage } from "./evaluation-blocks";
export * from "./block-components";
export { blockComponentsReducer, BlockComponentsPage } from "./block-components";
export * from "./component-indicators";
export { componentIndicatorsReducer, ComponentIndicatorsPage } from "./component-indicators";
export * from "./recovery-processes";
export { recoveryProcessesReducer, RecoveryProcessesPage } from "./recovery-processes";
export * from "./period-grade-summaries";
export { periodGradeSummariesReducer, PeriodGradeSummariesPage } from "./period-grade-summaries";
export * from "./grade-history";
export { gradeHistoryReducer, GradeHistoryPage } from "./grade-history";
export * from "./evaluation-types";
export { evaluationTypesReducer, EvaluationTypesPage } from "./evaluation-types";
export * from "./student-notes";
export { studentNotesReducer, StudentNotesPage } from "./student-notes";
export * from "./activity-types";
export { activityTypesReducer, ActivityTypesPage } from "./activity-types";
export * from "./promotion-statuses";
export { promotionStatusesReducer, PromotionStatusesPage } from "./promotion-statuses";
export * from "./recovery-process-types";
export { recoveryProcessTypesReducer, RecoveryProcessTypesPage } from "./recovery-process-types";
export * from "./project-notes";
export { projectNotesReducer, ProjectNotesPage } from "./project-notes";
