import { createSlice, type PayloadAction } from "@reduxjs/toolkit"; import type { RootState } from "@shared/redux/store"; import type { RequestStatusT } from "@shared/types/request.types"; import type { QualitativeScaleSublevelT } from "./qualitative-scale-sublevels.types";
export interface QSSStateT { qualitativeScaleSublevels: QualitativeScaleSublevelT[]; status: RequestStatusT; error: string | null; }
const initialState: QSSStateT = { qualitativeScaleSublevels: [], status: "idle", error: null };
const slice = createSlice({ name: "qualitativeScaleSublevels", initialState, reducers: { loadPending(s) { s.status = "loading"; s.error = null; }, loadSuccess(s, a: PayloadAction<QualitativeScaleSublevelT[]>) { s.qualitativeScaleSublevels = a.payload; s.status = "succeeded"; }, loadError(s, a: PayloadAction<string>) { s.status = "failed"; s.error = a.payload; }, entityCreated(s, a: PayloadAction<QualitativeScaleSublevelT>) { s.qualitativeScaleSublevels.unshift(a.payload); s.status = "succeeded"; }, entityUpdated(s, a: PayloadAction<QualitativeScaleSublevelT>) { const idx = s.qualitativeScaleSublevels.findIndex((p) => p.id === a.payload.id); if (idx !== -1) s.qualitativeScaleSublevels[idx] = a.payload; s.status = "succeeded"; }, entityDeleted(s, a: PayloadAction<QualitativeScaleSublevelT>) { const idx = s.qualitativeScaleSublevels.findIndex((p) => p.id === a.payload.id); if (idx !== -1) s.qualitativeScaleSublevels[idx] = a.payload; s.status = "succeeded"; }, mutationError(s, a: PayloadAction<string>) { s.status = "failed"; s.error = a.payload; }, clearError(s) { s.error = null; } } });
export const { loadPending, loadSuccess, loadError, entityCreated, entityUpdated, entityDeleted, mutationError, clearError } = slice.actions;
export const selectQSS = (s: RootState): QualitativeScaleSublevelT[] => s.grading.qualitativeScaleSublevels.qualitativeScaleSublevels;
export const selectQSSStatus = (s: RootState): RequestStatusT => s.grading.qualitativeScaleSublevels.status;
export const selectQSSError = (s: RootState): string | null => s.grading.qualitativeScaleSublevels.error;
export const qualitativeScaleSublevelReducer = slice.reducer; export default slice.reducer;
