import { useAppDispatch, useAppSelector } from "@shared/redux/hooks"; import { useCallback, useState } from "react"; import { qualitativeScaleSublevelService } from "./qualitative-scale-sublevels.service"; import { loadPending, loadSuccess, loadError, entityCreated, entityUpdated, entityDeleted, mutationError, selectQSS, selectQSSStatus, selectQSSError } from "./qualitative-scale-sublevels.slice"; import type { QualitativeScaleSublevelCreateDataT, QualitativeScaleSublevelCreateParamsT, QualitativeScaleSublevelDeleteParamsT, QualitativeScaleSublevelFormValues, QualitativeScaleSublevelListParamsT, QualitativeScaleSublevelT, QualitativeScaleSublevelUpdateParamsT } from "./qualitative-scale-sublevels.types";
export type CreateRejectValue = { msg: string; data: Record<string, string> | null; }; export type ValidationErrors = Record<string, string>; export interface SubmitErrorState { general: string[]; validation: ValidationErrors; }
const toRejectValue = (e: unknown): CreateRejectValue => { const msg = e instanceof Error ? e.message : "Error desconocido"; const cause = e instanceof Error ? (e as { cause?: unknown }).cause : undefined; const d = (cause as { response?: { data?: { data?: unknown } } })?.response?.data; return { msg, data: (d?.data as Record<string, string> | null) ?? null }; };
export const useQSSController = () => {
  const dispatch = useAppDispatch(); const items = useAppSelector(selectQSS); const status = useAppSelector(selectQSSStatus); const error = useAppSelector(selectQSSError);
  const load = useCallback(async (p?: QualitativeScaleSublevelListParamsT) => { dispatch(loadPending()); try { const items = await qualitativeScaleSublevelService.list(p ?? { page: 1, pageSize: 100 }); dispatch(loadSuccess(items)); } catch (err) { dispatch(loadError(err instanceof Error ? err.message : "Error")); } }, [dispatch]);
  const create = useCallback(async (d: QualitativeScaleSublevelCreateParamsT): Promise<QualitativeScaleSublevelT> => { try { const c = await qualitativeScaleSublevelService.create(d); dispatch(entityCreated(c)); return c; } catch (err) { const rv = toRejectValue(err); dispatch(mutationError(rv.msg)); throw rv; } }, [dispatch]);
  const update = useCallback(async (p: QualitativeScaleSublevelUpdateParamsT): Promise<QualitativeScaleSublevelT> => { try { const u = await qualitativeScaleSublevelService.update(p); dispatch(entityUpdated(u)); return u; } catch (err) { const rv = toRejectValue(err); dispatch(mutationError(rv.msg)); throw rv; } }, [dispatch]);
  const remove = useCallback(async (id: QualitativeScaleSublevelDeleteParamsT): Promise<void> => { try { const r = await qualitativeScaleSublevelService.softDelete(id); dispatch(entityDeleted(r)); } catch (err) { dispatch(mutationError(err instanceof Error ? err.message : "Error")); } }, [dispatch]);
  return { qualitativeScaleSublevels: items, isLoading: status === "loading", error, loadQualitativeScaleSublevels: load, createQualitativeScaleSublevel: create, updateQualitativeScaleSublevel: update, deleteQualitativeScaleSublevel: remove };
};
export type QSSControllerT = ReturnType<typeof useQSSController>;
const extractError = (e: unknown) => { if (e && typeof e === "object" && "msg" in e && typeof (e as { msg?: unknown }).msg === "string") { const obj = e as CreateRejectValue; const fes: ValidationErrors = {}; const gen: string[] = []; if (obj.data && typeof obj.data === "object") { for (const [k, v] of Object.entries(obj.data)) { if (typeof v === "string") fes[k] = v; else gen.push(`${k}: ${v}`); } } if (gen.length === 0 && Object.keys(fes).length === 0) gen.push(obj.msg); return { msg: obj.msg, general: gen, validation: fes }; } const msg = e instanceof Error ? e.message : "Error desconocido"; return { msg, general: [msg], validation: {} }; };
const uwCreate = async (d: QualitativeScaleSublevelCreateDataT, create: QSSControllerT["createQualitativeScaleSublevel"]) => { try { return { ok: true as const, result: await create(d), errors: { general: [], validation: {} } as SubmitErrorState }; } catch (e) { const p = extractError(e); return { ok: false as const, result: null, errors: { general: p.general, validation: p.validation } as SubmitErrorState }; } };
const uwUpdate = async (p: QualitativeScaleSublevelUpdateParamsT, update: QSSControllerT["updateQualitativeScaleSublevel"]) => { try { return { ok: true as const, result: await update(p), errors: { general: [], validation: {} } as SubmitErrorState }; } catch (e) { const p2 = extractError(e); return { ok: false as const, result: null, errors: { general: p2.general, validation: p2.validation } as SubmitErrorState }; } };
interface UseFormArgs { create: QSSControllerT["createQualitativeScaleSublevel"]; update: QSSControllerT["updateQualitativeScaleSublevel"]; }
export const useQSSForm = ({ create, update }: UseFormArgs) => {
  const [isOpen, setIsOpen] = useState(false); const [editing, setEditing] = useState<QualitativeScaleSublevelT | null>(null); const [submitErrors, setSubmitErrors] = useState<SubmitErrorState>({ general: [], validation: {} }); const isEdit = !!editing;
  const openModal = useCallback((item?: QualitativeScaleSublevelT) => { setEditing(item ?? null); setSubmitErrors({ general: [], validation: {} }); setIsOpen(true); }, []);
  const closeModal = useCallback(() => { setIsOpen(false); setEditing(null); setSubmitErrors({ general: [], validation: {} }); }, []);
  const handleSubmit = useCallback(async (values: QualitativeScaleSublevelFormValues) => { setSubmitErrors({ general: [], validation: {} }); if (editing) { const r = await uwUpdate({ id: editing.id, data: values }, update); if (r.ok) { closeModal(); return; } setSubmitErrors(r.errors); } else { const { scale, sublevel } = values; const r = await uwCreate({ scale, sublevel }, create); if (r.ok) { closeModal(); return; } setSubmitErrors(r.errors); } }, [editing, create, update, closeModal]);
  return { isOpen, isEdit, editingQualitativeScaleSublevel: editing, submitErrors, openModal, closeModal, handleSubmit };
};
