import { apiClient, getApiErrorMessage } from "@shared/services/api.client"; import type { PaginatedData, ResponseApi } from "@shared/types/api.response.types"; import { QUALITATIVE_SCALE_SUBLEVEL_ENDPOINTS } from "./qualitative-scale-sublevels.constants"; import type { QualitativeScaleSublevelCreateDataT, QualitativeScaleSublevelDeleteParamsT, QualitativeScaleSublevelGetParamsT, QualitativeScaleSublevelListParamsT, QualitativeScaleSublevelServiceT, QualitativeScaleSublevelT, QualitativeScaleSublevelUpdateParamsT } from "./qualitative-scale-sublevels.types";
class QualitativeScaleSublevelService implements QualitativeScaleSublevelServiceT {
  async list(p?: QualitativeScaleSublevelListParamsT): Promise<QualitativeScaleSublevelT[]> { try { const page = p?.page ?? 1; const ps = p?.pageSize ?? 100; const sq = p?.search ? `&search=${encodeURIComponent(p.search)}` : ""; const oq = p?.ordering ? `&ordering=${encodeURIComponent(p.ordering)}` : ""; const { data } = await apiClient.get<ResponseApi<PaginatedData<QualitativeScaleSublevelT>>>(`${QUALITATIVE_SCALE_SUBLEVEL_ENDPOINTS.LIST}?page=${page}&page_size=${ps}${sq}${oq}`); return data.data.results; } catch (error) { throw new Error(getApiErrorMessage(error), { cause: error }); } }
  async get(id: QualitativeScaleSublevelGetParamsT): Promise<QualitativeScaleSublevelT> { try { const { data } = await apiClient.get<ResponseApi<QualitativeScaleSublevelT>>(QUALITATIVE_SCALE_SUBLEVEL_ENDPOINTS.DETAIL(id)); return data.data; } catch (error) { throw new Error(getApiErrorMessage(error), { cause: error }); } }
  async create(d: QualitativeScaleSublevelCreateDataT): Promise<QualitativeScaleSublevelT> { try { const { data } = await apiClient.post<ResponseApi<QualitativeScaleSublevelT>>(QUALITATIVE_SCALE_SUBLEVEL_ENDPOINTS.LIST, d); return data.data; } catch (error) { throw new Error(getApiErrorMessage(error), { cause: error }); } }
  async update(p: QualitativeScaleSublevelUpdateParamsT): Promise<QualitativeScaleSublevelT> { try { const { data } = await apiClient.patch<ResponseApi<QualitativeScaleSublevelT>>(QUALITATIVE_SCALE_SUBLEVEL_ENDPOINTS.DETAIL(p.id), p.data); return data.data; } catch (error) { throw new Error(getApiErrorMessage(error), { cause: error }); } }
  async softDelete(id: QualitativeScaleSublevelDeleteParamsT): Promise<QualitativeScaleSublevelT> { try { const { data } = await apiClient.delete<ResponseApi<QualitativeScaleSublevelT>>(QUALITATIVE_SCALE_SUBLEVEL_ENDPOINTS.DETAIL(id)); return data.data; } catch (error) { throw new Error(getApiErrorMessage(error), { cause: error }); } }
}
export const qualitativeScaleSublevelService = new QualitativeScaleSublevelService();
