import { Plus } from "lucide-react"; import { useCallback, useEffect, useRef, useState } from "react"; import { Pencil } from "lucide-react";
import { tableClassname, tableColumnsClassname, tableFirstColumnClassname } from "@app/styles/styles"; import { Badge } from "@shared/components/Badge"; import { SearchInput } from "@shared/components/Form"; import { Pagination } from "@shared/components/Pagination"; import { CustomTable } from "@shared/components/Table";
import { useFormik } from "formik"; import { useEffect as useEffect2 } from "react"; import { checkboxClassname, selectClassname } from "@app/styles/styles"; import { CustomCheckbox, CustomSelect } from "@shared/components/Form";
import { useQSSController, useQSSForm } from "./qualitative-scale-sublevels.controller"; import { useQualitativeScaleSublevelOptions } from "./qualitative-scale-sublevels.options"; import { qssSchema } from "./qualitative-scale-sublevels.utils";
import type { TableColumnProps } from "@shared/components/Table"; import type { SubmitErrorState } from "./qualitative-scale-sublevels.controller"; import type { QualitativeScaleSublevelFormValues, QualitativeScaleSublevelOrderingT, QualitativeScaleSublevelT } from "./qualitative-scale-sublevels.types";

const O: { label: string; value: QualitativeScaleSublevelOrderingT }[] = [{ label: "Escala (A-Z)", value: "scale_name" }, { label: "Escala (Z-A)", value: "-scale_name" }, { label: "Subnivel (A-Z)", value: "sublevel_name" }, { label: "Subnivel (Z-A)", value: "-sublevel_name" }];

const getFieldLabel = (f: string): string => ({ scale: "Escala", sublevel: "Subnivel", non_field_errors: "Error general" }[f] || f);

function FormModal({ isOpen, onClose, isEdit, editingQualitativeScaleSublevel, onSubmit, submitErrors, scaleOptions, sublevelOptions }: {
  isOpen: boolean; onClose: () => void; isEdit: boolean; editingQualitativeScaleSublevel: QualitativeScaleSublevelT | null;
  onSubmit: (v: QualitativeScaleSublevelFormValues) => Promise<void>; submitErrors: SubmitErrorState;
  scaleOptions: { label: string; value: string }[]; sublevelOptions: { label: string; value: string }[];
}) {
  const formik = useFormik<QualitativeScaleSublevelFormValues>({
    initialValues: editingQualitativeScaleSublevel ? { scale: editingQualitativeScaleSublevel.scale, sublevel: editingQualitativeScaleSublevel.sublevel, is_active: editingQualitativeScaleSublevel.is_active } : { scale: 0, sublevel: 0, is_active: true },
    validationSchema: qssSchema, enableReinitialize: true, onSubmit,
  });
  useEffect2(() => { if (isOpen && editingQualitativeScaleSublevel) formik.setValues({ scale: editingQualitativeScaleSublevel.scale, sublevel: editingQualitativeScaleSublevel.sublevel, is_active: editingQualitativeScaleSublevel.is_active }); }, [isOpen, editingQualitativeScaleSublevel]);
  if (!isOpen) return null;
  return (<div className="fixed inset-0 z-50 flex items-center justify-center"><div className="absolute inset-0 bg-black/40" onClick={onClose} /><div className="relative w-full max-w-md animate-slide-up overflow-hidden rounded-xl bg-white shadow-xl"><div className="flex items-center justify-between border-b border-slate-200 px-5 py-4"><div><h3 className="text-lg font-semibold text-slate-900">{isEdit ? "Editar" : "Nueva"} Asignación</h3><p className="mt-0.5 text-sm text-slate-500">Asocie una escala cualitativa a un subnivel</p></div><button type="button" onClick={onClose} className="rounded-lg p-1.5 text-slate-400 hover:bg-slate-100"><svg className="size-5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" /></svg></button></div>
    {(submitErrors.general.length > 0 || Object.keys(submitErrors.validation).length > 0) && (<div className="mx-5 mt-3 rounded-lg border border-red-300 bg-red-50 p-4 shadow-sm"><div className="flex items-start gap-2"><svg className="mt-0.5 size-5 flex-shrink-0 text-red-600" fill="currentColor" viewBox="0 0 20 20"><path fillRule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zM8.707 7.293a1 1 0 00-1.414 1.414L8.586 10l-1.293 1.293a1 1 0 101.414 1.414L10 11.414l1.293 1.293a1 1 0 001.414-1.414L11.414 10l1.293-1.293a1 1 0 00-1.414-1.414L10 8.586 8.707 7.293z" clipRule="evenodd" /></svg><div className="flex-1"><p className="mb-2 text-sm font-semibold text-red-800">Error al guardar</p>{submitErrors.general.length > 0 && (<ul>{submitErrors.general.map((e, i) => (<li key={i} className="text-sm text-red-700">• {e}</li>))}</ul>)}{Object.keys(submitErrors.validation).length > 0 && (<ul>{Object.entries(submitErrors.validation).map(([f, m]) => (<li key={f} className="text-sm text-red-700"><span className="font-semibold">{getFieldLabel(f)}:</span> {m}</li>))}</ul>)}</div></div></div>)}
    <form onSubmit={formik.handleSubmit} className="space-y-4 p-5"><CustomSelect label="Escala Cualitativa" name="scale" value={String(formik.values.scale)} onChange={(o) => formik.setFieldValue("scale", Number(o.value))} options={scaleOptions} className={selectClassname} error={formik.touched.scale ? formik.errors.scale : undefined} /><CustomSelect label="Subnivel Académico" name="sublevel" value={String(formik.values.sublevel)} onChange={(o) => formik.setFieldValue("sublevel", Number(o.value))} options={sublevelOptions} className={selectClassname} error={formik.touched.sublevel ? formik.errors.sublevel : undefined} />{isEdit && <CustomCheckbox name="is_active" checked={formik.values.is_active} onChange={formik.handleChange} onBlur={formik.handleBlur} label="Activo" className={checkboxClassname} />}<div className="flex items-center justify-end gap-3 border-t border-slate-200 pt-4"><button type="button" onClick={onClose} className="rounded-lg border border-slate-300 bg-white px-4 py-2 text-sm font-medium text-slate-700 hover:bg-slate-50">Cancelar</button><button type="submit" disabled={formik.isSubmitting} className="rounded-lg bg-primary px-4 py-2 text-sm font-medium text-white hover:bg-primary-hover disabled:opacity-60">{formik.isSubmitting ? "Guardando..." : isEdit ? "Actualizar" : "Crear"}</button></div></form></div></div>);
}

export default function QualitativeScaleSublevelsPage() {
  const { qualitativeScaleSublevels, isLoading, loadQualitativeScaleSublevels, createQualitativeScaleSublevel, updateQualitativeScaleSublevel } = useQSSController();
  const { isOpen, isEdit, editingQualitativeScaleSublevel, submitErrors, openModal, closeModal, handleSubmit } = useQSSForm({ create: createQualitativeScaleSublevel, update: updateQualitativeScaleSublevel });
  const { scaleOptions, sublevelOptions } = useQualitativeScaleSublevelOptions();
  const [search, setSearch] = useState(""); const [page, setPage] = useState(1); const [pageSize, setPageSize] = useState(10); const [ordering, setOrdering] = useState<QualitativeScaleSublevelOrderingT>("scale_name"); const [hasSearched, setHasSearched] = useState(false);
  const dr = useRef<ReturnType<typeof setTimeout>>(undefined);
  const fetchData = useCallback((o?: { page?: number; pageSize?: number; search?: string; ordering?: QualitativeScaleSublevelOrderingT }) => { loadQualitativeScaleSublevels({ page: o?.page ?? page, pageSize: o?.pageSize ?? pageSize, search: o?.search !== undefined ? o.search : search || undefined, ordering: o?.ordering ?? ordering }); }, [loadQualitativeScaleSublevels, page, pageSize, search, ordering]);
  useEffect(() => { fetchData(); }, []); // eslint-disable-line react-hooks/exhaustive-deps
  const hSearch = useCallback((e: React.ChangeEvent<HTMLInputElement>) => { const v = e.target.value; setSearch(v); setPage(1); setHasSearched(true); if (dr.current) clearTimeout(dr.current); dr.current = setTimeout(() => { fetchData({ page: 1, search: v || undefined }); }, 400); }, [fetchData]);
  const hOrder = useCallback((e: React.ChangeEvent<HTMLSelectElement>) => { const n = e.target.value as QualitativeScaleSublevelOrderingT; setOrdering(n); setPage(1); fetchData({ page: 1, ordering: n }); }, [fetchData]);
  const hnp = qualitativeScaleSublevels.length >= pageSize;
  const cols: TableColumnProps<QualitativeScaleSublevelT>[] = [{ key: "scale_name", label: "Escala", className: tableFirstColumnClassname }, { key: "sublevel_name", label: "Subnivel", className: tableColumnsClassname }, { key: "is_active", label: "Estado", className: tableColumnsClassname, render: (s) => s.is_active ? <Badge variant="default">Activo</Badge> : <Badge variant="outline">Inactivo</Badge> }];
  return (<div className="space-y-4"><div className="flex flex-col items-start justify-between gap-4 sm:flex-row sm:items-center"><div><h1 className="text-2xl font-extrabold text-slate-800">Escalas por Subnivel</h1><p className="mt-1 text-sm text-slate-500">Gestiona la asignación de escalas cualitativas a subniveles</p></div><button type="button" onClick={() => openModal()} className="inline-flex items-center gap-2 rounded-lg bg-primary px-4 py-2.5 text-sm font-bold text-white hover:bg-primary-hover"><Plus className="size-4" />Nueva Asignación</button></div><div className="overflow-visible rounded-xl border border-slate-200 bg-white shadow-sm"><div className="flex flex-wrap items-center gap-3 border-b border-slate-200 bg-slate-50/50 px-4 py-3"><SearchInput name="search" type="text" onChange={hSearch} value={search} className="relative min-w-50 flex-1" placeholder="Filtrar..." /><select value={ordering} onChange={hOrder} className="block w-auto rounded-md border border-gray-300 bg-white px-3 py-2 text-sm text-gray-700 focus:border-blue-500 focus:outline-none focus:ring-1 focus:ring-blue-500">{O.map((o) => <option key={o.value} value={o.value}>{o.label}</option>)}</select></div><CustomTable<QualitativeScaleSublevelT> data={qualitativeScaleSublevels} columns={cols} isLoading={isLoading && qualitativeScaleSublevels.length === 0} emptyMessage={hasSearched ? "No se encontraron registros" : "No se encontraron escalas por subnivel"} actionsTitle="Acciones" className={tableClassname} loadingMessage="Cargando..." rowActions={(s) => (<div className="flex items-center justify-end gap-1"><button type="button" onClick={() => openModal(s)} className="inline-flex items-center justify-center rounded-md p-2 text-slate-400 hover:bg-slate-100" title="Editar"><Pencil className="size-4" /></button></div>)} /><Pagination page={page} pageSize={pageSize} totalItems={qualitativeScaleSublevels.length} isLoading={isLoading} hasNextPage={hnp} onPageChange={(np) => { setPage(np); fetchData({ page: np }); }} onPageSizeChange={(ns) => { setPageSize(ns); setPage(1); fetchData({ page: 1, pageSize: ns }); }} /></div><FormModal isOpen={isOpen} onClose={closeModal} isEdit={isEdit} editingQualitativeScaleSublevel={editingQualitativeScaleSublevel} onSubmit={handleSubmit} submitErrors={submitErrors} scaleOptions={scaleOptions} sublevelOptions={sublevelOptions} /></div>);
}
