import {
  AlertTriangle,
  BookOpen,
  CalendarClock,
  CalendarDays,
  CalendarRange,
  CheckSquare,
  ClipboardList,
  Clock,
  DoorOpen,
  FileText,
  FolderLock,
  GraduationCap,
  Grid,
  Key,
  KeyRound,
  Layers,
  LayoutDashboard,
  Settings,
  Shield,
  SlidersHorizontal,
  Table,
  User,
  UserCheck,
  UserPlus,
  UserRound,
  Users,
  type LucideIcon,
} from "lucide-react";

const iconMap: Record<string, LucideIcon> = {
  LayoutDashboard,
  User,
  Calendar: CalendarDays,
  Building: DoorOpen,
  Settings,
  Clock,
  Layers,
  BookOpen,
  CalendarRange,
  ClipboardList,
  UserCheck,
  Grid,
  SlidersHorizontal,
  AlertTriangle,
  UserClock: CalendarClock,
  Table,
  Key,
  KeyRound,
  Shield,
  FolderLock,
  Users,
  GraduationCap,
  UserPlus,
  UserRound,
  CheckSquare,
  FileText,
};

export function getIconByName(name: string | undefined): LucideIcon | null {
  if (!name) return null;
  return iconMap[name] ?? null;
}
