export const PROFILE_ROUTE = "/profile";

export const IAM_ROUTES_CONST = {
  USERS: "/users",
  ROLES: "/roles",
  PERMISSIONS: "/permissions",
} as const;

export const PROTECTED_ROUTES = {
  DASHBOARD: "/dashboard",
  SCHOOL_YEARS: "/school-years",
  ACADEMIC_GRADES: "/academic-grades",
  ACADEMIC_LEVELS: "/academic-levels",
  SECTIONS: "/sections",
  SUBJECTS: "/subjects",
  ACADEMIC_PERIODS: "/academic-periods",
  SUBJECT_ACADEMIC_CONFIGS: "/subject-academic-configs",
  TEACHER_SUBJECT_SECTIONS: "/teacher-subject-sections",
  SUBJECT_OFFERINGS: "/subject-offerings",
  QUALITATIVE_SCALES: "/qualitative-scales",
  ACTIVITY_TYPES: "/activity-types",
  EVALUATION_BLOCKS: "/evaluation-blocks",
  BLOCK_COMPONENTS: "/block-components",
  STUDENT_NOTES: "/student-notes",
  GRADE_HISTORY: "/grade-history",
  PERIOD_GRADE_SUMMARIES: "/period-grade-summaries",
  ACADEMIC_SUBLEVELS: "/academic-subnivels",
  PERIOD_TYPES: "/period-types",
  STUDENTS: "/students",
  STUDENT_REPRESENTATIVES: "/student-representatives",
  ENROLLMENTS: "/enrollments",
  TAKE_ATTENDANCE: "/attendance/take",
  ATTENDANCES: "/attendances",
  ATTENDANCE_SUMMARY: "/attendance/summary",
  ATTENDANCE_STATUSES: "/attendance-statuses",
  ABSENCE_TYPES: "/absence-types",
  TEACHER_SCHEDULE: "/teacher/schedule",
  TEACHER_ACTIVITIES: "/teacher/activities",
  TEACHER_GRADING: "/teacher/grading",
  TEACHER_ATTENDANCE: "/teacher/attendance",
  TEACHER_INCIDENTS: "/teacher/incidents",
  STUDENT_GRADES: "/student/grades",
  STUDENT_ATTENDANCE: "/student/attendance",
  STUDENT_CONDUCT: "/student/conduct",
  ANALYTICS_EARLY_ALERTS: "/analytics/early-alerts",
  ANALYTICS_RISK_SCORES: "/analytics/risk-scores",
  ANALYTICS_RISK_SCORE_DETAIL: "/analytics/risk-scores/:id",
  ANALYTICS_SCORING_CONFIG: "/analytics/scoring-config",
  ANALYTICS_MODEL_EVALUATOR: "/analytics/model-evaluator",
};
