export { default as studentReducer } from './student/redux/student.slice'
export { clearStudentsError } from './student/redux/student.slice'
export * from './student/redux/student.thunks'
export * from './student/redux/student.selectors'
export * from './student/constants'
export * from './student/helpers'
export * from './student/hooks'
export * from './student/services'
export * from './student/types'
export { default as StudentPage } from './student/pages/StudentPage'

export { default as representativeReducer } from './representative/redux/representative.slice'
export { clearRepresentativesError } from './representative/redux/representative.slice'
export * from './representative/redux/representative.thunks'
export * from './representative/redux/representative.selectors'
export * from './representative/constants'
export * from './representative/helpers'
export * from './representative/hooks'
export * from './representative/services'
export * from './representative/types'
export { default as RepresentativePage } from './representative/pages/RepresentativePage'
