import { Eye, Pencil, Trash2 } from "lucide-react"; import { useCallback, useEffect, useRef, useState } from "react";
import { tableClassname, tableColumnsClassname, tableFirstColumnClassname } from "@app/styles/styles"; import { Badge } from "@shared/components/Badge";
import { SearchInput } from "@shared/components/Form"; import { Pagination } from "@shared/components/Pagination"; import { CustomTable } from "@shared/components/Table";
import type { TableColumnProps } from "@shared/components/Table"; import type { StudentNoteListParamsT, StudentNoteOrderingT, StudentNoteT } from "../student-notes.types";
const O: { label: string; value: StudentNoteOrderingT }[] = [{ label: "Matrícula (A-Z)", value: "enrollment_name" }, { label: "Matrícula (Z-A)", value: "-enrollment_name" }, { label: "Actividad (A-Z)", value: "evaluative_activity_title" }, { label: "Actividad (Z-A)", value: "-evaluative_activity_title" }, { label: "Puntaje (asc)", value: "numeric_score" }, { label: "Puntaje (desc)", value: "-numeric_score" }, { label: "Fecha (asc)", value: "created_at" }, { label: "Fecha (desc)", value: "-created_at" }];
type Props = { studentNotes: StudentNoteT[]; isLoading: boolean; loadStudentNotes: (p?: StudentNoteListParamsT) => void; onEdit: (s: StudentNoteT) => void; onView: (s: StudentNoteT) => void; onDelete: (s: StudentNoteT) => void; };
export const StudentNotesTable = ({ studentNotes, isLoading, loadStudentNotes, onEdit, onView, onDelete }: Props) => {
  const [search, setSearch] = useState(""); const [page, setPage] = useState(1); const [pageSize, setPageSize] = useState(10); const [ordering, setOrdering] = useState<StudentNoteOrderingT>("created_at"); const [hasSearched, setHasSearched] = useState(false);
  const dr = useRef<ReturnType<typeof setTimeout>>(undefined);
  const fetchData = useCallback((o?: { page?: number; pageSize?: number; search?: string; ordering?: StudentNoteOrderingT }) => { loadStudentNotes({ page: o?.page ?? page, pageSize: o?.pageSize ?? pageSize, search: o?.search !== undefined ? o.search : search || undefined, ordering: o?.ordering ?? ordering }); }, [loadStudentNotes, page, pageSize, search, ordering]);
  useEffect(() => { fetchData(); }, []); // eslint-disable-line react-hooks/exhaustive-deps
  const hSearch = useCallback((e: React.ChangeEvent<HTMLInputElement>) => { const v = e.target.value; setSearch(v); setPage(1); setHasSearched(true); if (dr.current) clearTimeout(dr.current); dr.current = setTimeout(() => { fetchData({ page: 1, search: v || undefined }); }, 400); }, [fetchData]);
  const hOrder = useCallback((e: React.ChangeEvent<HTMLSelectElement>) => { const n = e.target.value as StudentNoteOrderingT; setOrdering(n); setPage(1); fetchData({ page: 1, ordering: n }); }, [fetchData]);
  const hnp = studentNotes.length >= pageSize;
  const cols: TableColumnProps<StudentNoteT>[] = [{ key: "enrollment_name", label: "Matrícula", className: tableFirstColumnClassname }, { key: "evaluative_activity_title", label: "Actividad", className: tableColumnsClassname }, { key: "numeric_score", label: "Puntaje", className: tableColumnsClassname }, { key: "grading_mode", label: "Tipo", className: tableColumnsClassname }, { key: "sync_status", label: "Sinc.", className: tableColumnsClassname, render: (s) => { const v = s.sync_status === "SINCRONIZADO" ? "default" : s.sync_status === "ERROR" ? "outline" : "secondary"; return <Badge variant={v}>{s.sync_status}</Badge>; } }];
  return (<div className="overflow-visible rounded-xl border border-slate-200 bg-white shadow-sm"><div className="flex flex-wrap items-center gap-3 border-b border-slate-200 bg-slate-50/50 px-4 py-3"><SearchInput name="search" type="text" onChange={hSearch} value={search} className="relative min-w-50 flex-1" placeholder="Filtrar notas..." /><select value={ordering} onChange={hOrder} className="block w-auto rounded-md border border-gray-300 bg-white px-3 py-2 text-sm text-gray-700 focus:border-blue-500 focus:outline-none focus:ring-1 focus:ring-blue-500">{O.map((o) => <option key={o.value} value={o.value}>{o.label}</option>)}</select></div><CustomTable<StudentNoteT> data={studentNotes} columns={cols} isLoading={isLoading && studentNotes.length === 0} emptyMessage={hasSearched ? "No se encontraron notas con los filtros" : "No se encontraron notas de estudiantes"} actionsTitle="Acciones" className={tableClassname} loadingMessage="Cargando..." rowActions={(s) => (<div className="flex items-center justify-end gap-1"><button type="button" onClick={() => onView(s)} className="inline-flex items-center justify-center rounded-md p-2 text-slate-400 hover:bg-slate-100" title="Ver"><Eye className="size-4" /></button><button type="button" onClick={() => onEdit(s)} className="inline-flex items-center justify-center rounded-md p-2 text-slate-400 hover:bg-slate-100" title="Editar"><Pencil className="size-4" /></button><button type="button" onClick={() => onDelete(s)} className="inline-flex items-center justify-center rounded-md p-2 text-red-400 hover:bg-red-50" title="Desactivar"><Trash2 className="size-4" /></button></div>)} /><Pagination page={page} pageSize={pageSize} totalItems={studentNotes.length} isLoading={isLoading} hasNextPage={hnp} onPageChange={(np) => { setPage(np); fetchData({ page: np }); }} onPageSizeChange={(ns) => { setPageSize(ns); setPage(1); fetchData({ page: 1, pageSize: ns }); }} /></div>);
};
