import { useAppDispatch, useAppSelector } from "@shared/redux/hooks"; import { useCallback, useState } from "react"; import { schoolYearService } from "./school-year.service"; import { loadPending, loadSuccess, loadError, entityCreated, entityUpdated, entityDeleted, mutationError, selectSchoolYears, selectSchoolYearsStatus, selectSchoolYearError } from "./school-year.slice"; import type { SchoolYearCreateDataT, SchoolYearCreateParamsT, SchoolYearDeleteParamsT, SchoolYearFormValues, SchoolYearListParamsT, SchoolYearT, SchoolYearUpdateParamsT } from "./school-year.types";
export type CreateRejectValue = { msg: string; data: Record<string, string> | null; }; export type ValidationErrors = Record<string, string>; export interface SubmitErrorState { general: string[]; validation: ValidationErrors; }
const toRejectValue = (e: unknown): CreateRejectValue => { const msg = e instanceof Error ? e.message : "Error desconocido"; const cause = e instanceof Error ? (e as { cause?: unknown }).cause : undefined; const d = (cause as { response?: { data?: { data?: unknown } } })?.response?.data; return { msg, data: (d?.data as Record<string, string> | null) ?? null }; };
export const useSchoolYearController = () => {
  const dispatch = useAppDispatch(); const items = useAppSelector(selectSchoolYears); const status = useAppSelector(selectSchoolYearsStatus); const error = useAppSelector(selectSchoolYearError);
  const load = useCallback(async (p?: SchoolYearListParamsT) => { dispatch(loadPending()); try { const items = await schoolYearService.list(p ?? { page: 1, pageSize: 100 }); dispatch(loadSuccess(items)); } catch (err) { dispatch(loadError(err instanceof Error ? err.message : "Error")); } }, [dispatch]);
  const create = useCallback(async (d: SchoolYearCreateParamsT): Promise<SchoolYearT> => { try { const c = await schoolYearService.create(d); dispatch(entityCreated(c)); return c; } catch (err) { const rv = toRejectValue(err); dispatch(mutationError(rv.msg)); throw rv; } }, [dispatch]);
  const update = useCallback(async (p: SchoolYearUpdateParamsT): Promise<SchoolYearT> => { try { const u = await schoolYearService.update(p); dispatch(entityUpdated(u)); return u; } catch (err) { const rv = toRejectValue(err); dispatch(mutationError(rv.msg)); throw rv; } }, [dispatch]);
  const remove = useCallback(async (id: SchoolYearDeleteParamsT): Promise<void> => { try { const { id: did } = await schoolYearService.softDelete(id); dispatch(entityDeleted(did)); } catch (err) { dispatch(mutationError(err instanceof Error ? err.message : "Error")); } }, [dispatch]);
  return { schoolYears: items, isLoading: status === "loading", error, loadSchoolYears: load, createSchoolYear: create, updateSchoolYear: update, deleteSchoolYear: remove };
};
export type SYControllerT = ReturnType<typeof useSchoolYearController>;
const extractError = (e: unknown) => { if (e && typeof e === "object" && "msg" in e && typeof (e as { msg?: unknown }).msg === "string") { const obj = e as CreateRejectValue; const fes: ValidationErrors = {}; const gen: string[] = []; if (obj.data && typeof obj.data === "object") { for (const [k, v] of Object.entries(obj.data)) { if (typeof v === "string") fes[k] = v; else gen.push(`${k}: ${v}`); } } if (gen.length === 0 && Object.keys(fes).length === 0) gen.push(obj.msg); return { msg: obj.msg, general: gen, validation: fes }; } const msg = e instanceof Error ? e.message : "Error desconocido"; return { msg, general: [msg], validation: {} }; };
const uwCreate = async (d: SchoolYearCreateDataT, create: SYControllerT["createSchoolYear"]) => { try { return { ok: true as const, result: await create(d), errors: { general: [], validation: {} } as SubmitErrorState }; } catch (e) { const p = extractError(e); return { ok: false as const, result: null, errors: { general: p.general, validation: p.validation } as SubmitErrorState }; } };
const uwUpdate = async (p: SchoolYearUpdateParamsT, update: SYControllerT["updateSchoolYear"]) => { try { return { ok: true as const, result: await update(p), errors: { general: [], validation: {} } as SubmitErrorState }; } catch (e) { const p2 = extractError(e); return { ok: false as const, result: null, errors: { general: p2.general, validation: p2.validation } as SubmitErrorState }; } };
interface UseFormArgs { create: SYControllerT["createSchoolYear"]; update: SYControllerT["updateSchoolYear"]; }
export const useSchoolYearForm = ({ create, update }: UseFormArgs) => {
  const [isOpen, setIsOpen] = useState(false); const [editing, setEditing] = useState<SchoolYearT | null>(null); const [submitErrors, setSubmitErrors] = useState<SubmitErrorState>({ general: [], validation: {} }); const isEdit = !!editing;
  const openModal = useCallback((s?: SchoolYearT) => { setEditing(s ?? null); setSubmitErrors({ general: [], validation: {} }); setIsOpen(true); }, []);
  const closeModal = useCallback(() => { setIsOpen(false); setEditing(null); setSubmitErrors({ general: [], validation: {} }); }, []);
  const handleSubmit = useCallback(async (values: SchoolYearFormValues) => { setSubmitErrors({ general: [], validation: {} }); if (editing) { const { name, start_date, end_date, is_active } = values; const r = await uwUpdate({ id: editing.id, data: { name, start_date, end_date, is_active } }, update); if (r.ok) { closeModal(); return; } setSubmitErrors(r.errors); } else { const { name, start_date, end_date } = values; const r = await uwCreate({ name, start_date, end_date }, create); if (r.ok) { closeModal(); return; } setSubmitErrors(r.errors); } }, [editing, create, update, closeModal]);
  return { isOpen, isEdit, editingSchoolYear: editing, submitErrors, openModal, closeModal, handleSubmit };
};
