import { apiClient, getApiErrorMessage } from "@shared/services/api.client"; import type { PaginatedData, ResponseApi } from "@shared/types/api.response.types"; import { SCHOOL_YEAR_ENDPOINTS } from "./school-year.constants"; import type { SchoolYearCreateDataT, SchoolYearDeleteParamsT, SchoolYearGetParamsT, SchoolYearListParamsT, SchoolYearServiceT, SchoolYearT, SchoolYearUpdateParamsT } from "./school-year.types";
class SchoolYearService implements SchoolYearServiceT {
  async list(p?: SchoolYearListParamsT): Promise<SchoolYearT[]> { try { const pg = p?.page ?? 1; const ps = p?.pageSize ?? 100; const sq = p?.search ? `&search=${encodeURIComponent(p.search)}` : ""; const oq = p?.ordering ? `&ordering=${encodeURIComponent(p.ordering)}` : ""; const { data } = await apiClient.get<ResponseApi<PaginatedData<SchoolYearT>>>(`${SCHOOL_YEAR_ENDPOINTS.LIST}?page=${pg}&page_size=${ps}${sq}${oq}`); return data.data.results; } catch (error) { throw new Error(getApiErrorMessage(error), { cause: error }); } }
  async get(id: SchoolYearGetParamsT): Promise<SchoolYearT> { try { const { data } = await apiClient.get<ResponseApi<SchoolYearT>>(SCHOOL_YEAR_ENDPOINTS.DETAIL(id)); return data.data; } catch (error) { throw new Error(getApiErrorMessage(error), { cause: error }); } }
  async create(d: SchoolYearCreateDataT): Promise<SchoolYearT> { try { const { data } = await apiClient.post<ResponseApi<SchoolYearT>>(SCHOOL_YEAR_ENDPOINTS.LIST, d); return data.data; } catch (error) { throw new Error(getApiErrorMessage(error), { cause: error }); } }
  async update(p: SchoolYearUpdateParamsT): Promise<SchoolYearT> { try { const { data } = await apiClient.patch<ResponseApi<SchoolYearT>>(SCHOOL_YEAR_ENDPOINTS.DETAIL(p.id), p.data); return data.data; } catch (error) { throw new Error(getApiErrorMessage(error), { cause: error }); } }
  async softDelete(id: SchoolYearDeleteParamsT): Promise<{ id: number }> { try { const { data } = await apiClient.post<ResponseApi<{ id: number }>>(SCHOOL_YEAR_ENDPOINTS.SOFT_DELETE(id)); return data.data; } catch (error) { throw new Error(getApiErrorMessage(error), { cause: error }); } }
}
export const schoolYearService = new SchoolYearService();
