import { Plus } from "lucide-react"; import { useCallback, useState } from "react"; import { useSchoolYearController, useSchoolYearForm } from "./school-year.controller"; import { SchoolYearDeleteModal } from "./components/SchoolYearDeleteModal"; import { SchoolYearFormModal } from "./components/SchoolYearFormModal"; import { SchoolYearTable } from "./components/SchoolYearTable"; import { SchoolYearViewModal } from "./components/SchoolYearViewModal"; import type { SchoolYearT } from "./school-year.types";
export default function SchoolYearsPage() {
  const { schoolYears, isLoading, loadSchoolYears, createSchoolYear, updateSchoolYear, deleteSchoolYear } = useSchoolYearController();
  const { isOpen, isEdit, editingSchoolYear, submitErrors, openModal, closeModal, handleSubmit } = useSchoolYearForm({ create: createSchoolYear, update: updateSchoolYear });
  const [viewing, setViewing] = useState<SchoolYearT | null>(null); const [isViewOpen, setIsViewOpen] = useState(false);
  const [deleting, setDeleting] = useState<SchoolYearT | null>(null); const [isDeleteOpen, setIsDeleteOpen] = useState(false);
  const openV = useCallback((s: SchoolYearT) => { setViewing(s); setIsViewOpen(true); }, []); const closeV = useCallback(() => { setViewing(null); setIsViewOpen(false); }, []);
  const openD = useCallback((s: SchoolYearT) => { setDeleting(s); setIsDeleteOpen(true); }, []); const closeD = useCallback(() => { setDeleting(null); setIsDeleteOpen(false); }, []);
  const handleDel = useCallback(async (id: number) => { await deleteSchoolYear(id); }, [deleteSchoolYear]);
  return (<div className="space-y-4"><div className="flex flex-col items-start justify-between gap-4 sm:flex-row sm:items-center"><div><h1 className="text-2xl font-extrabold text-slate-800">Años Escolares</h1><p className="mt-1 text-sm text-slate-500">Gestiona los años escolares</p></div><button type="button" onClick={() => openModal()} className="inline-flex items-center gap-2 rounded-lg bg-primary px-4 py-2.5 text-sm font-bold text-white hover:bg-primary-hover"><Plus className="size-4" />Nuevo Año</button></div><SchoolYearTable schoolYears={schoolYears} isLoading={isLoading} loadSchoolYears={loadSchoolYears} onEdit={openModal} onView={openV} onDelete={openD} /><SchoolYearFormModal isOpen={isOpen} onClose={closeModal} isEdit={isEdit} editingSchoolYear={editingSchoolYear} onSubmit={handleSubmit} submitErrors={submitErrors} /><SchoolYearViewModal isOpen={isViewOpen} schoolYearId={viewing?.id ?? null} onClose={closeV} /><SchoolYearDeleteModal isOpen={isDeleteOpen} schoolYear={deleting} onClose={closeD} onConfirm={handleDel} /></div>);
}
