import { createSlice, type PayloadAction } from "@reduxjs/toolkit"; import type { RootState } from "@shared/redux/store"; import type { RequestStatusT } from "@shared/types/request.types"; import type { SchoolYearT } from "./school-year.types";
export interface SchoolYearStateT { schoolYears: SchoolYearT[]; status: RequestStatusT; error: string | null; }
const initialState: SchoolYearStateT = { schoolYears: [], status: "idle", error: null };
const slice = createSlice({ name: "schoolYear", initialState, reducers: { loadPending(s) { s.status = "loading"; s.error = null; }, loadSuccess(s, a: PayloadAction<SchoolYearT[]>) { s.schoolYears = a.payload; s.status = "succeeded"; }, loadError(s, a: PayloadAction<string>) { s.status = "failed"; s.error = a.payload; }, entityCreated(s, a: PayloadAction<SchoolYearT>) { s.schoolYears.unshift(a.payload); s.status = "succeeded"; }, entityUpdated(s, a: PayloadAction<SchoolYearT>) { const idx = s.schoolYears.findIndex((p) => p.id === a.payload.id); if (idx !== -1) s.schoolYears[idx] = a.payload; s.status = "succeeded"; }, entityDeleted(s, a: PayloadAction<number>) { s.schoolYears = s.schoolYears.filter((p) => p.id !== a.payload); s.status = "succeeded"; }, mutationError(s, a: PayloadAction<string>) { s.status = "failed"; s.error = a.payload; }, clearError(s) { s.error = null; } } });
export const { loadPending, loadSuccess, loadError, entityCreated, entityUpdated, entityDeleted, mutationError, clearError } = slice.actions;
export const selectSchoolYears = (s: RootState): SchoolYearT[] => s.institutions.schoolYear.schoolYears;
export const selectSchoolYearsStatus = (s: RootState): RequestStatusT => s.institutions.schoolYear.status;
export const selectSchoolYearError = (s: RootState): string | null => s.institutions.schoolYear.error;
export const schoolYearReducer = slice.reducer; export default slice.reducer;
