import { apiClient, getApiErrorMessage } from "@shared/services/api.client"; import type { PaginatedData, ResponseApi } from "@shared/types/api.response.types"; import { ACTIVITY_TYPES_ENDPOINTS } from "./activity-types.constants";
import type { ActivityTypeCreateDataT, ActivityTypeDeleteParamsT, ActivityTypeGetParamsT, ActivityTypeListParamsT, ActivityTypeServiceT, ActivityTypeT, ActivityTypeUpdateParamsT } from "./activity-types.types";
class ActivityTypeService implements ActivityTypeServiceT {
  async list(p?: ActivityTypeListParamsT): Promise<ActivityTypeT[]> { try { const page = p?.page ?? 1; const pageSize = p?.pageSize ?? 100; const sq = p?.search ? `&search=${encodeURIComponent(p.search)}` : ""; const oq = p?.ordering ? `&ordering=${encodeURIComponent(p.ordering)}` : ""; const { data } = await apiClient.get<ResponseApi<PaginatedData<ActivityTypeT>>>(`${ACTIVITY_TYPES_ENDPOINTS.LIST}?page=${page}&page_size=${pageSize}${sq}${oq}`); return data.data.results; } catch (error) { throw new Error(getApiErrorMessage(error), { cause: error }); } }
  async get(id: ActivityTypeGetParamsT): Promise<ActivityTypeT> { try { const { data } = await apiClient.get<ResponseApi<ActivityTypeT>>(ACTIVITY_TYPES_ENDPOINTS.DETAIL(id)); return data.data; } catch (error) { throw new Error(getApiErrorMessage(error), { cause: error }); } }
  async create(d: ActivityTypeCreateDataT): Promise<ActivityTypeT> { try { const { data } = await apiClient.post<ResponseApi<ActivityTypeT>>(ACTIVITY_TYPES_ENDPOINTS.LIST, d); return data.data; } catch (error) { throw new Error(getApiErrorMessage(error), { cause: error }); } }
  async update(p: ActivityTypeUpdateParamsT): Promise<ActivityTypeT> { try { const { data } = await apiClient.patch<ResponseApi<ActivityTypeT>>(ACTIVITY_TYPES_ENDPOINTS.DETAIL(p.id), p.data); return data.data; } catch (error) { throw new Error(getApiErrorMessage(error), { cause: error }); } }
  async softDelete(id: ActivityTypeDeleteParamsT): Promise<{ id: number }> { try { const { data } = await apiClient.post<ResponseApi<{ id: number }>>(ACTIVITY_TYPES_ENDPOINTS.SOFT_DELETE(id)); return data.data; } catch (error) { throw new Error(getApiErrorMessage(error), { cause: error }); } }
}
export const activityTypeService = new ActivityTypeService();
