import { enrollmentService } from "@features/students/enrollments/enrollments.service"; import { academicPeriodService } from "@features/academic/academic-period"; import { subjectOfferingService } from "@features/academic/subject-offering/subject-offering.service"; import { qualitativeScaleService } from "@features/grading/qualitative-scales/qualitative-scales.service"; import { useEffect, useReducer } from "react";
interface Option { label: string; value: string; }
interface State { enrollmentOptions: Option[]; subjectOfferingOptions: Option[]; academicPeriodOptions: Option[]; qualitativeScaleOptions: Option[]; loading: boolean; }
type Action = { type: "loading" } | { type: "success"; enrollments: Option[]; subjectOfferings: Option[]; academicPeriods: Option[]; qualitativeScales: Option[] } | { type: "error" };
function reducer(s: State, a: Action): State { switch (a.type) { case "loading": return { ...s, loading: true }; case "success": return { ...s, loading: false, enrollmentOptions: a.enrollments, subjectOfferingOptions: a.subjectOfferings, academicPeriodOptions: a.academicPeriods, qualitativeScaleOptions: a.qualitativeScales }; case "error": return { ...s, loading: false }; } }
const PROMOTION_STATUSES: Option[] = [{ label: "Aprobado", value: "approved" }, { label: "Reprobado", value: "failed" }];
export const usePeriodGradeSummaryOptions = () => {
  const [state, dispatch] = useReducer(reducer, { enrollmentOptions: [], subjectOfferingOptions: [], academicPeriodOptions: [], qualitativeScaleOptions: [], loading: true });
  useEffect(() => { let cancelled = false; dispatch({ type: "loading" }); Promise.all([enrollmentService.list({ page: 1, pageSize: 100 }), subjectOfferingService.list({ page: 1, pageSize: 100 }), academicPeriodService.list({ page: 1, pageSize: 100 }), qualitativeScaleService.list({ page: 1, pageSize: 100 })]).then(([enrollments, subjectOfferings, academicPeriods, qualitativeScales]) => { if (cancelled) return; dispatch({ type: "success", enrollments: enrollments.map((i) => ({ label: i.student_name, value: String(i.id) })), subjectOfferings: subjectOfferings.map((i) => ({ label: i.section_name, value: String(i.id) })), academicPeriods: academicPeriods.map((i) => ({ label: i.name, value: String(i.id) })), qualitativeScales: qualitativeScales.filter((i) => i.is_active).map((i) => ({ label: i.name, value: String(i.id) })) }); }).catch(() => { if (!cancelled) dispatch({ type: "error" }); }); return () => { cancelled = true; }; }, []);
  return { enrollmentOptions: state.enrollmentOptions, subjectOfferingOptions: state.subjectOfferingOptions, academicPeriodOptions: state.academicPeriodOptions, qualitativeScaleOptions: state.qualitativeScaleOptions, promotionStatusOptions: PROMOTION_STATUSES, loading: state.loading };
};
