import { apiClient, getApiErrorMessage } from "@shared/services/api.client"; import type { PaginatedData, ResponseApi } from "@shared/types/api.response.types"; import { PERIOD_GRADE_SUMMARIES_ENDPOINTS } from "./period-grade-summaries.constants"; import type { PeriodGradeSummaryCreateDataT, PeriodGradeSummaryDeleteParamsT, PeriodGradeSummaryGetParamsT, PeriodGradeSummaryListParamsT, PeriodGradeSummaryServiceT, PeriodGradeSummaryT, PeriodGradeSummaryUpdateParamsT } from "./period-grade-summaries.types";
class PeriodGradeSummaryService implements PeriodGradeSummaryServiceT {
  async list(p?: PeriodGradeSummaryListParamsT): Promise<PeriodGradeSummaryT[]> { try { const page = p?.page ?? 1; const ps = p?.pageSize ?? 100; const sq = p?.search ? `&search=${encodeURIComponent(p.search)}` : ""; const oq = p?.ordering ? `&ordering=${encodeURIComponent(p.ordering)}` : ""; const filters = p?.filters ?? {}; const fq = Object.entries(filters).filter(([, v]) => v !== undefined && v !== null).map(([k, v]) => `&${k}=${encodeURIComponent(String(v))}`).join(""); const { data } = await apiClient.get<ResponseApi<PaginatedData<PeriodGradeSummaryT>>>(`${PERIOD_GRADE_SUMMARIES_ENDPOINTS.LIST}?page=${page}&page_size=${ps}${sq}${oq}${fq}`); return data.data.results; } catch (error) { throw new Error(getApiErrorMessage(error), { cause: error }); } }
  async get(id: PeriodGradeSummaryGetParamsT): Promise<PeriodGradeSummaryT> { try { const { data } = await apiClient.get<ResponseApi<PeriodGradeSummaryT>>(PERIOD_GRADE_SUMMARIES_ENDPOINTS.DETAIL(id)); return data.data; } catch (error) { throw new Error(getApiErrorMessage(error), { cause: error }); } }
  async create(d: PeriodGradeSummaryCreateDataT): Promise<PeriodGradeSummaryT> { try { const { data } = await apiClient.post<ResponseApi<PeriodGradeSummaryT>>(PERIOD_GRADE_SUMMARIES_ENDPOINTS.LIST, d); return data.data; } catch (error) { throw new Error(getApiErrorMessage(error), { cause: error }); } }
  async update(p: PeriodGradeSummaryUpdateParamsT): Promise<PeriodGradeSummaryT> { try { const { data } = await apiClient.patch<ResponseApi<PeriodGradeSummaryT>>(PERIOD_GRADE_SUMMARIES_ENDPOINTS.DETAIL(p.id), p.data); return data.data; } catch (error) { throw new Error(getApiErrorMessage(error), { cause: error }); } }
  async softDelete(id: PeriodGradeSummaryDeleteParamsT): Promise<{ id: number }> { try { const { data } = await apiClient.post<ResponseApi<{ id: number }>>(PERIOD_GRADE_SUMMARIES_ENDPOINTS.SOFT_DELETE(id)); return data.data; } catch (error) { throw new Error(getApiErrorMessage(error), { cause: error }); } }
}
export const periodGradeSummaryService = new PeriodGradeSummaryService();
