import { Plus } from "lucide-react"; import { useCallback, useState } from "react"; import { PeriodGradeSummaryDeleteModal } from "./components/PeriodGradeSummaryDeleteModal"; import { PeriodGradeSummariesFormModal } from "./components/PeriodGradeSummariesFormModal"; import { PeriodGradeSummariesTable } from "./components/PeriodGradeSummariesTable"; import { PeriodGradeSummaryViewModal } from "./components/PeriodGradeSummaryViewModal"; import { usePeriodGradeSummariesController, usePeriodGradeSummariesForm } from "./period-grade-summaries.controller"; import { usePeriodGradeSummaryOptions } from "./period-grade-summaries.options"; import type { PeriodGradeSummaryT } from "./period-grade-summaries.types";
export default function PeriodGradeSummariesPage() {
  const { periodGradeSummaries, isLoading, loadPeriodGradeSummaries, createPeriodGradeSummary, updatePeriodGradeSummary, deletePeriodGradeSummary } = usePeriodGradeSummariesController();
  const { isOpen, isEdit, editingPeriodGradeSummary, submitErrors, openModal, closeModal, handleSubmit } = usePeriodGradeSummariesForm({ create: createPeriodGradeSummary, update: updatePeriodGradeSummary });
  const { enrollmentOptions, subjectOfferingOptions, academicPeriodOptions, qualitativeScaleOptions, promotionStatusOptions } = usePeriodGradeSummaryOptions();
  const [viewing, setViewing] = useState<PeriodGradeSummaryT | null>(null); const [isViewOpen, setIsViewOpen] = useState(false);
  const [deleting, setDeleting] = useState<PeriodGradeSummaryT | null>(null); const [isDeleteOpen, setIsDeleteOpen] = useState(false);
  const openV = useCallback((s: PeriodGradeSummaryT) => { setViewing(s); setIsViewOpen(true); }, []); const closeV = useCallback(() => { setViewing(null); setIsViewOpen(false); }, []);
  const openD = useCallback((s: PeriodGradeSummaryT) => { setDeleting(s); setIsDeleteOpen(true); }, []); const closeD = useCallback(() => { setDeleting(null); setIsDeleteOpen(false); }, []);
  const handleDel = useCallback(async (id: number) => { await deletePeriodGradeSummary(id); }, [deletePeriodGradeSummary]);
  return (<div className="space-y-4"><div className="flex flex-col items-start justify-between gap-4 sm:flex-row sm:items-center"><div><h1 className="text-2xl font-extrabold text-slate-800">Resúmenes de Calificaciones</h1><p className="mt-1 text-sm text-slate-500">Gestiona los resúmenes de calificaciones por período</p></div><button type="button" onClick={() => openModal()} className="inline-flex items-center gap-2 rounded-lg bg-primary px-4 py-2.5 text-sm font-bold text-white hover:bg-primary-hover"><Plus className="size-4" />Nuevo Resumen</button></div><PeriodGradeSummariesTable periodGradeSummaries={periodGradeSummaries} isLoading={isLoading} loadPeriodGradeSummaries={loadPeriodGradeSummaries} onEdit={openModal} onView={openV} onDelete={openD} /><PeriodGradeSummariesFormModal isOpen={isOpen} onClose={closeModal} isEdit={isEdit} editingPeriodGradeSummary={editingPeriodGradeSummary} onSubmit={handleSubmit} submitErrors={submitErrors} enrollmentOptions={enrollmentOptions} subjectOfferingOptions={subjectOfferingOptions} academicPeriodOptions={academicPeriodOptions} qualitativeScaleOptions={qualitativeScaleOptions} promotionStatusOptions={promotionStatusOptions} /><PeriodGradeSummaryViewModal isOpen={isViewOpen} periodGradeSummaryId={viewing?.id ?? null} onClose={closeV} /><PeriodGradeSummaryDeleteModal isOpen={isDeleteOpen} periodGradeSummary={deleting} onClose={closeD} onConfirm={handleDel} /></div>);
}
