import { useFormik } from "formik"; import { useEffect } from "react"; import { checkboxClassname, inputClassname, selectClassname } from "@app/styles/styles"; import { CustomCheckbox, CustomInput, CustomSelect } from "@shared/components/Form"; import { sectionSchema } from "../section.utils"; import type { SubmitErrorState } from "../section.controller"; import type { SectionFormValues, SectionT } from "../section.types";
const getFieldLabel = (f: string): string => ({ parallel: "Paralelo", school_year: "Año escolar", academic_grade: "Grado académico", non_field_errors: "Error general" }[f] || f);
interface Props { isOpen: boolean; onClose: () => void; isEdit: boolean; editingSection: SectionT | null; onSubmit: (values: SectionFormValues) => Promise<void>; submitErrors: SubmitErrorState; academicGradeOptions: { label: string; value: string }[]; schoolYearOptions: { label: string; value: string }[]; }
export const SectionFormModal = ({ isOpen, onClose, isEdit, editingSection, onSubmit, submitErrors, academicGradeOptions, schoolYearOptions }: Props) => {
  const getIV = (): SectionFormValues => { if (editingSection) return { parallel: editingSection.parallel, school_year: editingSection.school_year, academic_grade: editingSection.academic_grade, is_active: editingSection.is_active }; return { parallel: "", school_year: 0, academic_grade: 0, is_active: true }; };
  const formik = useFormik<SectionFormValues>({ initialValues: getIV(), validationSchema: sectionSchema, enableReinitialize: true, onSubmit });
  useEffect(() => { if (isOpen && editingSection) formik.setValues(getIV()); }, [isOpen, editingSection]);
  if (!isOpen) return null;
  return (<div className="fixed inset-0 z-50 flex items-center justify-center"><div className="absolute inset-0 bg-black/40" onClick={onClose} /><div className="relative w-full max-w-md animate-slide-up overflow-hidden rounded-xl bg-white shadow-xl"><div className="flex items-center justify-between border-b border-slate-200 px-5 py-4"><div><h3 className="text-lg font-semibold text-slate-900">{isEdit ? "Editar" : "Nueva"} Sección</h3><p className="mt-0.5 text-sm text-slate-500">Configure la sección/paralelo</p></div><button type="button" onClick={onClose} className="rounded-lg p-1.5 text-slate-400 hover:bg-slate-100"><svg className="size-5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" /></svg></button></div>
    {(submitErrors.general.length > 0 || Object.keys(submitErrors.validation).length > 0) && (<div className="mx-5 mt-3 rounded-lg border border-red-300 bg-red-50 p-4 shadow-sm"><div className="flex items-start gap-2"><svg className="mt-0.5 size-5 flex-shrink-0 text-red-600" fill="currentColor" viewBox="0 0 20 20"><path fillRule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zM8.707 7.293a1 1 0 00-1.414 1.414L8.586 10l-1.293 1.293a1 1 0 101.414 1.414L10 11.414l1.293 1.293a1 1 0 001.414-1.414L11.414 10l1.293-1.293a1 1 0 00-1.414-1.414L10 8.586 8.707 7.293z" clipRule="evenodd" /></svg><div className="flex-1"><p className="mb-2 text-sm font-semibold text-red-800">Error al guardar</p>{submitErrors.general.length > 0 && (<ul>{submitErrors.general.map((e, i) => (<li key={i} className="text-sm text-red-700">• {e}</li>))}</ul>)}{Object.keys(submitErrors.validation).length > 0 && (<ul>{Object.entries(submitErrors.validation).map(([f, m]) => (<li key={f} className="text-sm text-red-700"><span className="font-semibold">{getFieldLabel(f)}:</span> {m}</li>))}</ul>)}</div></div></div>)}
    <form onSubmit={formik.handleSubmit} className="space-y-4 p-5"><CustomInput label="Paralelo" name="parallel" placeholder="Ej: A, B, C" value={formik.values.parallel} onBlur={formik.handleBlur} onChange={formik.handleChange} type="text" error={formik.touched.parallel ? formik.errors.parallel : undefined} className={inputClassname} /><CustomSelect label="Año Escolar" name="school_year" value={String(formik.values.school_year)} onChange={(o) => formik.setFieldValue("school_year", Number(o.value))} options={schoolYearOptions} className={selectClassname} error={formik.touched.school_year ? formik.errors.school_year : undefined} /><CustomSelect label="Grado Académico" name="academic_grade" value={String(formik.values.academic_grade)} onChange={(o) => formik.setFieldValue("academic_grade", Number(o.value))} options={academicGradeOptions} className={selectClassname} error={formik.touched.academic_grade ? formik.errors.academic_grade : undefined} />{isEdit && <CustomCheckbox name="is_active" checked={formik.values.is_active} onChange={formik.handleChange} onBlur={formik.handleBlur} label="Activo" className={checkboxClassname} />}<div className="flex items-center justify-end gap-3 border-t border-slate-200 pt-4"><button type="button" onClick={onClose} className="rounded-lg border border-slate-300 bg-white px-4 py-2 text-sm font-medium text-slate-700 hover:bg-slate-50">Cancelar</button><button type="submit" disabled={formik.isSubmitting} className="rounded-lg bg-primary px-4 py-2 text-sm font-medium text-white hover:bg-primary-hover disabled:opacity-60">{formik.isSubmitting ? "Guardando..." : "Guardar"}</button></div></form></div></div>);
};
