import { Plus } from "lucide-react"; import { useCallback, useState } from "react"; import { useAcademicLevelController, useAcademicLevelForm } from "./academic-level.controller"; import { AcademicLevelDeleteModal } from "./components/AcademicLevelDeleteModal"; import { AcademicLevelFormModal } from "./components/AcademicLevelFormModal"; import { AcademicLevelTable } from "./components/AcademicLevelTable"; import { AcademicLevelViewModal } from "./components/AcademicLevelViewModal"; import type { AcademicLevelT } from "./academic-level.types";
export default function AcademicLevelsPage() {
  const { academicLevels, isLoading, loadAcademicLevels, createAcademicLevel, updateAcademicLevel, deleteAcademicLevel } = useAcademicLevelController();
  const { isOpen, isEdit, editingAcademicLevel, submitErrors, openModal, closeModal, handleSubmit } = useAcademicLevelForm({ create: createAcademicLevel, update: updateAcademicLevel });
  const [viewing, setViewing] = useState<AcademicLevelT | null>(null); const [isViewOpen, setIsViewOpen] = useState(false);
  const [deleting, setDeleting] = useState<AcademicLevelT | null>(null); const [isDeleteOpen, setIsDeleteOpen] = useState(false);
  const openV = useCallback((l: AcademicLevelT) => { setViewing(l); setIsViewOpen(true); }, []); const closeV = useCallback(() => { setViewing(null); setIsViewOpen(false); }, []);
  const openD = useCallback((l: AcademicLevelT) => { setDeleting(l); setIsDeleteOpen(true); }, []); const closeD = useCallback(() => { setDeleting(null); setIsDeleteOpen(false); }, []);
  const handleDel = useCallback(async (id: number) => { await deleteAcademicLevel(id); }, [deleteAcademicLevel]);
  return (<div className="space-y-4"><div className="flex flex-col items-start justify-between gap-4 sm:flex-row sm:items-center"><div><h1 className="text-2xl font-extrabold text-slate-800">Niveles Académicos</h1><p className="mt-1 text-sm text-slate-500">Gestiona los niveles académicos</p></div><button type="button" onClick={() => openModal()} className="inline-flex items-center gap-2 rounded-lg bg-primary px-4 py-2.5 text-sm font-bold text-white hover:bg-primary-hover"><Plus className="size-4" />Nuevo Nivel</button></div><AcademicLevelTable academicLevels={academicLevels} isLoading={isLoading} loadAcademicLevels={loadAcademicLevels} onEdit={openModal} onView={openV} onDelete={openD} /><AcademicLevelFormModal isOpen={isOpen} onClose={closeModal} isEdit={isEdit} editingAcademicLevel={editingAcademicLevel} onSubmit={handleSubmit} submitErrors={submitErrors} /><AcademicLevelViewModal isOpen={isViewOpen} academicLevelId={viewing?.id ?? null} onClose={closeV} /><AcademicLevelDeleteModal isOpen={isDeleteOpen} academicLevel={deleting} onClose={closeD} onConfirm={handleDel} /></div>);
}
