import { useAppDispatch, useAppSelector } from "@shared/redux/hooks"; import { useCallback, useState } from "react"; import { academicLevelService } from "./academic-level.service"; import { loadPending, loadSuccess, loadError, entityCreated, entityUpdated, entityDeleted, mutationError, selectAcademicLevels, selectAcademicLevelsStatus, selectAcademicLevelError } from "./academic-level.slice"; import type { AcademicLevelCreateDataT, AcademicLevelCreateParamsT, AcademicLevelDeleteParamsT, AcademicLevelFormValues, AcademicLevelListParamsT, AcademicLevelT, AcademicLevelUpdateParamsT } from "./academic-level.types";
export type CreateRejectValue = { msg: string; data: Record<string, string> | null; }; export type ValidationErrors = Record<string, string>; export interface SubmitErrorState { general: string[]; validation: ValidationErrors; }
const toRejectValue = (e: unknown): CreateRejectValue => { const msg = e instanceof Error ? e.message : "Error desconocido"; const cause = e instanceof Error ? (e as { cause?: unknown }).cause : undefined; const d = (cause as { response?: { data?: { data?: unknown } } })?.response?.data; return { msg, data: (d?.data as Record<string, string> | null) ?? null }; };
export const useAcademicLevelController = () => {
  const dispatch = useAppDispatch(); const items = useAppSelector(selectAcademicLevels); const status = useAppSelector(selectAcademicLevelsStatus); const error = useAppSelector(selectAcademicLevelError);
  const load = useCallback(async (p?: AcademicLevelListParamsT) => { dispatch(loadPending()); try { const items = await academicLevelService.list(p ?? { page: 1, pageSize: 100 }); dispatch(loadSuccess(items)); } catch (err) { dispatch(loadError(err instanceof Error ? err.message : "Error")); } }, [dispatch]);
  const create = useCallback(async (d: AcademicLevelCreateParamsT): Promise<AcademicLevelT> => { try { const c = await academicLevelService.create(d); dispatch(entityCreated(c)); return c; } catch (err) { const rv = toRejectValue(err); dispatch(mutationError(rv.msg)); throw rv; } }, [dispatch]);
  const update = useCallback(async (p: AcademicLevelUpdateParamsT): Promise<AcademicLevelT> => { try { const u = await academicLevelService.update(p); dispatch(entityUpdated(u)); return u; } catch (err) { const rv = toRejectValue(err); dispatch(mutationError(rv.msg)); throw rv; } }, [dispatch]);
  const remove = useCallback(async (id: AcademicLevelDeleteParamsT): Promise<void> => { try { const { id: did } = await academicLevelService.softDelete(id); dispatch(entityDeleted(did)); } catch (err) { dispatch(mutationError(err instanceof Error ? err.message : "Error")); } }, [dispatch]);
  return { academicLevels: items, isLoading: status === "loading", error, loadAcademicLevels: load, createAcademicLevel: create, updateAcademicLevel: update, deleteAcademicLevel: remove };
};
export type ALControllerT = ReturnType<typeof useAcademicLevelController>;
const extractError = (e: unknown) => { if (e && typeof e === "object" && "msg" in e && typeof (e as { msg?: unknown }).msg === "string") { const obj = e as CreateRejectValue; const fes: ValidationErrors = {}; const gen: string[] = []; if (obj.data && typeof obj.data === "object") { for (const [k, v] of Object.entries(obj.data)) { if (typeof v === "string") fes[k] = v; else gen.push(`${k}: ${v}`); } } if (gen.length === 0 && Object.keys(fes).length === 0) gen.push(obj.msg); return { msg: obj.msg, general: gen, validation: fes }; } const msg = e instanceof Error ? e.message : "Error desconocido"; return { msg, general: [msg], validation: {} }; };
const uwCreate = async (d: AcademicLevelCreateDataT, create: ALControllerT["createAcademicLevel"]) => { try { return { ok: true as const, result: await create(d), errors: { general: [], validation: {} } as SubmitErrorState }; } catch (e) { const p = extractError(e); return { ok: false as const, result: null, errors: { general: p.general, validation: p.validation } as SubmitErrorState }; } };
const uwUpdate = async (p: AcademicLevelUpdateParamsT, update: ALControllerT["updateAcademicLevel"]) => { try { return { ok: true as const, result: await update(p), errors: { general: [], validation: {} } as SubmitErrorState }; } catch (e) { const p2 = extractError(e); return { ok: false as const, result: null, errors: { general: p2.general, validation: p2.validation } as SubmitErrorState }; } };
interface UseFormArgs { create: ALControllerT["createAcademicLevel"]; update: ALControllerT["updateAcademicLevel"]; }
export const useAcademicLevelForm = ({ create, update }: UseFormArgs) => {
  const [isOpen, setIsOpen] = useState(false); const [editing, setEditing] = useState<AcademicLevelT | null>(null); const [submitErrors, setSubmitErrors] = useState<SubmitErrorState>({ general: [], validation: {} }); const isEdit = !!editing;
  const openModal = useCallback((s?: AcademicLevelT) => { setEditing(s ?? null); setSubmitErrors({ general: [], validation: {} }); setIsOpen(true); }, []);
  const closeModal = useCallback(() => { setIsOpen(false); setEditing(null); setSubmitErrors({ general: [], validation: {} }); }, []);
  const handleSubmit = useCallback(async (values: AcademicLevelFormValues) => { setSubmitErrors({ general: [], validation: {} }); if (editing) { const { code, name, description, is_active } = values; const r = await uwUpdate({ id: editing.id, data: { code, name, description, is_active } }, update); if (r.ok) { closeModal(); return; } setSubmitErrors(r.errors); } else { const { code, name, description } = values; const r = await uwCreate({ code, name, description }, create); if (r.ok) { closeModal(); return; } setSubmitErrors(r.errors); } }, [editing, create, update, closeModal]);
  return { isOpen, isEdit, editingAcademicLevel: editing, submitErrors, openModal, closeModal, handleSubmit };
};
