import { apiClient, getApiErrorMessage } from "@shared/services/api.client"; import type { PaginatedData, ResponseApi } from "@shared/types/api.response.types"; import { ACADEMIC_LEVEL_ENDPOINTS } from "./academic-level.constants"; import type { AcademicLevelCreateDataT, AcademicLevelDeleteParamsT, AcademicLevelGetParamsT, AcademicLevelListParamsT, AcademicLevelServiceT, AcademicLevelT, AcademicLevelUpdateParamsT } from "./academic-level.types";
class AcademicLevelService implements AcademicLevelServiceT {
  async list(p?: AcademicLevelListParamsT): Promise<AcademicLevelT[]> { try { const pg = p?.page ?? 1; const ps = p?.pageSize ?? 100; const sq = p?.search ? `&search=${encodeURIComponent(p.search)}` : ""; const oq = p?.ordering ? `&ordering=${encodeURIComponent(p.ordering)}` : ""; const { data } = await apiClient.get<ResponseApi<PaginatedData<AcademicLevelT>>>(`${ACADEMIC_LEVEL_ENDPOINTS.LIST}?page=${pg}&page_size=${ps}${sq}${oq}`); return data.data.results; } catch (error) { throw new Error(getApiErrorMessage(error), { cause: error }); } }
  async get(id: AcademicLevelGetParamsT): Promise<AcademicLevelT> { try { const { data } = await apiClient.get<ResponseApi<AcademicLevelT>>(ACADEMIC_LEVEL_ENDPOINTS.DETAIL(id)); return data.data; } catch (error) { throw new Error(getApiErrorMessage(error), { cause: error }); } }
  async create(d: AcademicLevelCreateDataT): Promise<AcademicLevelT> { try { const { data } = await apiClient.post<ResponseApi<AcademicLevelT>>(ACADEMIC_LEVEL_ENDPOINTS.LIST, d); return data.data; } catch (error) { throw new Error(getApiErrorMessage(error), { cause: error }); } }
  async update(p: AcademicLevelUpdateParamsT): Promise<AcademicLevelT> { try { const { data } = await apiClient.patch<ResponseApi<AcademicLevelT>>(ACADEMIC_LEVEL_ENDPOINTS.DETAIL(p.id), p.data); return data.data; } catch (error) { throw new Error(getApiErrorMessage(error), { cause: error }); } }
  async softDelete(id: AcademicLevelDeleteParamsT): Promise<{ id: number }> { try { const { data } = await apiClient.post<ResponseApi<{ id: number }>>(ACADEMIC_LEVEL_ENDPOINTS.SOFT_DELETE(id)); return data.data; } catch (error) { throw new Error(getApiErrorMessage(error), { cause: error }); } }
}
export const academicLevelService = new AcademicLevelService();
