import { useFormik } from "formik"; import { useEffect } from "react"; import { checkboxClassname, inputClassname } from "@app/styles/styles"; import { CustomCheckbox, CustomInput } from "@shared/components/Form"; import { representativeSchema } from "../representative.utils"; import type { SubmitErrorState } from "../representative.controller"; import type { RepresentativeFormValues, RepresentativeT } from "../representative.types";
const getFieldLabel = (f: string): string => ({ dni: "DNI", names: "Nombres", last_names: "Apellidos", email: "Email", phone: "Teléfono", address: "Dirección", city: "Ciudad", document_type: "Tipo documento", non_field_errors: "Error general" }[f] || f);
interface Props { isOpen: boolean; onClose: () => void; isEdit: boolean; editingRepresentative: RepresentativeT | null; onSubmit: (values: RepresentativeFormValues) => Promise<void>; submitErrors: SubmitErrorState; }
export const RepresentativeFormModal = ({ isOpen, onClose, isEdit, editingRepresentative, onSubmit, submitErrors }: Props) => {
  const getIV = (): RepresentativeFormValues => { if (editingRepresentative) return { dni: editingRepresentative.dni, names: editingRepresentative.names, last_names: editingRepresentative.last_names, email: editingRepresentative.email, phone: editingRepresentative.phone, address: editingRepresentative.address, city: editingRepresentative.city, document_type: editingRepresentative.document_type, is_active: editingRepresentative.is_active }; return { dni: "", names: "", last_names: "", email: "", phone: "", address: "", city: null, document_type: "", is_active: true }; };
  const formik = useFormik<RepresentativeFormValues>({ initialValues: getIV(), validationSchema: representativeSchema, enableReinitialize: true, onSubmit });
  useEffect(() => { if (isOpen && editingRepresentative) formik.setValues(getIV()); }, [isOpen, editingRepresentative]);
  if (!isOpen) return null;
  return (<div className="fixed inset-0 z-50 flex items-center justify-center"><div className="absolute inset-0 bg-black/40" onClick={onClose} /><div className="relative w-full max-w-lg animate-slide-up overflow-hidden rounded-xl bg-white shadow-xl"><div className="flex items-center justify-between border-b border-slate-200 px-5 py-4"><div><h3 className="text-lg font-semibold text-slate-900">{isEdit ? "Editar" : "Nuevo"} Representante</h3><p className="mt-0.5 text-sm text-slate-500">Configure los datos del representante</p></div><button type="button" onClick={onClose} className="rounded-lg p-1.5 text-slate-400 hover:bg-slate-100"><svg className="size-5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" /></svg></button></div>
    {(submitErrors.general.length > 0 || Object.keys(submitErrors.validation).length > 0) && (<div className="mx-5 mt-3 rounded-lg border border-red-300 bg-red-50 p-4 shadow-sm"><div className="flex items-start gap-2"><svg className="mt-0.5 size-5 flex-shrink-0 text-red-600" fill="currentColor" viewBox="0 0 20 20"><path fillRule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zM8.707 7.293a1 1 0 00-1.414 1.414L8.586 10l-1.293 1.293a1 1 0 101.414 1.414L10 11.414l1.293 1.293a1 1 0 001.414-1.414L11.414 10l1.293-1.293a1 1 0 00-1.414-1.414L10 8.586 8.707 7.293z" clipRule="evenodd" /></svg><div className="flex-1"><p className="mb-2 text-sm font-semibold text-red-800">Error al guardar</p>{submitErrors.general.length > 0 && (<ul>{submitErrors.general.map((e, i) => (<li key={i} className="text-sm text-red-700">• {e}</li>))}</ul>)}{Object.keys(submitErrors.validation).length > 0 && (<ul>{Object.entries(submitErrors.validation).map(([f, m]) => (<li key={f} className="text-sm text-red-700"><span className="font-semibold">{getFieldLabel(f)}:</span> {m}</li>))}</ul>)}</div></div></div>)}
    <form onSubmit={formik.handleSubmit} className="space-y-4 p-5"><div className="grid grid-cols-2 gap-4"><CustomInput label="DNI" name="dni" value={formik.values.dni} onBlur={formik.handleBlur} onChange={formik.handleChange} type="text" error={formik.touched.dni ? formik.errors.dni : undefined} className={inputClassname} /><CustomInput label="Tipo Documento" name="document_type" value={formik.values.document_type} onBlur={formik.handleBlur} onChange={formik.handleChange} type="text" error={formik.touched.document_type ? formik.errors.document_type : undefined} className={inputClassname} /></div><div className="grid grid-cols-2 gap-4"><CustomInput label="Nombres" name="names" value={formik.values.names} onBlur={formik.handleBlur} onChange={formik.handleChange} type="text" error={formik.touched.names ? formik.errors.names : undefined} className={inputClassname} /><CustomInput label="Apellidos" name="last_names" value={formik.values.last_names} onBlur={formik.handleBlur} onChange={formik.handleChange} type="text" error={formik.touched.last_names ? formik.errors.last_names : undefined} className={inputClassname} /></div><div className="grid grid-cols-2 gap-4"><CustomInput label="Email" name="email" value={formik.values.email} onBlur={formik.handleBlur} onChange={formik.handleChange} type="email" error={formik.touched.email ? formik.errors.email : undefined} className={inputClassname} /><CustomInput label="Teléfono" name="phone" value={formik.values.phone} onBlur={formik.handleBlur} onChange={formik.handleChange} type="text" error={formik.touched.phone ? formik.errors.phone : undefined} className={inputClassname} /></div><CustomInput label="Dirección" name="address" value={formik.values.address} onBlur={formik.handleBlur} onChange={formik.handleChange} type="text" error={formik.touched.address ? formik.errors.address : undefined} className={inputClassname} />{isEdit && <CustomCheckbox name="is_active" checked={formik.values.is_active} onChange={formik.handleChange} onBlur={formik.handleBlur} label="Activo" className={checkboxClassname} />}<div className="flex items-center justify-end gap-3 border-t border-slate-200 pt-4"><button type="button" onClick={onClose} className="rounded-lg border border-slate-300 bg-white px-4 py-2 text-sm font-medium text-slate-700 hover:bg-slate-50">Cancelar</button><button type="submit" disabled={formik.isSubmitting} className="rounded-lg bg-primary px-4 py-2 text-sm font-medium text-white hover:bg-primary-hover disabled:opacity-60">{formik.isSubmitting ? "Guardando..." : "Guardar"}</button></div></form></div></div>);
};
