import { apiClient, getApiErrorMessage } from "@shared/services/api.client"; import type { PaginatedData, ResponseApi } from "@shared/types/api.response.types"; import { SEVERITY_ENDPOINTS } from "./severity.constants";
import type { SeverityCreateDataT, SeverityDeleteParamsT, SeverityGetParamsT, SeverityListParamsT, SeverityServiceT, SeverityT, SeverityUpdateParamsT } from "./severity.types";
class SeverityService implements SeverityServiceT {
  async list(p?: SeverityListParamsT): Promise<SeverityT[]> { try { const qs = new URLSearchParams(); if (p?.page) qs.set("page", String(p.page)); if (p?.pageSize) qs.set("page_size", String(p.pageSize)); if (p?.search) qs.set("search", p.search); if (p?.ordering) qs.set("ordering", p.ordering); const q = qs.toString(); const url = q ? `${SEVERITY_ENDPOINTS.LIST}?${q}` : SEVERITY_ENDPOINTS.LIST; const { data } = await apiClient.get<ResponseApi<PaginatedData<SeverityT>>>(url); return data.data.results; } catch (error) { throw new Error(getApiErrorMessage(error), { cause: error }); } }
  async get(id: SeverityGetParamsT): Promise<SeverityT> { try { const { data } = await apiClient.get<ResponseApi<SeverityT>>(SEVERITY_ENDPOINTS.DETAIL(id)); return data.data; } catch (error) { throw new Error(getApiErrorMessage(error), { cause: error }); } }
  async create(d: SeverityCreateDataT): Promise<SeverityT> { try { const { data } = await apiClient.post<ResponseApi<SeverityT>>(SEVERITY_ENDPOINTS.LIST, d); return data.data; } catch (error) { throw new Error(getApiErrorMessage(error), { cause: error }); } }
  async update(p: SeverityUpdateParamsT): Promise<SeverityT> { try { const { data } = await apiClient.patch<ResponseApi<SeverityT>>(SEVERITY_ENDPOINTS.DETAIL(p.id), p.data); return data.data; } catch (error) { throw new Error(getApiErrorMessage(error), { cause: error }); } }
  async softDelete(id: SeverityDeleteParamsT): Promise<{ id: number }> { try { const { data } = await apiClient.post<ResponseApi<{ id: number }>>(SEVERITY_ENDPOINTS.SOFT_DELETE(id)); return data.data; } catch (error) { throw new Error(getApiErrorMessage(error), { cause: error }); } }
}
export const severityService = new SeverityService();
