import { Eye, Pencil, Trash2 } from "lucide-react"; import { useCallback, useEffect, useRef, useState } from "react";
import { tableClassname, tableColumnsClassname, tableFirstColumnClassname } from "@app/styles/styles"; import { Badge } from "@shared/components/Badge";
import { SearchInput } from "@shared/components/Form"; import { Pagination } from "@shared/components/Pagination"; import { CustomTable } from "@shared/components/Table";
import type { TableColumnProps } from "@shared/components/Table"; import type { PeriodGradeSummaryListParamsT, PeriodGradeSummaryOrderingT, PeriodGradeSummaryT } from "../period-grade-summaries.types";
const O: { label: string; value: PeriodGradeSummaryOrderingT }[] = [{ label: "Estudiante (A-Z)", value: "enrollment_name" }, { label: "Estudiante (Z-A)", value: "-enrollment_name" }, { label: "Oferta (A-Z)", value: "subject_offering_name" }, { label: "Oferta (Z-A)", value: "-subject_offering_name" }, { label: "Período (A-Z)", value: "academic_period_name" }, { label: "Período (Z-A)", value: "-academic_period_name" }, { label: "Promedio (asc)", value: "final_avg_truncated" }, { label: "Promedio (desc)", value: "-final_avg_truncated" }];
type Props = { periodGradeSummaries: PeriodGradeSummaryT[]; isLoading: boolean; loadPeriodGradeSummaries: (p?: PeriodGradeSummaryListParamsT) => void; onEdit: (s: PeriodGradeSummaryT) => void; onView: (s: PeriodGradeSummaryT) => void; onDelete: (s: PeriodGradeSummaryT) => void; };
export const PeriodGradeSummariesTable = ({ periodGradeSummaries, isLoading, loadPeriodGradeSummaries, onEdit, onView, onDelete }: Props) => {
  const [search, setSearch] = useState(""); const [page, setPage] = useState(1); const [pageSize, setPageSize] = useState(10); const [ordering, setOrdering] = useState<PeriodGradeSummaryOrderingT>("-final_avg_truncated"); const [hasSearched, setHasSearched] = useState(false);
  const dr = useRef<ReturnType<typeof setTimeout>>(undefined);
  const fetchData = useCallback((o?: { page?: number; pageSize?: number; search?: string; ordering?: PeriodGradeSummaryOrderingT }) => { loadPeriodGradeSummaries({ page: o?.page ?? page, pageSize: o?.pageSize ?? pageSize, search: o?.search !== undefined ? o.search : search || undefined, ordering: o?.ordering ?? ordering }); }, [loadPeriodGradeSummaries, page, pageSize, search, ordering]);
  useEffect(() => { fetchData(); }, []); // eslint-disable-line react-hooks/exhaustive-deps
  const hSearch = useCallback((e: React.ChangeEvent<HTMLInputElement>) => { const v = e.target.value; setSearch(v); setPage(1); setHasSearched(true); if (dr.current) clearTimeout(dr.current); dr.current = setTimeout(() => { fetchData({ page: 1, search: v || undefined }); }, 400); }, [fetchData]);
  const hOrder = useCallback((e: React.ChangeEvent<HTMLSelectElement>) => { const n = e.target.value as PeriodGradeSummaryOrderingT; setOrdering(n); setPage(1); fetchData({ page: 1, ordering: n }); }, [fetchData]);
  const hnp = periodGradeSummaries.length >= pageSize;
  const cols: TableColumnProps<PeriodGradeSummaryT>[] = [{ key: "enrollment_name", label: "Estudiante", className: tableFirstColumnClassname }, { key: "subject_offering_name", label: "Oferta", className: tableColumnsClassname }, { key: "academic_period_name", label: "Período", className: tableColumnsClassname }, { key: "final_avg_truncated", label: "Promedio", className: tableColumnsClassname, render: (s) => <Badge variant={s.final_avg_truncated >= 7 ? "default" : s.final_avg_truncated >= 5 ? "secondary" : "destructive"}>{s.final_avg_truncated}</Badge> }, { key: "requires_recovery", label: "Recupera", className: tableColumnsClassname, render: (s) => s.requires_recovery ? <Badge variant="destructive">Sí</Badge> : <Badge variant="outline">No</Badge> }];
  return (<div className="overflow-visible rounded-xl border border-slate-200 bg-white shadow-sm"><div className="flex flex-wrap items-center gap-3 border-b border-slate-200 bg-slate-50/50 px-4 py-3"><SearchInput name="search" type="text" onChange={hSearch} value={search} className="relative min-w-50 flex-1" placeholder="Filtrar..." /><select value={ordering} onChange={hOrder} className="block w-auto rounded-md border border-gray-300 bg-white px-3 py-2 text-sm text-gray-700 focus:border-blue-500 focus:outline-none focus:ring-1 focus:ring-blue-500">{O.map((o) => <option key={o.value} value={o.value}>{o.label}</option>)}</select></div><CustomTable<PeriodGradeSummaryT> data={periodGradeSummaries} columns={cols} isLoading={isLoading && periodGradeSummaries.length === 0} emptyMessage={hasSearched ? "No se encontraron resúmenes con los filtros" : "No se encontraron resúmenes de calificaciones"} actionsTitle="Acciones" className={tableClassname} loadingMessage="Cargando..." rowActions={(s) => (<div className="flex items-center justify-end gap-1"><button type="button" onClick={() => onView(s)} className="inline-flex items-center justify-center rounded-md p-2 text-slate-400 hover:bg-slate-100" title="Ver"><Eye className="size-4" /></button><button type="button" onClick={() => onEdit(s)} className="inline-flex items-center justify-center rounded-md p-2 text-slate-400 hover:bg-slate-100" title="Editar"><Pencil className="size-4" /></button><button type="button" onClick={() => onDelete(s)} className="inline-flex items-center justify-center rounded-md p-2 text-red-400 hover:bg-red-50" title="Desactivar"><Trash2 className="size-4" /></button></div>)} /><Pagination page={page} pageSize={pageSize} totalItems={periodGradeSummaries.length} isLoading={isLoading} hasNextPage={hnp} onPageChange={(np) => { setPage(np); fetchData({ page: np }); }} onPageSizeChange={(ns) => { setPageSize(ns); setPage(1); fetchData({ page: 1, pageSize: ns }); }} /></div>);
};
