import { BookOpen, User, Percent } from "lucide-react"; import { useEffect, useReducer } from "react"; import { periodGradeSummaryService } from "../period-grade-summaries.service"; import type { PeriodGradeSummaryT } from "../period-grade-summaries.types";
interface State { data: PeriodGradeSummaryT | null; loading: boolean; error: string | null; } type Action = { type: "loading" } | { type: "success"; data: PeriodGradeSummaryT } | { type: "error"; error: string };
function reducer(_s: State, a: Action): State { switch (a.type) { case "loading": return { data: null, loading: true, error: null }; case "success": return { data: a.data, loading: false, error: null }; case "error": return { data: null, loading: false, error: a.error }; } }
interface Props { isOpen: boolean; periodGradeSummaryId: number | null; onClose: () => void; }
export const PeriodGradeSummaryViewModal = ({ isOpen, periodGradeSummaryId, onClose }: Props) => {
  const [state, sd] = useReducer(reducer, { data: null, loading: false, error: null });
  useEffect(() => { if (isOpen && periodGradeSummaryId !== null) { sd({ type: "loading" }); periodGradeSummaryService.get(periodGradeSummaryId).then((data) => sd({ type: "success", data })).catch((err: Error) => sd({ type: "error", error: err.message })); } }, [isOpen, periodGradeSummaryId]);
  if (!isOpen) return null;
  return (<div className="fixed inset-0 z-50 flex items-center justify-center p-4"><div className="absolute inset-0 bg-black/40" onClick={onClose} /><div className="relative w-full max-w-lg animate-slide-up overflow-hidden rounded-xl bg-white shadow-xl"><div className="flex items-center justify-between border-b border-slate-200 px-6 py-4"><div><h3 className="text-lg font-semibold text-slate-900">Detalle de Resumen</h3><p className="mt-0.5 text-sm text-slate-500">Información del resumen de calificaciones</p></div><button type="button" onClick={onClose} className="rounded-lg p-1.5 text-slate-400 hover:bg-slate-100"><svg className="size-5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" /></svg></button></div><div className="space-y-5 p-6">{state.loading && (<div className="flex animate-pulse flex-col gap-4 py-4">{[1, 2, 3].map((i) => (<div key={i} className="flex items-start gap-3"><div className="size-9 rounded-lg bg-slate-100" /><div className="flex-1 space-y-2"><div className="h-3 w-20 rounded bg-slate-100" /><div className="h-4 w-48 rounded bg-slate-100" /></div></div>))}</div>)}{state.error && <div className="flex items-center gap-2.5 rounded-lg bg-red-50 p-4 text-sm text-red-600"><svg className="size-4 shrink-0" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" /></svg>{state.error}</div>}{state.data && (<div className="space-y-5"><DetailRow icon={<User className="size-4" />} label="Estudiante" value={state.data.enrollment_name} /><DetailRow icon={<BookOpen className="size-4" />} label="Oferta" value={state.data.subject_offering_name} /><DetailRow icon={<BookOpen className="size-4" />} label="Período" value={state.data.academic_period_name} /><DetailRow icon={<Percent className="size-4" />} label="Promedio" value={String(state.data.final_avg_truncated)} /><DetailRow icon={null} label="Recupera" value={state.data.requires_recovery ? "Sí" : "No"} /><DetailRow icon={null} label="Estado" value={state.data.promotion_status} /></div>)}</div><div className="flex items-center justify-end border-t border-slate-200 px-6 py-4"><button type="button" onClick={onClose} className="rounded-lg border border-slate-300 bg-white px-4 py-2 text-sm font-medium text-slate-700 hover:bg-slate-50">Cerrar</button></div></div></div>);
};
function DetailRow({ icon, label, value }: { icon: React.ReactNode | null; label: string; value: string }) { return (<div className="flex items-start gap-3">{icon !== null && <span className="flex size-9 shrink-0 items-center justify-center rounded-lg bg-slate-100 text-slate-500">{icon}</span>}{icon === null && <div className="size-9 shrink-0" />}<div className="min-w-0 flex-1"><p className="text-xs font-semibold uppercase tracking-wider text-slate-500">{label}</p><p className="mt-1 text-sm font-medium text-slate-900">{value}</p></div></div>); }
