import { Plus } from "lucide-react"; import { useCallback, useState } from "react"; import { useAcademicGradeController, useAcademicGradeForm } from "./academic-grade.controller"; import { useAcademicSubLevelOptions } from "./academic-grade.options"; import { AcademicGradeDeleteModal } from "./components/AcademicGradeDeleteModal"; import { AcademicGradeFormModal } from "./components/AcademicGradeFormModal"; import { AcademicGradeTable } from "./components/AcademicGradeTable"; import { AcademicGradeViewModal } from "./components/AcademicGradeViewModal"; import type { AcademicGradeT } from "./academic-grade.types";
export default function AcademicGradePage() {
  const { academicGrades, isLoading, loadAcademicGrades, createAcademicGrade, updateAcademicGrade, deleteAcademicGrade } = useAcademicGradeController();
  const { isOpen, isEdit, editingAcademicGrade, submitErrors, openModal, closeModal, handleSubmit } = useAcademicGradeForm({ create: createAcademicGrade, update: updateAcademicGrade });
  const { academicSubLevelOptions } = useAcademicSubLevelOptions();
  const [viewing, setViewing] = useState<AcademicGradeT | null>(null); const [isViewOpen, setIsViewOpen] = useState(false);
  const [deleting, setDeleting] = useState<AcademicGradeT | null>(null); const [isDeleteOpen, setIsDeleteOpen] = useState(false);
  const openV = useCallback((g: AcademicGradeT) => { setViewing(g); setIsViewOpen(true); }, []); const closeV = useCallback(() => { setViewing(null); setIsViewOpen(false); }, []);
  const openD = useCallback((g: AcademicGradeT) => { setDeleting(g); setIsDeleteOpen(true); }, []); const closeD = useCallback(() => { setDeleting(null); setIsDeleteOpen(false); }, []);
  const handleDel = useCallback(async (id: number) => { await deleteAcademicGrade(id); }, [deleteAcademicGrade]);
  return (<div className="space-y-4"><div className="flex flex-col items-start justify-between gap-4 sm:flex-row sm:items-center"><div><h1 className="text-2xl font-extrabold text-slate-800">Grados</h1><p className="mt-1 text-sm text-slate-500">Gestiona los grados académicos</p></div><button type="button" onClick={() => openModal()} className="inline-flex items-center gap-2 rounded-lg bg-primary px-4 py-2.5 text-sm font-bold text-white hover:bg-primary-hover"><Plus className="size-4" />Nuevo Grado</button></div><AcademicGradeTable academicGrades={academicGrades} isLoading={isLoading} loadAcademicGrades={loadAcademicGrades} onEdit={openModal} onView={openV} onDelete={openD} /><AcademicGradeFormModal isOpen={isOpen} onClose={closeModal} isEdit={isEdit} editingAcademicGrade={editingAcademicGrade} academicSublevels={academicSubLevelOptions} onSubmit={handleSubmit} submitErrors={submitErrors} /><AcademicGradeViewModal isOpen={isViewOpen} academicGradeId={viewing?.id ?? null} onClose={closeV} /><AcademicGradeDeleteModal isOpen={isDeleteOpen} academicGrade={deleting} onClose={closeD} onConfirm={handleDel} /></div>);
}
