import { useAppDispatch, useAppSelector } from "@shared/redux/hooks"; import { useCallback, useState } from "react"; import { academicGradeService } from "./academic-grade.service"; import { loadPending, loadSuccess, loadError, entityCreated, entityUpdated, entityDeleted, mutationError, selectAcademicGrades, selectAcademicGradesStatus, selectAcademicGradeError } from "./academic-grade.slice"; import type { AcademicGradeCreateDataT, AcademicGradeCreateParamsT, AcademicGradeDeleteParamsT, AcademicGradeFormValues, AcademicGradeListParamsT, AcademicGradeT, AcademicGradeUpdateParamsT } from "./academic-grade.types";
export type CreateRejectValue = { msg: string; data: Record<string, string> | null; }; export type ValidationErrors = Record<string, string>; export interface SubmitErrorState { general: string[]; validation: ValidationErrors; }
const toRejectValue = (e: unknown): CreateRejectValue => { const msg = e instanceof Error ? e.message : "Error desconocido"; const cause = e instanceof Error ? (e as { cause?: unknown }).cause : undefined; const d = (cause as { response?: { data?: { data?: unknown } } })?.response?.data; return { msg, data: (d?.data as Record<string, string> | null) ?? null }; };
export const useAcademicGradeController = () => {
  const dispatch = useAppDispatch(); const items = useAppSelector(selectAcademicGrades); const status = useAppSelector(selectAcademicGradesStatus); const error = useAppSelector(selectAcademicGradeError);
  const load = useCallback(async (p?: AcademicGradeListParamsT) => { dispatch(loadPending()); try { const items = await academicGradeService.list(p ?? { page: 1, pageSize: 100 }); dispatch(loadSuccess(items)); } catch (err) { dispatch(loadError(err instanceof Error ? err.message : "Error")); } }, [dispatch]);
  const create = useCallback(async (d: AcademicGradeCreateParamsT): Promise<AcademicGradeT> => { try { const c = await academicGradeService.create(d); dispatch(entityCreated(c)); return c; } catch (err) { const rv = toRejectValue(err); dispatch(mutationError(rv.msg)); throw rv; } }, [dispatch]);
  const update = useCallback(async (p: AcademicGradeUpdateParamsT): Promise<AcademicGradeT> => { try { const u = await academicGradeService.update(p); dispatch(entityUpdated(u)); return u; } catch (err) { const rv = toRejectValue(err); dispatch(mutationError(rv.msg)); throw rv; } }, [dispatch]);
  const remove = useCallback(async (id: AcademicGradeDeleteParamsT): Promise<void> => { try { const { id: did } = await academicGradeService.softDelete(id); dispatch(entityDeleted(did)); } catch (err) { dispatch(mutationError(err instanceof Error ? err.message : "Error")); } }, [dispatch]);
  return { academicGrades: items, isLoading: status === "loading", error, loadAcademicGrades: load, createAcademicGrade: create, updateAcademicGrade: update, deleteAcademicGrade: remove };
};
export type AGControllerT = ReturnType<typeof useAcademicGradeController>;
const extractError = (e: unknown) => { if (e && typeof e === "object" && "msg" in e && typeof (e as { msg?: unknown }).msg === "string") { const obj = e as CreateRejectValue; const fes: ValidationErrors = {}; const gen: string[] = []; if (obj.data && typeof obj.data === "object") { for (const [k, v] of Object.entries(obj.data)) { if (typeof v === "string") fes[k] = v; else gen.push(`${k}: ${v}`); } } if (gen.length === 0 && Object.keys(fes).length === 0) gen.push(obj.msg); return { msg: obj.msg, general: gen, validation: fes }; } const msg = e instanceof Error ? e.message : "Error desconocido"; return { msg, general: [msg], validation: {} }; };
const uwCreate = async (d: AcademicGradeCreateDataT, create: AGControllerT["createAcademicGrade"]) => { try { return { ok: true as const, result: await create(d), errors: { general: [], validation: {} } as SubmitErrorState }; } catch (e) { const p = extractError(e); return { ok: false as const, result: null, errors: { general: p.general, validation: p.validation } as SubmitErrorState }; } };
const uwUpdate = async (p: AcademicGradeUpdateParamsT, update: AGControllerT["updateAcademicGrade"]) => { try { return { ok: true as const, result: await update(p), errors: { general: [], validation: {} } as SubmitErrorState }; } catch (e) { const p2 = extractError(e); return { ok: false as const, result: null, errors: { general: p2.general, validation: p2.validation } as SubmitErrorState }; } };
interface UseFormArgs { create: AGControllerT["createAcademicGrade"]; update: AGControllerT["updateAcademicGrade"]; }
export const useAcademicGradeForm = ({ create, update }: UseFormArgs) => {
  const [isOpen, setIsOpen] = useState(false); const [editing, setEditing] = useState<AcademicGradeT | null>(null); const [submitErrors, setSubmitErrors] = useState<SubmitErrorState>({ general: [], validation: {} }); const isEdit = !!editing;
  const openModal = useCallback((s?: AcademicGradeT) => { setEditing(s ?? null); setSubmitErrors({ general: [], validation: {} }); setIsOpen(true); }, []);
  const closeModal = useCallback(() => { setIsOpen(false); setEditing(null); setSubmitErrors({ general: [], validation: {} }); }, []);
  const handleSubmit = useCallback(async (values: AcademicGradeFormValues) => { setSubmitErrors({ general: [], validation: {} }); if (editing) { const r = await uwUpdate({ id: editing.id, data: values }, update); if (r.ok) { closeModal(); return; } setSubmitErrors(r.errors); } else { const { code, name, academic_sublevel } = values; const r = await uwCreate({ code, name, academic_sublevel }, create); if (r.ok) { closeModal(); return; } setSubmitErrors(r.errors); } }, [editing, create, update, closeModal]);
  return { isOpen, isEdit, editingAcademicGrade: editing, submitErrors, openModal, closeModal, handleSubmit };
};
