import { apiClient, getApiErrorMessage } from "@shared/services/api.client"; import type { PaginatedData, ResponseApi } from "@shared/types/api.response.types"; import { ACADEMIC_GRADE_ENDPOINTS } from "./academic-grade.constants"; import type { AcademicGradeCreateDataT, AcademicGradeDeleteParamsT, AcademicGradeGetParamsT, AcademicGradeListParamsT, AcademicGradeServiceT, AcademicGradeT, AcademicGradeUpdateParamsT } from "./academic-grade.types";
class AcademicGradeService implements AcademicGradeServiceT {
  async list(p?: AcademicGradeListParamsT): Promise<AcademicGradeT[]> { try { const pg = p?.page ?? 1; const ps = p?.pageSize ?? 100; const sq = p?.search ? `&search=${encodeURIComponent(p.search)}` : ""; const oq = p?.ordering ? `&ordering=${encodeURIComponent(p.ordering)}` : ""; const { data } = await apiClient.get<ResponseApi<PaginatedData<AcademicGradeT>>>(`${ACADEMIC_GRADE_ENDPOINTS.LIST}?page=${pg}&page_size=${ps}${sq}${oq}`); return data.data.results; } catch (error) { throw new Error(getApiErrorMessage(error), { cause: error }); } }
  async get(id: AcademicGradeGetParamsT): Promise<AcademicGradeT> { try { const { data } = await apiClient.get<ResponseApi<AcademicGradeT>>(`${ACADEMIC_GRADE_ENDPOINTS.LIST}${id}/`); return data.data; } catch (error) { throw new Error(getApiErrorMessage(error), { cause: error }); } }
  async create(d: AcademicGradeCreateDataT): Promise<AcademicGradeT> { try { const { data } = await apiClient.post<ResponseApi<AcademicGradeT>>(ACADEMIC_GRADE_ENDPOINTS.LIST, d); return data.data; } catch (error) { throw new Error(getApiErrorMessage(error), { cause: error }); } }
  async update(p: AcademicGradeUpdateParamsT): Promise<AcademicGradeT> { try { const { data } = await apiClient.patch<ResponseApi<AcademicGradeT>>(`${ACADEMIC_GRADE_ENDPOINTS.LIST}${p.id}/`, p.data); return data.data; } catch (error) { throw new Error(getApiErrorMessage(error), { cause: error }); } }
  async softDelete(id: AcademicGradeDeleteParamsT): Promise<{ id: number }> { try { const { data } = await apiClient.post<ResponseApi<{ id: number }>>(`${ACADEMIC_GRADE_ENDPOINTS.LIST}${id}/soft-delete/`); return data.data; } catch (error) { throw new Error(getApiErrorMessage(error), { cause: error }); } }
}
export const academicGradeService = new AcademicGradeService();
