import { Eye, Pencil, Trash2 } from "lucide-react"; import { useCallback, useEffect, useRef, useState } from "react";
import { filterSelectClassname, tableClassname, tableColumnsClassname, tableFirstColumnClassname } from "@app/styles/styles";
import { CustomSelect } from "@shared/components/Form/CustomSelect/CustomSelect"; import { SearchInput } from "@shared/components/Form"; import { Pagination } from "@shared/components/Pagination"; import { CustomTable } from "@shared/components/Table";
import { useBlockComponentFilterCatalogs } from "../block-components.options";
import type { SelectOptionT } from "@shared/components/Form/CustomSelect/CustomSelectProps"; import type { TableColumnProps } from "@shared/components/Table"; import type { BlockComponentListParamsT, BlockComponentOrderingT, BlockComponentT } from "../block-components.types";
const ORDERING_OPTIONS: { label: string; value: BlockComponentOrderingT }[] = [{ label: "Nombre (A-Z)", value: "name" }, { label: "Nombre (Z-A)", value: "-name" }, { label: "Código (A-Z)", value: "code" }, { label: "Código (Z-A)", value: "-code" }, { label: "Ponderación (asc)", value: "internal_weight" }, { label: "Ponderación (desc)", value: "-internal_weight" }, { label: "Bloque (A-Z)", value: "evaluation_block_name" }, { label: "Bloque (Z-A)", value: "-evaluation_block_name" }];
type Props = { blockComponents: BlockComponentT[]; isLoading: boolean; loadBlockComponents: (p?: BlockComponentListParamsT) => void; onEdit: (s: BlockComponentT) => void; onView: (s: BlockComponentT) => void; onDelete: (s: BlockComponentT) => void; };
export const BlockComponentsTable = ({ blockComponents, isLoading, loadBlockComponents, onEdit, onView, onDelete }: Props) => {
  const [search, setSearch] = useState(""); const [page, setPage] = useState(1); const [pageSize, setPageSize] = useState(10); const [ordering, setOrdering] = useState<BlockComponentOrderingT>("name"); const [hasSearched, setHasSearched] = useState(false);
  const [evalBlockFilter, setEvalBlockFilter] = useState<number | 0>(0); const [periodFilter, setPeriodFilter] = useState<number | 0>(0); const [statusFilter, setStatusFilter] = useState<string>("");
  const { evaluationBlockOptions, academicPeriodOptions, statusOptions } = useBlockComponentFilterCatalogs();
  const debounceRef = useRef<ReturnType<typeof setTimeout>>(undefined);
  const buildFilters = useCallback(() => {
    const f: Record<string, string | number | boolean> = {};
    if (evalBlockFilter) f.evaluation_block = evalBlockFilter;
    if (periodFilter) f.academic_period = periodFilter;
    if (statusFilter) f.is_active = statusFilter === "active";
    return Object.keys(f).length > 0 ? f : undefined;
  }, [evalBlockFilter, periodFilter, statusFilter]);
  const fetchData = useCallback((o?: { page?: number; pageSize?: number; search?: string; ordering?: BlockComponentOrderingT; filters?: Record<string, string | number | boolean> }) => { loadBlockComponents({ page: o?.page ?? page, pageSize: o?.pageSize ?? pageSize, search: o?.search !== undefined ? o.search : search || undefined, ordering: o?.ordering ?? ordering, filters: o?.filters ?? buildFilters() }); }, [loadBlockComponents, page, pageSize, search, ordering, buildFilters]);
  useEffect(() => { fetchData(); }, []); // eslint-disable-line react-hooks/exhaustive-deps
  const handleSearch = useCallback((e: React.ChangeEvent<HTMLInputElement>) => { const v = e.target.value; setSearch(v); setPage(1); setHasSearched(true); if (debounceRef.current) clearTimeout(debounceRef.current); debounceRef.current = setTimeout(() => { fetchData({ page: 1, search: v || undefined }); }, 400); }, [fetchData]);
  const handleOrdering = useCallback((e: React.ChangeEvent<HTMLSelectElement>) => { const newOrdering = e.target.value as BlockComponentOrderingT; setOrdering(newOrdering); setPage(1); fetchData({ page: 1, ordering: newOrdering }); }, [fetchData]);
  const hEvalBlock = useCallback((o: SelectOptionT) => { setEvalBlockFilter(Number(o.value) || 0); setPage(1); }, []);
  const hPeriod = useCallback((o: SelectOptionT) => { setPeriodFilter(Number(o.value) || 0); setPage(1); }, []);
  const hStatus = useCallback((o: SelectOptionT) => { setStatusFilter(o.value as string); setPage(1); }, []);
  useEffect(() => { fetchData({ page: 1 }); }, [evalBlockFilter, periodFilter, statusFilter]); // eslint-disable-line react-hooks/exhaustive-deps
  const hasNextPage = blockComponents.length >= pageSize;
  const cols: TableColumnProps<BlockComponentT>[] = [{ key: "name", label: "Nombre", className: tableFirstColumnClassname, render: (s) => <span>{s.name}</span> }, { key: "evaluation_block_name", label: "Bloque", className: tableColumnsClassname, render: (s) => <span>{s.evaluation_block_name}</span> }, { key: "internal_weight", label: "Ponderación", className: tableColumnsClassname, render: (s) => <span>{s.internal_weight}%</span> }];
  return (<div className="overflow-visible rounded-xl border border-slate-200 bg-white shadow-sm"><div className="flex flex-wrap items-center gap-3 border-b border-slate-200 bg-slate-50/50 px-4 py-3"><SearchInput name="search" type="text" onChange={handleSearch} value={search} className="relative min-w-50 flex-1" placeholder="Filtrar componentes..." /><CustomSelect name="filter-eval-block" label="" placeholder="Todos los bloques" value={evalBlockFilter} options={evaluationBlockOptions} onChange={hEvalBlock} className={filterSelectClassname} /><CustomSelect name="filter-period" label="" placeholder="Todos los períodos" value={periodFilter} options={academicPeriodOptions} onChange={hPeriod} className={filterSelectClassname} /><CustomSelect name="filter-status" label="" placeholder="Todos" value={statusFilter} options={statusOptions} onChange={hStatus} className={filterSelectClassname} /><select value={ordering} onChange={handleOrdering} className="block w-auto rounded-md border border-gray-300 bg-white px-3 py-2 text-sm text-gray-700 focus:border-blue-500 focus:outline-none focus:ring-1 focus:ring-blue-500" aria-label="Ordenar">{ORDERING_OPTIONS.map((o) => <option key={o.value} value={o.value}>{o.label}</option>)}</select></div><CustomTable<BlockComponentT> data={blockComponents} columns={cols} isLoading={isLoading && blockComponents.length === 0} emptyMessage={hasSearched ? "No se encontraron componentes con los filtros" : "No se encontraron componentes de bloque"} actionsTitle="Acciones" className={tableClassname} loadingMessage="Cargando..." rowActions={(s) => (<div className="flex items-center justify-end gap-1"><button type="button" onClick={() => onView(s)} className="inline-flex items-center justify-center rounded-md p-2 text-slate-400 transition-colors hover:bg-slate-100 hover:text-slate-600" title="Ver"><Eye className="size-4" /></button><button type="button" onClick={() => onEdit(s)} className="inline-flex items-center justify-center rounded-md p-2 text-slate-400 transition-colors hover:bg-slate-100 hover:text-slate-600" title="Editar"><Pencil className="size-4" /></button><button type="button" onClick={() => onDelete(s)} className="inline-flex items-center justify-center rounded-md p-2 text-red-400 transition-colors hover:bg-red-50 hover:text-red-600" title="Eliminar"><Trash2 className="size-4" /></button></div>)} /><Pagination page={page} pageSize={pageSize} totalItems={blockComponents.length} isLoading={isLoading} hasNextPage={hasNextPage} onPageChange={(np) => { setPage(np); fetchData({ page: np }); }} onPageSizeChange={(ns) => { setPageSize(ns); setPage(1); fetchData({ page: 1, pageSize: ns }); }} /></div>);
};
