import { useFormik } from "formik"; import { X } from "lucide-react"; import { useEffect } from "react";
import { checkboxClassname, inputClassname } from "@app/styles/styles"; import { CustomCheckbox, CustomInput } from "@shared/components/Form";
import { blockComponentSchema } from "../block-components.utils"; import type { SubmitErrorState } from "../block-components.controller"; import type { BlockComponentFormValues, BlockComponentT } from "../block-components.types";
const getFieldLabel = (f: string): string => { const labels: Record<string, string> = { code: "Código", name: "Nombre", internal_weight: "Ponderación", evaluation_block: "Bloque de evaluación", non_field_errors: "Error general" }; return labels[f] || f; };
interface Props { isOpen: boolean; onClose: () => void; isEdit: boolean; editingBlockComponent: BlockComponentT | null; onSubmit: (values: BlockComponentFormValues) => Promise<void>; submitErrors: SubmitErrorState; }
export const BlockComponentsFormModal = ({ isOpen, onClose, isEdit, editingBlockComponent, onSubmit, submitErrors }: Props) => {
  const getInitialValues = (): BlockComponentFormValues => { if (editingBlockComponent) return { code: editingBlockComponent.code, name: editingBlockComponent.name, internal_weight: editingBlockComponent.internal_weight, evaluation_block: editingBlockComponent.evaluation_block, is_active: editingBlockComponent.is_active }; return { code: "", name: "", internal_weight: 0, evaluation_block: 0, is_active: true }; };
  const formik = useFormik<BlockComponentFormValues>({ initialValues: getInitialValues(), validationSchema: blockComponentSchema, enableReinitialize: true, onSubmit });
  useEffect(() => { if (isOpen && editingBlockComponent) formik.setValues(getInitialValues()); }, [isOpen, editingBlockComponent]);
  if (!isOpen) return null;
  return (<div className="fixed inset-0 z-50 flex items-center justify-center"><div className="absolute inset-0 bg-black/40" onClick={onClose} /><div className="relative w-full max-w-md animate-slide-up overflow-hidden rounded-xl bg-white shadow-xl"><div className="flex items-center justify-between border-b border-slate-200 px-5 py-4"><div><h3 className="text-lg font-semibold text-slate-900">{isEdit ? "Editar" : "Nuevo"} Componente de Bloque</h3><p className="mt-0.5 text-sm text-slate-500">Configure el componente de bloque de evaluación</p></div><button type="button" onClick={onClose} className="rounded-lg p-1.5 text-slate-400 transition hover:bg-slate-100 hover:text-slate-600"><X className="size-5" /></button></div>
    {(submitErrors.general.length > 0 || Object.keys(submitErrors.validation).length > 0) && (<div className="mx-5 mt-3 rounded-lg border border-red-300 bg-red-50 p-4 shadow-sm"><div className="flex items-start gap-2"><svg className="mt-0.5 size-5 flex-shrink-0 text-red-600" fill="currentColor" viewBox="0 0 20 20"><path fillRule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zM8.707 7.293a1 1 0 00-1.414 1.414L8.586 10l-1.293 1.293a1 1 0 101.414 1.414L10 11.414l1.293 1.293a1 1 0 001.414-1.414L11.414 10l1.293-1.293a1 1 0 00-1.414-1.414L10 8.586 8.707 7.293z" clipRule="evenodd" /></svg><div className="flex-1"><p className="mb-2 text-sm font-semibold text-red-800">Error al guardar</p>{submitErrors.general.length > 0 && (<ul className="mb-2 space-y-1">{submitErrors.general.map((err, i) => (<li key={i} className="text-sm text-red-700">• {err}</li>))}</ul>)}{Object.keys(submitErrors.validation).length > 0 && (<ul className="space-y-1">{Object.entries(submitErrors.validation).map(([f, m]) => (<li key={f} className="text-sm text-red-700"><span className="font-semibold">{getFieldLabel(f)}:</span> {m}</li>))}</ul>)}</div></div></div>)}
    <form onSubmit={formik.handleSubmit} className="space-y-4 p-5"><CustomInput label="Código" name="code" placeholder="Ej: TAR-1" value={formik.values.code} onBlur={formik.handleBlur} onChange={formik.handleChange} type="text" error={formik.touched.code ? formik.errors.code : undefined} className={inputClassname} /><CustomInput label="Nombre" name="name" placeholder="Ej: Tareas, Examen..." value={formik.values.name} onBlur={formik.handleBlur} onChange={formik.handleChange} type="text" error={formik.touched.name ? formik.errors.name : undefined} className={inputClassname} /><CustomInput label="Ponderación (%)" name="internal_weight" placeholder="0-100" value={formik.values.internal_weight} onBlur={formik.handleBlur} onChange={formik.handleChange} type="number" error={formik.touched.internal_weight ? formik.errors.internal_weight : undefined} className={inputClassname} /><CustomInput label="ID Bloque" name="evaluation_block" placeholder="ID del bloque" value={formik.values.evaluation_block} onBlur={formik.handleBlur} onChange={formik.handleChange} type="number" error={formik.touched.evaluation_block ? formik.errors.evaluation_block : undefined} className={inputClassname} />{isEdit && <CustomCheckbox name="is_active" checked={formik.values.is_active} onChange={formik.handleChange} onBlur={formik.handleBlur} label="Activo" className={checkboxClassname} />}<div className="flex items-center justify-end gap-3 border-t border-slate-200 pt-4"><button type="button" onClick={onClose} className="inline-flex items-center justify-center rounded-lg border border-slate-300 bg-white px-4 py-2 text-sm font-medium text-slate-700 shadow-sm transition hover:bg-slate-50">Cancelar</button><button type="submit" disabled={formik.isSubmitting} className="inline-flex items-center justify-center rounded-lg bg-primary px-4 py-2 text-sm font-medium text-white shadow-sm transition hover:bg-primary-hover disabled:cursor-not-allowed disabled:opacity-60">{formik.isSubmitting ? <><span className="mr-2 size-4 animate-spin rounded-full border-2 border-white/30 border-t-white" />Guardando...</> : "Guardar"}</button></div></form></div></div>);
};
