import { apiClient, getApiErrorMessage } from "@shared/services/api.client"; import type { PaginatedData, ResponseApi } from "@shared/types/api.response.types"; import { ACADEMIC_SUBLEVEL_ENDPOINTS } from "./academic-sublevel.constants"; import type { AcademicSubLevelCreateDataT, AcademicSubLevelDeleteParamsT, AcademicSubLevelGetParamsT, AcademicSubLevelListParamsT, AcademicSubLevelServiceT, AcademicSubLevelT, AcademicSubLevelUpdateParamsT } from "./academic-sublevel.types";
class AcademicSubLevelService implements AcademicSubLevelServiceT {
  async list(p?: AcademicSubLevelListParamsT): Promise<AcademicSubLevelT[]> { try { const pg = p?.page ?? 1; const ps = p?.pageSize ?? 100; const sq = p?.search ? `&search=${encodeURIComponent(p.search)}` : ""; const oq = p?.ordering ? `&ordering=${encodeURIComponent(p.ordering)}` : ""; const { data } = await apiClient.get<ResponseApi<PaginatedData<AcademicSubLevelT>>>(`${ACADEMIC_SUBLEVEL_ENDPOINTS.LIST}?page=${pg}&page_size=${ps}${sq}${oq}`); return data.data.results; } catch (error) { throw new Error(getApiErrorMessage(error), { cause: error }); } }
  async get(id: AcademicSubLevelGetParamsT): Promise<AcademicSubLevelT> { try { const { data } = await apiClient.get<ResponseApi<AcademicSubLevelT>>(ACADEMIC_SUBLEVEL_ENDPOINTS.DETAIL(id)); return data.data; } catch (error) { throw new Error(getApiErrorMessage(error), { cause: error }); } }
  async create(d: AcademicSubLevelCreateDataT): Promise<AcademicSubLevelT> { try { const { data } = await apiClient.post<ResponseApi<AcademicSubLevelT>>(ACADEMIC_SUBLEVEL_ENDPOINTS.LIST, d); return data.data; } catch (error) { throw new Error(getApiErrorMessage(error), { cause: error }); } }
  async update(p: AcademicSubLevelUpdateParamsT): Promise<AcademicSubLevelT> { try { const { data } = await apiClient.patch<ResponseApi<AcademicSubLevelT>>(ACADEMIC_SUBLEVEL_ENDPOINTS.DETAIL(p.id), p.data); return data.data; } catch (error) { throw new Error(getApiErrorMessage(error), { cause: error }); } }
  async softDelete(id: AcademicSubLevelDeleteParamsT): Promise<{ id: number }> { try { const { data } = await apiClient.post<ResponseApi<{ id: number }>>(ACADEMIC_SUBLEVEL_ENDPOINTS.SOFT_DELETE(id)); return data.data; } catch (error) { throw new Error(getApiErrorMessage(error), { cause: error }); } }
}
export const academicSubLevelService = new AcademicSubLevelService();
