import { useAppDispatch, useAppSelector } from "@shared/redux/hooks"; import { useCallback, useState } from "react"; import { academicSubLevelService } from "./academic-sublevel.service"; import { loadPending, loadSuccess, loadError, entityCreated, entityUpdated, entityDeleted, mutationError, selectAcademicSubLevels, selectAcademicSubLevelsStatus, selectAcademicSubLevelError } from "./academic-sublevel.slice"; import type { AcademicSubLevelCreateDataT, AcademicSubLevelCreateParamsT, AcademicSubLevelDeleteParamsT, AcademicSubLevelFormValues, AcademicSubLevelListParamsT, AcademicSubLevelT, AcademicSubLevelUpdateParamsT } from "./academic-sublevel.types";
export type CreateRejectValue = { msg: string; data: Record<string, string> | null; }; export type ValidationErrors = Record<string, string>; export interface SubmitErrorState { general: string[]; validation: ValidationErrors; }
const toRejectValue = (e: unknown): CreateRejectValue => { const msg = e instanceof Error ? e.message : "Error desconocido"; const cause = e instanceof Error ? (e as { cause?: unknown }).cause : undefined; const d = (cause as { response?: { data?: { data?: unknown } } })?.response?.data; return { msg, data: (d?.data as Record<string, string> | null) ?? null }; };
export const useAcademicSubLevelController = () => {
  const dispatch = useAppDispatch(); const items = useAppSelector(selectAcademicSubLevels); const status = useAppSelector(selectAcademicSubLevelsStatus); const error = useAppSelector(selectAcademicSubLevelError);
  const load = useCallback(async (p?: AcademicSubLevelListParamsT) => { dispatch(loadPending()); try { const items = await academicSubLevelService.list(p ?? { page: 1, pageSize: 100 }); dispatch(loadSuccess(items)); } catch (err) { dispatch(loadError(err instanceof Error ? err.message : "Error")); } }, [dispatch]);
  const create = useCallback(async (d: AcademicSubLevelCreateParamsT): Promise<AcademicSubLevelT> => { try { const c = await academicSubLevelService.create(d); dispatch(entityCreated(c)); return c; } catch (err) { const rv = toRejectValue(err); dispatch(mutationError(rv.msg)); throw rv; } }, [dispatch]);
  const update = useCallback(async (p: AcademicSubLevelUpdateParamsT): Promise<AcademicSubLevelT> => { try { const u = await academicSubLevelService.update(p); dispatch(entityUpdated(u)); return u; } catch (err) { const rv = toRejectValue(err); dispatch(mutationError(rv.msg)); throw rv; } }, [dispatch]);
  const remove = useCallback(async (id: AcademicSubLevelDeleteParamsT): Promise<void> => { try { const { id: did } = await academicSubLevelService.softDelete(id); dispatch(entityDeleted(did)); } catch (err) { dispatch(mutationError(err instanceof Error ? err.message : "Error")); } }, [dispatch]);
  return { academicSubLevels: items, isLoading: status === "loading", error, loadAcademicSubLevels: load, createAcademicSubLevel: create, updateAcademicSubLevel: update, deleteAcademicSubLevel: remove };
};
export type ASLControllerT = ReturnType<typeof useAcademicSubLevelController>;
const extractError = (e: unknown) => { if (e && typeof e === "object" && "msg" in e && typeof (e as { msg?: unknown }).msg === "string") { const obj = e as CreateRejectValue; const fes: ValidationErrors = {}; const gen: string[] = []; if (obj.data && typeof obj.data === "object") { for (const [k, v] of Object.entries(obj.data)) { if (typeof v === "string") fes[k] = v; else gen.push(`${k}: ${v}`); } } if (gen.length === 0 && Object.keys(fes).length === 0) gen.push(obj.msg); return { msg: obj.msg, general: gen, validation: fes }; } const msg = e instanceof Error ? e.message : "Error desconocido"; return { msg, general: [msg], validation: {} }; };
const uwCreate = async (d: AcademicSubLevelCreateDataT, create: ASLControllerT["createAcademicSubLevel"]) => { try { return { ok: true as const, result: await create(d), errors: { general: [], validation: {} } as SubmitErrorState }; } catch (e) { const p = extractError(e); return { ok: false as const, result: null, errors: { general: p.general, validation: p.validation } as SubmitErrorState }; } };
const uwUpdate = async (p: AcademicSubLevelUpdateParamsT, update: ASLControllerT["updateAcademicSubLevel"]) => { try { return { ok: true as const, result: await update(p), errors: { general: [], validation: {} } as SubmitErrorState }; } catch (e) { const p2 = extractError(e); return { ok: false as const, result: null, errors: { general: p2.general, validation: p2.validation } as SubmitErrorState }; } };
interface UseFormArgs { create: ASLControllerT["createAcademicSubLevel"]; update: ASLControllerT["updateAcademicSubLevel"]; }
export const useAcademicSubLevelForm = ({ create, update }: UseFormArgs) => {
  const [isOpen, setIsOpen] = useState(false); const [editing, setEditing] = useState<AcademicSubLevelT | null>(null); const [submitErrors, setSubmitErrors] = useState<SubmitErrorState>({ general: [], validation: {} }); const isEdit = !!editing;
  const openModal = useCallback((s?: AcademicSubLevelT) => { setEditing(s ?? null); setSubmitErrors({ general: [], validation: {} }); setIsOpen(true); }, []);
  const closeModal = useCallback(() => { setIsOpen(false); setEditing(null); setSubmitErrors({ general: [], validation: {} }); }, []);
  const handleSubmit = useCallback(async (values: AcademicSubLevelFormValues) => { setSubmitErrors({ general: [], validation: {} }); if (editing) { const { code, name, description, academic_level, is_active } = values; const r = await uwUpdate({ id: editing.id, data: { code, name, description, academic_level, is_active } }, update); if (r.ok) { closeModal(); return; } setSubmitErrors(r.errors); } else { const { code, name, description, academic_level } = values; const r = await uwCreate({ code, name, description, academic_level }, create); if (r.ok) { closeModal(); return; } setSubmitErrors(r.errors); } }, [editing, create, update, closeModal]);
  return { isOpen, isEdit, editingAcademicSubLevel: editing, submitErrors, openModal, closeModal, handleSubmit };
};
