import { useCallback, useEffect, useRef, useState } from "react"; import { tableClassname, tableColumnsClassname, tableFirstColumnClassname } from "@app/styles/styles"; import { SearchInput } from "@shared/components/Form"; import { Pagination } from "@shared/components/Pagination"; import { CustomTable } from "@shared/components/Table"; import { useGradeHistoryController } from "./grade-history.controller"; import type { TableColumnProps } from "@shared/components/Table"; import type { GradeChangeHistoryOrderingT, GradeChangeHistoryT } from "./grade-history.types";
const O: { label: string; value: GradeChangeHistoryOrderingT }[] = [{ label: "Nota (A-Z)", value: "student_note_name" }, { label: "Nota (Z-A)", value: "-student_note_name" }, { label: "Modificado por (A-Z)", value: "modified_by_user_name" }, { label: "Modificado por (Z-A)", value: "-modified_by_user_name" }, { label: "Fecha (asc)", value: "modified_at" }, { label: "Fecha (desc)", value: "-modified_at" }, { label: "Antes (asc)", value: "previous_score" }, { label: "Antes (desc)", value: "-previous_score" }, { label: "Nuevo (asc)", value: "new_score" }, { label: "Nuevo (desc)", value: "-new_score" }];
export default function GradeHistoryPage() {
  const { gradeHistoryItems, isLoading, loadGradeHistory } = useGradeHistoryController();
  const [search, setSearch] = useState(""); const [page, setPage] = useState(1); const [pageSize, setPageSize] = useState(10); const [ordering, setOrdering] = useState<GradeChangeHistoryOrderingT>("-modified_at"); const [hasSearched, setHasSearched] = useState(false);
  const dr = useRef<ReturnType<typeof setTimeout>>(undefined);
  const fetchData = useCallback((o?: { page?: number; pageSize?: number; search?: string; ordering?: GradeChangeHistoryOrderingT }) => { loadGradeHistory({ page: o?.page ?? page, pageSize: o?.pageSize ?? pageSize, search: o?.search !== undefined ? o.search : search || undefined, ordering: o?.ordering ?? ordering }); }, [loadGradeHistory, page, pageSize, search, ordering]);
  useEffect(() => { fetchData(); }, []); // eslint-disable-line react-hooks/exhaustive-deps
  const hSearch = useCallback((e: React.ChangeEvent<HTMLInputElement>) => { const v = e.target.value; setSearch(v); setPage(1); setHasSearched(true); if (dr.current) clearTimeout(dr.current); dr.current = setTimeout(() => { fetchData({ page: 1, search: v || undefined }); }, 400); }, [fetchData]);
  const hOrder = useCallback((e: React.ChangeEvent<HTMLSelectElement>) => { const n = e.target.value as GradeChangeHistoryOrderingT; setOrdering(n); setPage(1); fetchData({ page: 1, ordering: n }); }, [fetchData]);
  const hnp = gradeHistoryItems.length >= pageSize;
  const cols: TableColumnProps<GradeChangeHistoryT>[] = [{ key: "student_note_name", label: "Nota", className: tableFirstColumnClassname }, { key: "modified_by_user_name", label: "Modificado por", className: tableColumnsClassname }, { key: "previous_score", label: "Antes", className: tableColumnsClassname, render: (s) => <span>{s.previous_score}</span> }, { key: "new_score", label: "Nuevo", className: tableColumnsClassname, render: (s) => <span>{s.new_score}</span> }, { key: "reason", label: "Motivo", className: tableColumnsClassname, render: (s) => <span>{s.reason}</span> }, { key: "modified_at", label: "Fecha", className: tableColumnsClassname, render: (s) => <span>{s.modified_at}</span> }];
  return (<div className="space-y-4"><div className="flex flex-col items-start justify-between gap-4 sm:flex-row sm:items-center"><div><h1 className="text-2xl font-extrabold text-slate-800">Historial de Calificaciones</h1><p className="mt-1 text-sm text-slate-500">Consulta los cambios realizados en las calificaciones</p></div></div><div className="overflow-visible rounded-xl border border-slate-200 bg-white shadow-sm"><div className="flex flex-wrap items-center gap-3 border-b border-slate-200 bg-slate-50/50 px-4 py-3"><SearchInput name="search" type="text" onChange={hSearch} value={search} className="relative min-w-50 flex-1" placeholder="Filtrar historial..." /><select value={ordering} onChange={hOrder} className="block w-auto rounded-md border border-gray-300 bg-white px-3 py-2 text-sm text-gray-700 focus:border-blue-500 focus:outline-none focus:ring-1 focus:ring-blue-500">{O.map((o) => <option key={o.value} value={o.value}>{o.label}</option>)}</select></div><CustomTable<GradeChangeHistoryT> data={gradeHistoryItems} columns={cols} isLoading={isLoading && gradeHistoryItems.length === 0} emptyMessage={hasSearched ? "No se encontraron registros con los filtros" : "No se encontraron registros de historial"} className={tableClassname} loadingMessage="Cargando historial..." /><Pagination page={page} pageSize={pageSize} totalItems={gradeHistoryItems.length} isLoading={isLoading} hasNextPage={hnp} onPageChange={(np) => { setPage(np); fetchData({ page: np }); }} onPageSizeChange={(ns) => { setPageSize(ns); setPage(1); fetchData({ page: 1, pageSize: ns }); }} /></div></div>);
}
