import { useFormik } from "formik"; import { useEffect } from "react";
import { checkboxClassname, inputClassname, selectClassname } from "@app/styles/styles"; import { CustomCheckbox, CustomInput, CustomSelect } from "@shared/components/Form";
import type { SubmitErrorState } from "../enrollments.controller"; import type { EnrollmentFormValues, EnrollmentT } from "../enrollments.types";

const getFieldLabel = (f: string): string => ({ section: "Curso", enrollment_status: "Estado", is_repeat: "Repite", student_condition: "Condición", cellphone: "Teléfono", email: "Correo", observations: "Observaciones", non_field_errors: "Error general" }[f] || f);

interface Props { isOpen: boolean; onClose: () => void; isEdit: boolean; editingEnrollment: EnrollmentT | null; onSubmit: (values: EnrollmentFormValues) => Promise<void>; submitErrors: SubmitErrorState; sectionOptions: { label: string; value: string }[]; }

export const EnrollmentFormModal = ({ isOpen, onClose, isEdit, editingEnrollment, onSubmit, submitErrors, sectionOptions }: Props) => {
  const getIV = (): EnrollmentFormValues => { if (editingEnrollment) return { section: editingEnrollment.section, enrollment_status: editingEnrollment.enrollment_status, is_repeat: editingEnrollment.is_repeat, student_condition: editingEnrollment.student_condition, cellphone: editingEnrollment.cellphone, email: editingEnrollment.email, observations: editingEnrollment.observations, is_active: editingEnrollment.is_active }; return { section: 0, enrollment_status: "ACT", is_repeat: false, student_condition: "", cellphone: "", email: "", observations: "", is_active: true }; };
  const formik = useFormik<EnrollmentFormValues>({ initialValues: getIV(), enableReinitialize: true, onSubmit });
  useEffect(() => { if (isOpen && editingEnrollment) formik.setValues(getIV()); }, [isOpen, editingEnrollment]);
  if (!isOpen) return null;
  return (<div className="fixed inset-0 z-50 flex items-center justify-center"><div className="absolute inset-0 bg-black/40" onClick={onClose} /><div className="relative w-full max-w-md animate-slide-up overflow-hidden rounded-xl bg-white shadow-xl"><div className="flex items-center justify-between border-b border-slate-200 px-5 py-4"><div><h3 className="text-lg font-semibold text-slate-900">{isEdit ? "Editar" : "Nueva"} Matrícula</h3><p className="mt-0.5 text-sm text-slate-500">Complete los datos de la matrícula</p></div><button type="button" onClick={onClose} className="rounded-lg p-1.5 text-slate-400 hover:bg-slate-100"><svg className="size-5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" /></svg></button></div>
    {(submitErrors.general.length > 0 || Object.keys(submitErrors.validation).length > 0) && (<div className="mx-5 mt-3 rounded-lg border border-red-300 bg-red-50 p-4 shadow-sm"><div className="flex items-start gap-2"><svg className="mt-0.5 size-5 flex-shrink-0 text-red-600" fill="currentColor" viewBox="0 0 20 20"><path fillRule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zM8.707 7.293a1 1 0 00-1.414 1.414L8.586 10l-1.293 1.293a1 1 0 101.414 1.414L10 11.414l1.293 1.293a1 1 0 001.414-1.414L11.414 10l1.293-1.293a1 1 0 00-1.414-1.414L10 8.586 8.707 7.293z" clipRule="evenodd" /></svg><div className="flex-1"><p className="mb-2 text-sm font-semibold text-red-800">Error al guardar</p>{submitErrors.general.length > 0 && (<ul>{submitErrors.general.map((e, i) => (<li key={i} className="text-sm text-red-700">• {e}</li>))}</ul>)}{Object.keys(submitErrors.validation).length > 0 && (<ul>{Object.entries(submitErrors.validation).map(([f, m]) => (<li key={f} className="text-sm text-red-700"><span className="font-semibold">{getFieldLabel(f)}:</span> {m}</li>))}</ul>)}</div></div></div>)}
    <form onSubmit={formik.handleSubmit} className="space-y-4 p-5"><CustomSelect label="Curso" name="section" value={String(formik.values.section)} onChange={(o) => formik.setFieldValue("section", Number(o.value))} options={sectionOptions} className={selectClassname} error={formik.touched.section ? formik.errors.section : undefined} /><CustomSelect label="Estado" name="enrollment_status" value={formik.values.enrollment_status} onChange={(o) => formik.setFieldValue("enrollment_status", String(o.value))} options={[{ label: "Activo", value: "ACT" }, { label: "Retirado", value: "WITHDRAWN" }, { label: "Egresado", value: "GRADUATED" }]} className={selectClassname} error={formik.touched.enrollment_status ? formik.errors.enrollment_status : undefined} /><CustomInput label="Teléfono" name="cellphone" value={formik.values.cellphone ?? ""} onBlur={formik.handleBlur} onChange={formik.handleChange} type="text" error={formik.touched.cellphone ? formik.errors.cellphone : undefined} className={inputClassname} /><CustomInput label="Correo Electrónico" name="email" value={formik.values.email ?? ""} onBlur={formik.handleBlur} onChange={formik.handleChange} type="email" error={formik.touched.email ? formik.errors.email : undefined} className={inputClassname} /><CustomInput label="Observaciones" name="observations" value={formik.values.observations ?? ""} onBlur={formik.handleBlur} onChange={formik.handleChange} type="text" error={formik.touched.observations ? formik.errors.observations : undefined} className={inputClassname} /><CustomCheckbox name="is_repeat" checked={formik.values.is_repeat} onChange={formik.handleChange} onBlur={formik.handleBlur} label="Estudiante repite el año" className={checkboxClassname} />{isEdit && <CustomCheckbox name="is_active" checked={formik.values.is_active} onChange={formik.handleChange} onBlur={formik.handleBlur} label="Activo" className={checkboxClassname} />}<div className="flex items-center justify-end gap-3 border-t border-slate-200 pt-4"><button type="button" onClick={onClose} className="rounded-lg border border-slate-300 bg-white px-4 py-2 text-sm font-medium text-slate-700 hover:bg-slate-50">Cancelar</button><button type="submit" disabled={formik.isSubmitting} className="rounded-lg bg-primary px-4 py-2 text-sm font-medium text-white hover:bg-primary-hover disabled:opacity-60">{formik.isSubmitting ? "Guardando..." : isEdit ? "Actualizar" : "Crear"}</button></div></form></div></div>);
};
